### ISSUE TITLE
Python3 build broken by mps_reader.h

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1029]
The `/home/dan/dev/z3/src/src/util/lp/mps_reader.h` file on line 658 contains some invalid characters. In vim the line renders like this.

```
E   [rhs, rhs + |range|]     if range ¡Ý 0 [rhs - |range|, rhs]     if range < 0
```
This isn't valid utf8 and causes the `scripts/mk_gparams_register_modules_cpp.py` script to raise an exception when using Python 3.

```
Traceback (most recent call last):
  File "/home/dan/dev/z3/src/scripts/mk_gparams_register_modules_cpp.py", line 38, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/dan/dev/z3/src/scripts/mk_gparams_register_modules_cpp.py", line 32, in main
    pargs.destination_dir
  File "/home/dan/dev/z3/src/scripts/mk_genfile_common.py", line 623, in mk_gparams_register_modules_internal
    for line in fin:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 6344: invalid start by
```

It's just a comment so deleting the line unbreaks the build for me. That's not an ideal fix though. I would create a fix myself if I knew what the comment was supposed to say. @NikolajBjorner @levnach Could you please fix this line so the file is valid utf-8?

**Comment by delcypher** [comment]
@NikolajBjorner Thanks for fixing :)
