### ISSUE TITLE
Using the java bindings under Windows

### ISSUE THREAD

**Issue by proteusGIT** [Z3Prover/z3#1064]
Seems like a recurring issue but I still have to ask on how to run, for example, the JavaExample.class.
```
"C:\Program Files\Java\jdk1.8.0_121\bin\java" -cp "z3-4.5.1.a8ff97c0f446-x64-win\z3-4.5.1.a8ff97c0f446-x64-win\bin\com.microsoft.z3.jar;." -Djava.library.path="z3-4.5.1.a8ff97c0f446-x64-win\z3-4.5.1.a8ff97c0f446-x64-win\:%PATH%" JavaExample
Exception in thread "main" java.lang.UnsatisfiedLinkError: no libz3java in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at com.microsoft.z3.Native.<clinit>(Native.java:14)
        at com.microsoft.z3.Global.ToggleWarningMessages(Global.java:87)
        at JavaExample.main(JavaExample.java:2287)
```

The readme says to use the following but I have the .class file not in the "z3\bin" directory...
```
   java -cp com.microsoft.z3.jar;. JavaExample
```

I also made sure that I am using only 64 components...
Does it work on other windows machines?

**Comment by wintersteiger** [comment]
On Windows, `...:%PATH%` should be `...;%PATH%` (; instead of :). Also, java.libray.path may need to contain the `bin` directory instead of the top-level, if you are using a nightly or release package (it needs to see com.microsoft.z3.jar).  If that doesn't fix it, try adding the directory containing libz3.dll and libz3java.dll to your system's PATH instead of java.library.path. I never know which one of them works in what situations and/or different versions of Java.

**Comment by NikolajBjorner** [comment]
@proteusGIT, does this address your issue?

**Comment by proteusGIT** [comment]
I did not have the time yet to look into this again. I need a couple of days more...
Still, thank you very much already...

**Comment by NikolajBjorner** [comment]
Closing per no activity
