### ISSUE TITLE
Java API recusing to return candidate model

### ISSUE THREAD

**Issue by facanferff** [Z3Prover/z3#1109]
Hi, I'm trying to obtain a candidate model when Z3 returns "unknown". For that, I configure the solver with the parameter "candidate_models" set to true. The solver gives "unknown" with a reason "smt tactic failed to show goal to be sat/unsat (incomplete quantifiers)", which is expected, and then try to obtain the (candidate) model using solver.getModel() but it just throws an exception (even if I don't set the parameter):

```
com.microsoft.z3.Z3Exception: invalid usage
	at com.microsoft.z3.Native.solverGetModel(Native.java:4430)
	at com.microsoft.z3.Solver.getModel(Solver.java:247)
        ...
```

Is the parameter not the correct one? Or am I missing something?

Thanks.

**Comment by NikolajBjorner** [comment]
repro?

**Comment by facanferff** [comment]
For example, I have the following options provided by parsing a SMT file through the Java API:
```
(set-option :auto_config false)
(set-option :smt.mbqi false)

(set-option :model_evaluator.completion false)
(set-option :model.v1 true)
(set-option :smt.phase_selection 0)
(set-option :smt.restart_strategy 0)
(set-option :smt.restart_factor 1.5)
(set-option :nnf.sk_hack true)
(set-option :smt.qi.eager_threshold 100.0)
(set-option :smt.arith.random_initial_value true)
(set-option :smt.case_split 3)
(set-option :smt.delay_units true)
(set-option :smt.delay_units_threshold 16)
(set-option :type_check true)
(set-option :smt.bv.reflect true)
(set-option :smt.timeout 10000)
```

The sort/function declarations and assertions (this was obtained by using solver.toString()) are:
```
(declare-datatypes () ((General (G_Boolean (of_G_Boolean Bool)) (G_Integer (of_G_Integer Int)) (G_String (of_G_String String)) (G_Null))))
(declare-sort SVMap)
(declare-sort IVMap)
(declare-datatypes () ((Value (G (out_G General)) (E (out_E SVMap)) (C (out_C IVMap)) (R (type String) (representations Value) (identifiers Value)))))
(declare-datatypes () ((ValueOption (NoValue) (SomeValue (of_SomeValue Value)))))
(declare-fun r_resourceidof (Value Value) Value)
(declare-fun v_contains (Value Value) Value)
(declare-fun r_representationof (Value Value) Value)
(declare-fun In_String (Value) Bool)
(declare-fun v_nth (Value Value) Value)
(declare-fun v_integer (Int) Value)
(declare-fun v_length (Value) Value)
(declare-fun v_ff () Value)
(declare-fun v_tt () Value)
(declare-fun alphai (IVMap) (Array Int ValueOption))
(declare-fun Good_C (Value) Bool)
(declare-fun betai ((Array Int ValueOption)) IVMap)
(declare-fun v_cempty () Value)
(declare-fun FiniteC ((Array Int ValueOption)) Bool)
(declare-fun v_dot (String Value) Value)
(declare-fun alphas (SVMap) (Array String ValueOption))
(declare-fun v_has_field (String Value) Bool)
(declare-fun betas ((Array String ValueOption)) SVMap)
(declare-fun v_eempty () Value)
(declare-fun Good_E (Value) Bool)
(declare-fun FiniteE ((Array String ValueOption)) Bool)
(declare-fun v_string (String) Value)
(declare-fun O_LE (Value Value) Value)
(declare-fun O_LT (Value Value) Value)
(declare-fun O_GT (Value Value) Value)
(declare-fun O_GE (Value Value) Value)
(declare-fun O_Or (Value Value) Value)
(declare-fun O_And (Value Value) Value)
(declare-fun O_Minus (Value) Value)
(declare-fun O_Not (Value) Value)
(declare-fun O_NE (Value Value) Value)
(declare-fun O_EQ (Value Value) Value)
(declare-fun O_Mult (Value Value) Value)
(declare-fun O_Sub (Value Value) Value)
(declare-fun O_Sum (Value Value) Value)
(declare-fun In_Integer (Value) Bool)
(declare-fun In_Boolean (Value) Bool)
(declare-fun v_boolean (Bool) Value)
(declare-fun v_isnull (Value) Value)
(declare-fun v_null () Value)
(declare-fun Good_R (Value) Bool)
(declare-fun request () Value)
(declare-fun root () Value)
(assert (let ((a!1 (forall ((v Value))
             (! (= (v_isnull v) (ite (= v v_null) v_tt v_ff))
                :pattern ((v_isnull v)))))
      (a!2 (forall ((b Bool))
             (! (= (v_boolean b) (G (G_Boolean b))) :pattern ((v_boolean b)))))
      (a!3 (forall ((i Int))
             (! (= (v_integer i) (G (G_Integer i))) :pattern ((v_integer i)))))
      (a!4 (forall ((s String))
             (! (= (v_string s) (G (G_String s))) :pattern ((v_string s)))))
      (a!5 (forall ((v Value))
             (! (= (In_Boolean v) (and (is-G v) (is-G_Boolean (out_G v))))
                :pattern ((In_Boolean v)))))
      (a!6 (forall ((v Value))
             (! (= (In_Integer v) (and (is-G v) (is-G_Integer (out_G v))))
                :pattern ((In_Integer v)))))
      (a!7 (forall ((v Value))
             (! (= (In_String v) (and (is-G v) (is-G_String (out_G v))))
                :pattern ((In_String v)))))
      (a!8 (forall ((v1 Value) (v2 Value))
             (! (= (O_EQ v1 v2) (ite (= v1 v2) v_tt v_ff))
                :pattern ((O_EQ v1 v2)))))
      (a!9 (forall ((v1 Value) (v2 Value))
             (! (= (O_NE v1 v2) (ite (= v1 v2) v_ff v_tt))
                :pattern ((O_NE v1 v2)))))
      (a!10 (forall ((v Value))
              (! (= (O_Not v) (ite (not (= v v_tt)) v_tt v_ff))
                 :pattern ((O_Not v)))))
      (a!11 (forall ((v1 Value) (v2 Value))
              (! (= (O_And v1 v2) (ite (and (= v1 v_tt) (= v2 v_tt)) v_tt v_ff))
                 :pattern ((O_And v1 v2)))))
      (a!12 (forall ((v1 Value) (v2 Value))
              (! (= (O_Or v1 v2) (ite (or (= v1 v_tt) (= v2 v_tt)) v_tt v_ff))
                 :pattern ((O_Or v1 v2)))))
      (a!13 (forall ((v Value))
              (! (let ((a!1 (= (str.len (of_G_String (out_G v)))
                               (of_G_Integer (out_G (v_length v))))))
                   (=> (and (is-G v) (is-G_String (out_G v))) a!1))
                 :pattern ((v_length v)))))
      (a!14 (forall ((v1 Value) (v2 Value))
              (! (let ((a!1 (ite (str.contains (of_G_String (out_G v1))
                                               (of_G_String (out_G v2)))
                                 v_tt
                                 v_ff)))
                   (=> (and (is-G v1)
                            (is-G_String (out_G v1))
                            (is-G v2)
                            (is-G_String (out_G v2)))
                       (= (v_contains v1 v2) a!1)))
                 :pattern ((v_contains v1 v2)))))
      (a!15 (forall ((v Value) (i Int))
              (! (let ((a!1 (v_string (str.at (of_G_String (out_G v)) i))))
                   (=> (and (is-G v) (is-G_String (out_G v)))
                       (= (v_nth v (v_integer i)) a!1)))
                 :pattern ((v_nth v (v_integer i))))))
      (a!16 (forall ((am (Array String ValueOption)))
              (=> (FiniteE am) (= (alphas (betas am)) am))))
      (a!17 (forall ((svm SVMap))
              (and (FiniteE (alphas svm)) (= (betas (alphas svm)) svm))))
      (a!18 (forall ((svm (Array String ValueOption)))
              (! (= (FiniteE svm) (= (default svm) NoValue))
                 :pattern ((FiniteE svm)))))
      (a!19 (= v_eempty
               (E (betas ((as const (Array String ValueOption)) NoValue)))))
      (a!20 (forall ((l String) (svm SVMap))
              (! (let ((a!1 (not (= (select (alphas svm) l) NoValue))))
                   (= (v_has_field l (E svm)) a!1))
                 :pattern ((v_has_field l (E svm))))))
      (a!21 (forall ((l String) (svm SVMap))
              (! (= (v_dot l (E svm)) (of_SomeValue (select (alphas svm) l)))
                 :pattern ((v_dot l (E svm))))))
      (a!22 (forall ((am (Array Int ValueOption)))
              (=> (FiniteC am) (= (alphai (betai am)) am))))
      (a!23 (forall ((ivm IVMap))
              (and (FiniteC (alphai ivm)) (= (betai (alphai ivm)) ivm))))
      (a!24 (forall ((ivm (Array Int ValueOption)))
              (! (= (FiniteC ivm) (= (default ivm) NoValue))
                 :pattern ((FiniteC ivm)))))
      (a!25 (= v_cempty
               (C (betai ((as const (Array Int ValueOption)) NoValue)))))
      (a!26 (forall ((v Value) (i Int))
              (! (let ((a!1 (of_SomeValue (select (alphai (out_C v)) i))))
                   (=> (Good_C v) (= (v_nth v (v_integer i)) a!1)))
                 :pattern ((v_nth v (v_integer i))))))
      (a!27 (forall ((v1 Value) (v2 Value))
              (! (let ((a!1 (exists ((i Int))
                              (let ((a!1 (< i
                                            (of_G_Integer (out_G (v_length v1))))))
                                (and (<= 0 i)
                                     a!1
                                     (= (v_nth v1 (v_integer i)) v2))))))
                   (=> (and (is-C v1))
                       (= (v_contains v1 v2) (ite a!1 v_tt v_ff))))
                 :pattern ((v_contains v1 v2)))))
      (a!28 (forall ((v Value))
              (! (=> (is-R v)
                     (and (is-C (representations v)) (is-C (representations v))))
                 :pattern ((is-R v)))))
      (a!29 (forall ((v Value) (r Value))
              (! (=> (is-R r)
                     (= (r_representationof v r)
                        (v_contains (representations r) v)))
                 :pattern ((r_representationof v r)))))
      (a!30 (forall ((v Value) (r Value))
              (! (=> (is-R r)
                     (= (r_resourceidof v r) (v_contains (identifiers r) v)))
                 :pattern ((r_resourceidof v r))))))
  (and (forall ((v Value)) (! (= (Good_C v) (is-C v)) :pattern ((Good_C v))))
       (forall ((v Value)) (! (= (Good_E v) (is-E v)) :pattern ((Good_E v))))
       (forall ((v Value)) (! (= (Good_R v) (is-R v)) :pattern ((Good_R v))))
       (= v_tt (G (G_Boolean true)))
       (= v_ff (G (G_Boolean false)))
       (= v_null (G G_Null))
       a!1
       a!2
       a!3
       a!4
       a!5
       a!6
       a!7
       (forall ((v1 Value) (v2 Value))
         (! (let ((a!1 (v_integer (+ (of_G_Integer (out_G v1))
                                     (of_G_Integer (out_G v2))))))
              (= (O_Sum v1 v2) a!1))
            :pattern ((O_Sum v1 v2))))
       (forall ((v1 Value) (v2 Value))
         (! (let ((a!1 (v_integer (- (of_G_Integer (out_G v1))
                                     (of_G_Integer (out_G v2))))))
              (= (O_Sub v1 v2) a!1))
            :pattern ((O_Sub v1 v2))))
       (forall ((v1 Value) (v2 Value))
         (! (let ((a!1 (v_integer (* (of_G_Integer (out_G v1))
                                     (of_G_Integer (out_G v2))))))
              (= (O_Mult v1 v2) a!1))
            :pattern ((O_Mult v1 v2))))
       a!8
       a!9
       a!10
       (forall ((v Value))
         (! (let ((a!1 (v_integer (- (of_G_Integer (out_G v))))))
              (= (O_Minus v) a!1))
            :pattern ((O_Minus v))))
       a!11
       a!12
       (forall ((v1 Value) (v2 Value))
         (! (let ((a!1 (ite (>= (of_G_Integer (out_G v1))
                                (of_G_Integer (out_G v2)))
                            v_tt
                            v_ff)))
              (= (O_GE v1 v2) a!1))
            :pattern ((O_GE v1 v2))))
       (forall ((v1 Value) (v2 Value))
         (! (let ((a!1 (ite (> (of_G_Integer (out_G v1))
                               (of_G_Integer (out_G v2)))
                            v_tt
                            v_ff)))
              (= (O_GT v1 v2) a!1))
            :pattern ((O_GT v1 v2))))
       (forall ((v1 Value) (v2 Value))
         (! (let ((a!1 (ite (< (of_G_Integer (out_G v1))
                               (of_G_Integer (out_G v2)))
                            v_tt
                            v_ff)))
              (= (O_LT v1 v2) a!1))
            :pattern ((O_LT v1 v2))))
       (forall ((v1 Value) (v2 Value))
         (! (let ((a!1 (ite (<= (of_G_Integer (out_G v1))
                                (of_G_Integer (out_G v2)))
                            v_tt
                            v_ff)))
              (= (O_LE v1 v2) a!1))
            :pattern ((O_LE v1 v2))))
       a!13
       a!14
       a!15
       a!16
       a!17
       a!18
       (forall ((v Value))
         (! (let ((a!1 (and (is-E v) (FiniteE (alphas (out_E v))))))
              (= (Good_E v) a!1))
            :pattern ((Good_E v))))
       a!19
       a!20
       a!21
       a!22
       a!23
       a!24
       (forall ((v Value))
         (! (let ((a!1 (and (is-C v) (FiniteC (alphai (out_C v))))))
              (= (Good_C v) a!1))
            :pattern ((Good_C v))))
       (forall ((v Value))
         (! (let ((a!1 (>= (of_G_Integer (out_G (v_length v))) 0)))
              (=> (Good_C v) a!1))
            :pattern ((Good_C v))))
       (forall ((v Value))
         (! (let ((a!1 (forall ((i Int))
                         (let ((a!1 (< i (of_G_Integer (out_G (v_length v)))))
                               (a!2 (is-SomeValue (select (alphai (out_C v)) i))))
                           (=> (and (<= 0 i) a!1) a!2)))))
              (= (Good_C v) a!1))
            :pattern ((Good_C v))))
       a!25
       a!26
       a!27
       a!28
       (forall ((v Value))
         (let ((a!1 (forall ((i Int))
                      (let ((a!1 (of_G_Integer (out_G (v_length (representations v)))))
                            (a!2 (not (is-R (v_nth (representations v)
                                                   (v_integer i))))))
                        (=> (and (< 0 i) (< i a!1)) (and a!2))))))
           (=> (is-R v) a!1)))
       (forall ((v Value))
         (let ((a!1 (forall ((i Int))
                      (let ((a!1 (of_G_Integer (out_G (v_length (identifiers v)))))
                            (a!2 (and (In_String (v_nth (identifiers v)
                                                        (v_integer i))))))
                        (=> (and (< 0 i) (< i a!1)) a!2)))))
           (=> (is-R v) a!1)))
       a!29
       a!30)))
(assert (let ((a!1 (v_boolean (and (Good_E (v_dot "template" request)))))
      (a!2 (v_boolean (and (Good_E (v_dot "template" request))
                           (v_has_field "limit" (v_dot "template" request))
                           true)))
      (a!4 (v_boolean (and (Good_E (v_dot "template" request))
                           (v_has_field "page" (v_dot "template" request))
                           true)))
      (a!9 (O_And (O_LE (v_integer 1)
                        (v_dot "limit" (v_dot "template" request)))
                  (O_LE (v_dot "limit" (v_dot "template" request))
                        (v_integer 50))))
      (a!10 (O_And (O_LE (v_integer 1)
                         (v_dot "page" (v_dot "template" request)))
                   (O_LE (v_dot "page" (v_dot "template" request))
                         (v_integer 100000)))))
(let ((a!3 (v_boolean (and true (= (O_And a!1 a!2) v_tt))))
      (a!5 (v_boolean (and true (= (O_And a!1 a!4) v_tt))))
      (a!11 (and (Good_E (v_dot "template" request))
                 (v_has_field "limit" (v_dot "template" request))
                 (In_Integer (v_dot "limit" (v_dot "template" request)))
                 (= a!9 v_tt)
                 (v_has_field "page" (v_dot "template" request))
                 (In_Integer (v_dot "page" (v_dot "template" request)))
                 (= a!10 v_tt))))
(let ((a!6 (v_boolean (and true (= (O_And a!5 a!2) v_tt)))))
(let ((a!7 (= (O_Or (O_Or (O_Or a!1 a!3) a!5) a!6) v_tt)))
(let ((a!8 (= (O_And a!1 (v_boolean (and true a!7))) v_tt)))
  (and (In_String root)
       (Good_E request)
       (v_has_field "template" request)
       true
       a!8
       (v_has_field "header" request)
       (Good_E (v_dot "header" request))
       (v_has_field "location" request)
       (In_String (v_dot "location" request))
       (v_has_field "body" request)
       true
       (= (v_boolean a!11) v_tt))))))))
```

Also, after creating the solver, I do
```
Params params = context.mkParams();
params.add("candidate_models", true);
solver.setParameters(params);
```

If I set the option (set-option :produce-proofs true) (in a file containing everything above), the commandline-tool provides correctly a candidate model. I attempted also to set the parameter to solver "proof" but has the same result of throwing the exception.

**Comment by NikolajBjorner** [comment]
Thanks, it turned out that there is another setting on smt solvers that prevent candidate models from being produced. The option is fail_if_inconclusive. It takes precedence, or rather, it took precedence according to previous behavior. This confused me when trying out the repro, so I have it now that candidate_models take precedence. While fail_if_inconclusive is by default "true" it gets ignored if candidate_models is "true" (it is by default false).
You can either pick up the latest check-in and build yourself, wait for a build, or you can add the following to your code:

     Params params = context.mkParams();
     params.add("candidate_models", true);
     params.add("fail_if_inconclusive", false);
     solver.setParameters(params);

**Comment by facanferff** [comment]
Thanks, I confirm the option works.
