### ISSUE TITLE
Null pointer dereference in symbol::hash()

### ISSUE THREAD

**Issue by fumfel** [Z3Prover/z3#1170]
**Null pointer dereference in symbol::hash()**

Tested on HEAD: 3865c45

Faulting input: `(assert(let((a(+ 0)pi))`

To reproduce: `z3 -smt2 z3_nullptr`

ASAN log:

```
==28137==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000003dce2a3 bp 0xbebebebebebebebe sp 0x7fff1fcc6580 T0)
==28137==The signal is caused by a READ memory access.
==28137==Hint: address points to the zero page.
    #0 0x3dce2a2 in symbol::hash() const XYZ/z3/build/../src/util/symbol.h:92:43
    #1 0x3dce2a2 in symbol_table<smt2::parser::local>::key_data_hash_proc::operator()(symbol_table<smt2::parser::local>::key_data const&) const XYZ/z3/build/../src/util/symbol_table.h:50
    #2 0x3dce2a2 in core_hashtable<symbol_table<smt2::parser::local>::hash_entry, symbol_table<smt2::parser::local>::key_data_hash_proc, symbol_table<smt2::parser::local>::key_data_eq_proc>::get_hash(symbol_table<smt2::parser::local>::key_data const&) const XYZ/z3/build/../src/util/hashtable.h:155
    #3 0x3dce2a2 in core_hashtable<symbol_table<smt2::parser::local>::hash_entry, symbol_table<smt2::parser::local>::key_data_hash_proc, symbol_table<smt2::parser::local>::key_data_eq_proc>::find_core(symbol_table<smt2::parser::local>::key_data const&) const XYZ/z3/build/../src/util/hashtable.h:453
    #4 0x3dcda91 in symbol_table<smt2::parser::local>::insert(symbol, smt2::parser::local const&) XYZ/z3/build/../src/util/symbol_table.h:142:42
    #5 0x3dc5abc in smt2::parser::pop_let_frame(smt2::parser::let_frame*) XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:1666:27
    #6 0x3dba1c5 in smt2::parser::pop_expr_frame() XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:1782:17
    #7 0x3db98af in smt2::parser::parse_expr() XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:1812:21
    #8 0x3d982be in smt2::parser::parse_assert() XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:2236:13
    #9 0x3d954ea in smt2::parser::parse_cmd() XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:2628:17
    #10 0x3d8ee76 in smt2::parser::operator()() XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:2802:29
    #11 0x3d8c224 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:2851:12
    #12 0x530bcb in read_smtlib2_commands(char const*) XYZ/z3/build/../src/shell/smtlib_frontend.cpp:129:18
    #13 0x5172ac in main XYZ/z3/build/../src/shell/main.cpp:358:28
    #14 0x7f117c21682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #15 0x43e368 in _start (/usr/bin/z3+0x43e368)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV XYZ/z3/build/../src/util/symbol.h:92:43 in symbol::hash() const
==28137==ABORTING
```

**Comment by NikolajBjorner** [comment]
This is a duplicate
