### ISSUE TITLE
Null pointer dereference in func_decl::get_range()

### ISSUE THREAD

**Issue by fumfel** [Z3Prover/z3#1178]
**Null pointer dereference in func_decl::get_range()**

Tested on HEAD: e677030

Faulting input: `(define-sort FPN()(_ FloatingPoint 11 50))(declare-const mpfq FPN)(assert(= mpfq(fp.sqrt roundTowardNegative((_ to_fp 11 50)roundNearestTiesToEven 1.1028 5))))(check-sat-using(then fpa2bv))`

To reproduce: `z3 -smt2 z3_nullptr`

ASAN log:

```
==20539==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x000003ace1a5 bp 0x7ffec125ad50 sp 0x7ffec125a7e0 T0)
==20539==The signal is caused by a READ memory access.
==20539==Hint: address points to the zero page.
    #0 0x3ace1a4 in func_decl::get_range() const XYZ/z3/build/../src/ast/ast.h:606:39
    #1 0x3ace1a4 in fpa2bv_converter::mk_numeral(func_decl*, unsigned int, expr* const*, obj_ref<expr, ast_manager>&) XYZ/z3/build/../src/ast/fpa/fpa2bv_converter.cpp:138
    #2 0x3ace1a4 in fpa2bv_converter::mk_to_fp_real_int(func_decl*, unsigned int, expr* const*, obj_ref<expr, ast_manager>&) XYZ/z3/build/../src/ast/fpa/fpa2bv_converter.cpp:2726
    #3 0x3ab1462 in fpa2bv_converter::mk_to_fp(func_decl*, unsigned int, expr* const*, obj_ref<expr, ast_manager>&) XYZ/z3/build/../src/ast/fpa/fpa2bv_converter.cpp:2377:9
    #4 0x3b1a617 in fpa2bv_rewriter_cfg::reduce_app(func_decl*, unsigned int, expr* const*, obj_ref<expr, ast_manager>&, obj_ref<app, ast_manager>&) XYZ/z3/build/../src/ast/fpa/fpa2bv_rewriter.cpp:142:35
    #5 0x3b3bdc2 in void rewriter_tpl<fpa2bv_rewriter_cfg>::process_app<false>(app*, rewriter_core::frame&) XYZ/z3/build/../src/ast/rewriter/rewriter_def.h:260:30
    #6 0x3b2aea1 in void rewriter_tpl<fpa2bv_rewriter_cfg>::resume_core<false>(obj_ref<expr, ast_manager>&, obj_ref<app, ast_manager>&) XYZ/z3/build/../src/ast/rewriter/rewriter_def.h:695:13
    #7 0x3b280f2 in void rewriter_tpl<fpa2bv_rewriter_cfg>::main_loop<false>(expr*, obj_ref<expr, ast_manager>&, obj_ref<app, ast_manager>&) XYZ/z3/build/../src/ast/rewriter/rewriter_def.h:656:9
    #8 0x3b26ab2 in rewriter_tpl<fpa2bv_rewriter_cfg>::operator()(expr*, obj_ref<expr, ast_manager>&, obj_ref<app, ast_manager>&) XYZ/z3/build/../src/ast/rewriter/rewriter_def.h:726:9
    #9 0xa117c3 in fpa2bv_tactic::imp::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) XYZ/z3/build/../src/tactic/fpa/fpa2bv_tactic.cpp:78:17
    #10 0xa0fa72 in fpa2bv_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) XYZ/z3/build/../src/tactic/fpa/fpa2bv_tactic.cpp:148:13
    #11 0x4b7558a in cleanup_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) XYZ/z3/build/../src/tactic/tactical.cpp:1116:14
    #12 0x4ae5691 in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) XYZ/z3/build/../src/tactic/tactic.cpp:167:9
    #13 0x4ae691d in check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) XYZ/z3/build/../src/tactic/tactic.cpp:190:9
    #14 0x3f1f618 in check_sat_using_tactict_cmd::execute(cmd_context&) XYZ/z3/build/../src/cmd_context/tactic_cmds.cpp:226:25
    #15 0x3db70f6 in smt2::parser::parse_ext_cmd(int, int) XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:2602:33
    #16 0x3d93e96 in smt2::parser::parse_cmd() XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:2700:13
    #17 0x3d8d856 in smt2::parser::operator()() XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:2807:29
    #18 0x3d8ac04 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) XYZ/z3/build/../src/parsers/smt2/smt2parser.cpp:2856:12
    #19 0x530bcb in read_smtlib2_commands(char const*) XYZ/z3/build/../src/shell/smtlib_frontend.cpp:129:18
    #20 0x5172ac in main XYZ/z3/build/../src/shell/main.cpp:358:28
    #21 0x7f87ae97882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #22 0x43e368 in _start (/usr/bin/z3+0x43e368)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV XYZ/z3/build/../src/ast/ast.h:606:39 in func_decl::get_range() const
==20539==ABORTING
```

**Comment by NikolajBjorner** [comment]
It hits an assert in debug mode in the FP path where it expects a rational numeral to be an int64.
