### ISSUE TITLE
Python build uses --prefix incorrectly

### ISSUE THREAD

**Issue by skaller** [Z3Prover/z3#123]
OSX 10.6.8:

~/z3>   CXX=clang++ CC=clang python scripts/mk_make.py --prefix=/usr/local
opt = --prefix, arg = /usr/local
Traceback (most recent call last):
  File "scripts/mk_make.py", line 12, in <module>
    parse_options()
  File "/Users/johnskaller/z3/scripts/mk_util.py", line 600, in parse_options
    mk_dir(PYTHON_PACKAGE_DIR)
  File "/Users/johnskaller/z3/scripts/mk_util.py", line 656, in mk_dir
    os.makedirs(d)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.6'

The --prefix option should tell where to INSTALL the result, it should have nothing to do with where to find programs used to create the result. The PREFIX env variable option does not have this effect but i have no idea at this time if it influences the install location.

**Comment by NikolajBjorner** [comment]
Trace indicates you can't update the path under python2.6 from the installation script.
Could you either/and (1) update your version of python (2) chmod the appropriate directories?
