### ISSUE TITLE
how to use `xor` with Int type value?

### ISSUE THREAD

**Issue by 3xp10it** [Z3Prover/z3#1356]
I try to find two int value can match x1^x2==5 with below code,but find it can not run normorly.

```
from z3 import *
a=Int('x1')
b=Int('x2')
s=Solver()
s.add(BitVec(a,8)^BitVec(b,8)==BitVecVal(5,8))
s.check()
print(s.model())
```

Below is the debug message:

```
Traceback (most recent call last):
  File "3.py", line 5, in <module>
    s.add(BitVec(a,8)^BitVec(b,8)==BitVecVal(5,8))
  File "/usr/local/lib/python3.6/site-packages/z3/z3.py", line 3628, in BitVec
    return BitVecRef(Z3_mk_const(ctx.ref(), to_symbol(name, ctx), bv.ast), ctx)
  File "/usr/local/lib/python3.6/site-packages/z3/z3.py", line 106, in to_symbol
    return Z3_mk_string_symbol(_get_ctx(ctx).ref(), s)
  File "/usr/local/lib/python3.6/site-packages/z3/z3core.py", line 1430, in Z3_mk_string_symbol
    r = lib().Z3_mk_string_symbol(a0, _to_ascii(a1))
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

Then I try it with below two kinds of code,both works well,but I cannot understand why both of them works while upon code doesnot work,can you help me understand it?

```
from z3 import *
a=BitVec('x1',8)
b=BitVec('x2',8)
s=Solver()
s.add(a^b==BitVecVal(5,8))
s.check()
print(s.model())
```

```
from z3 import *
a=BitVec('x1',8)
b=BitVec('x2',8)
s=Solver()
s.add(a^b==5)
s.check()
print(s.model())
```

**Comment by NikolajBjorner** [comment]
The type of a^b in the last example is an 8-bit bit-vector. We overload == in python to work between bit-vector expressions and numeric constants. The numeric constant gets treated as a bit-vector.
XOR is not available on infinite precision integers.
