### ISSUE TITLE
AttributeError: 'BoolRef' object has no attribute 'assert_exprs'

### ISSUE THREAD

**Issue by UnnameBao** [Z3Prover/z3#1372]
I am a new beginner for using z3,and I can't find out where is wrong in my code.
When I was using Solver.add(),there was a  problem:
`Traceback (most recent call last):
  File "z3test.py", line 33, in <module>
    Solver.add(temp)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\z3\z3.py", line 6163, in add
    self.assert_exprs(*args)
AttributeError: 'BoolRef' object has no attribute 'assert_exprs'`
here is print result for temp:
`flag0*flag0 +
flag1*flag1 +
flag2*flag2 +
flag3*flag3 +
flag4*flag4 +
flag5*flag5 ==
73767`

**Comment by lwerdna** [comment]
@UnnameBao How did you resolve the issue?

I had the same error appear when following the tutorial at: https://ericpony.github.io/z3py-tutorial/guide-examples.htm

```
>>> x = Int('x')
>>> y = Int('y')
>>> s = Solver()
>>> s.add(x > 10, y == x + 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andrewl/.pyenv/versions/3.10.0/lib/python3.10/site-packages/z3/z3.py", line 6938, in add
    self.assert_exprs(*args)
AttributeError: 'BoolRef' object has no attribute 'assert_exprs'
```
