### ISSUE TITLE
z3.parse_smt2_string() in python API fails when string contains UTF-8 characters

### ISSUE THREAD

**Issue by delcypher** [Z3Prover/z3#1447]
From SMT-LIBv2.6 UTF-8 can be used in `.smt2` files. The python API `z3.parse_smt2_string()` fails to work on these files because it assumes the string it is provided with must be ascii.

Here's how to reproduce

Here's the contents of `test.py`

```python
#!/usr/bin/env python
import io
import logging
import sys
import z3

_logger = logging.getLogger(__name__)

def parse(query_file):
    assert isinstance(query_file, io.TextIOWrapper)
    # Load query_file as string
    query_str = ""
    for l in query_file.readlines():
        query_str += str(l)
    _logger.debug('query:\n{}'.format(query_str))
    try:
        constraint = z3.parse_smt2_string(query_str)
    except z3.z3types.Z3Exception as e:
        msg = 'Parsing failed: {}'.format(e)
        return (None, msg)
    return (constraint, None)

def main(args):
    logging.basicConfig(level=logging.DEBUG)
    file_name = args[0]
    with open(file_name, 'r') as f:
        contraint, msg = parse(f)
    return 0
        

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
```

now run it on 
[cos_polynomial_true-unreach-call.c_9.smt2.txt](https://github.com/Z3Prover/z3/files/1610446/cos_polynomial_true-unreach-call.c_9.smt2.txt)

```
$ ./test.py smtcomp/QF_FP/20170501-Heizmann-UltimateAutomizer/cos_polynomial_true-unreach-call.c_9.smt2



DEBUG:__main__:query:
(set-info :smt-lib-version 2.6)
(set-logic QF_FP)
(set-info :source |
Generated by the tool Ultimate Automizer [1,2] which implements 
an automata theoretic approach [3] to software verification.

This SMT script belongs to a set of SMT scripts that was generated by 
applying Ultimate Automizer to benchmarks [4] from the SV-COMP 2017 [5,6].

This script might _not_ contain all SMT commands that are used by 
Ultimate Automizer. In order to satisfy the restrictions of
the SMT-COMP we have to drop e.g., the commands for getting
values (resp. models), unsatisfiable cores and interpolants.

2017-05-01, Matthias Heizmann (heizmann@informatik.uni-freiburg.de)


[1] https://ultimate.informatik.uni-freiburg.de/automizer/
[2] Matthias Heizmann, Yu-Wen Chen, Daniel Dietsch, Marius Greitschus, 
Alexander Nutz, Betim Musa, Claus Schätzle, Christian Schilling, 
Frank Schüssele, Andreas Podelski:
Ultimate Automizer with an On-Demand Construction of Floyd-Hoare 
Automata - (Competition Contribution). TACAS (2) 2017: 394-398
[3] Matthias Heizmann, Jochen Hoenicke, Andreas Podelski: Software Model 
Checking for People Who Love Automata. CAV 2013:36-52
[4] https://github.com/sosy-lab/sv-benchmarks
[5] Dirk Beyer: Software Verification with Validation of Results - 
(Report on SV-COMP 2017). TACAS (2) 2017: 331-349
[6] https://sv-comp.sosy-lab.org/2017/
|)
(set-info :license "https://creativecommons.org/licenses/by/4.0/")
(set-info :category "industrial")
(set-info :status unknown)
(declare-fun v_mcos_~z~6_3_const_-1370124464 () (_ FloatingPoint 11 53))
(declare-fun v_~C6_2_const_-1185911185 () (_ FloatingPoint 11 53))
(declare-fun v_~C5_2_const_-1185912274 () (_ FloatingPoint 11 53))
(declare-fun v_~C4_2_const_-1185912339 () (_ FloatingPoint 11 53))
(declare-fun v_~C3_2_const_-1185913428 () (_ FloatingPoint 11 53))
(declare-fun v_~C2_2_const_-1185914525 () (_ FloatingPoint 11 53))
(declare-fun v_~C1_2_const_-1185899230 () (_ FloatingPoint 11 53))
(declare-fun v_mcos_~r~6_2_const_-1446751313 () (_ FloatingPoint 11 53))
(declare-fun v_mcos_~hz~6_4_const_-53211403 () (_ FloatingPoint 11 53))
(declare-fun v_mcos_~zr~6_3_const_-552628334 () (_ FloatingPoint 11 53))
(assert (let ((v_mcos_~z~6_3 v_mcos_~z~6_3_const_-1370124464) (v_~C6_2 v_~C6_2_const_-1185911185) (v_~C5_2 v_~C5_2_const_-1185912274) (v_~C4_2 v_~C4_2_const_-1185912339) (v_~C3_2 v_~C3_2_const_-1185913428) (v_~C2_2 v_~C2_2_const_-1185914525) (v_~C1_2 v_~C1_2_const_-1185899230) (v_mcos_~r~6_2 v_mcos_~r~6_2_const_-1446751313) (v_mcos_~hz~6_4 v_mcos_~hz~6_4_const_-53211403) (v_mcos_~zr~6_3 v_mcos_~zr~6_3_const_-552628334)) (and (= v_mcos_~hz~6_4 (fp.mul RNE ((_ to_fp 11 53) RNE 0.5) v_mcos_~z~6_3)) (= v_mcos_~r~6_2 (fp.mul RNE v_mcos_~z~6_3 (fp.add RNE v_~C1_2 (fp.mul RNE v_mcos_~z~6_3 (fp.add RNE v_~C2_2 (fp.mul RNE v_mcos_~z~6_3 (fp.add RNE v_~C3_2 (fp.mul RNE v_mcos_~z~6_3 (fp.add RNE v_~C4_2 (fp.mul RNE v_mcos_~z~6_3 (fp.add RNE v_~C5_2 (fp.mul RNE v_mcos_~z~6_3 v_~C6_2)))))))))))) (= v_mcos_~zr~6_3 (fp.mul RNE v_mcos_~z~6_3 v_mcos_~r~6_2)))))
(check-sat)
(exit)

Traceback (most recent call last):
  File "./z3_bug.py", line 32, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./z3_bug.py", line 27, in main
    contraint, msg = parse(f)
  File "./z3_bug.py", line 17, in parse
    constraint = z3.parse_smt2_string(query_str)
  File "/home/dan/dev/smt-coral-wrapper/z3/z3.py", line 8185, in parse_smt2_string
    return _to_expr_ref(Z3_parse_smtlib2_string(ctx.ref(), s, ssz, snames, ssorts, dsz, dnames, ddecls), ctx)
  File "/home/dan/dev/smt-coral-wrapper/z3/z3core.py", line 2981, in Z3_parse_smtlib2_string
    r = _elems.f(a0, _to_ascii(a1), a2, a3, a4, a5, a6, a7)
  File "/home/dan/dev/smt-coral-wrapper/z3/z3core.py", line 68, in _to_ascii
    return s.encode(encoding='ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 831: ordinal not in range(128)
```

I hacked around the problem in the `_to_ascii` function by changing it to

```python
def _to_ascii(s):
  if isinstance(s, str):
    return s.encode(encoding='utf-8')
  else:
    return s
```

This is only a hack though. Instead the Python API implementation needs to be changed to not assume that the string containing SMT-LIBv2 is ASCII.

**Comment by NikolajBjorner** [comment]
Fixed?

**Comment by delcypher** [comment]
@NikolajBjorner Yes this fixed the issue. Thanks.

**Comment by NikolajBjorner** [comment]
@wintersteiger - what is the status?

**Comment by wintersteiger** [comment]
I have no recollection of why I reopened this, but in general the utf/ascii patches have been flip-flopping. If you string-related tests work it's probably fine.
