### ISSUE TITLE
solver.toString() generates unordered and invalid SMT2 commands.

### ISSUE THREAD

**Issue by alcides** [Z3Prover/z3#1488]
When using solver.toString() in Java, the generated SMT2 commands are not valid.

The reason is that the order of datatype and sort definitions is invalid. In order to load the file back into z3, I have to manually reorder the first declarations.

I have put an exemple here: https://github.com/alcides/z3test and this is Problem 1.2 on the Readme.md

**Comment by alcides** [comment]
Actually, this issue remains.

The generated file in the Java Bindings does not have the correct order. I tested the commit that fixed this bug, as well as master. The repo I've linked before still shows the error.

**Comment by NikolajBjorner** [comment]
What is a simple self-contained repro?
My tests for the fix, which involves a topological sort of declarations, produces the right ordering.

[dt.py.txt](https://github.com/Z3Prover/z3/files/1746339/dt.py.txt)

**Comment by alcides** [comment]
Your example code does not run when imported from smt2
```python
from z3 import *

#sortA = DeclareSort('A')
#sortB = DeclareSort('B')

p1 = Datatype('P1')
p1.declare('p1', ('f', IntSort()))
p1 = p1.create()

p2 = Datatype('P2')
p2.declare('p2', ('f', p1))
p2 = p2.create()

p3 = Datatype('P3')
p3.declare('p3', ('f', p2))
p3 = p3.create()

p4 = Datatype('P4')
p4.declare('p4', ('f', p3))
p4 = p4.create()

x, y = Consts('x y',p4)
s = Solver()
s.add(x == y)
print(s.sexpr())
print(s.check())

print("before:")
print(s.to_smt2())

s2 = Solver()
s2.from_string(s.to_smt2())
print("after:")
print(s2.to_smt2())
```

It is unaware of all datatypes except for P3:

```
(declare-datatypes ((P4 0)) ((P4 (p4 (f P3)))))
(declare-fun y () P4)
(declare-fun x () P4)
(assert (= x y))

sat
before:
; benchmark generated from python API
(set-info :status unknown)
(declare-datatypes ((P4 0)) ((P4 (p4 (f P3)))))
 (declare-fun p4 (P3) P4)
(declare-fun f (P4) P3)
(declare-fun y () P4)
(declare-fun x () P4)
(assert
 (= x y))
(check-sat)

(error "line 3 column 19: invalid datatype declaration, unknown sort 'P3'")
(error "line 4 column 18: Parsing function declaration. Expecting sort list '(': unknown sort 'P3'")
(error "line 5 column 20: Invalid function declaration: unknown sort 'P3'")
Traceback (most recent call last):
  File "dt.py", line 32, in <module>
    s2.from_string(s.to_smt2())
  File "/usr/local/lib/python2.7/site-packages/z3/z3.py", line 6340, in from_string
    _handle_parse_error(e, self.ctx)        
  File "/usr/local/lib/python2.7/site-packages/z3/z3.py", line 8104, in _handle_parse_error
    raise ex
z3.z3types.Z3Exception: parser error
``
