### ISSUE TITLE
scripts/mk_make.py crashes if non-ascii characters are present in $(cc --version)

### ISSUE THREAD

**Issue by Armael** [Z3Prover/z3#1530]
When using a french locale, `gcc --version` gets localized into: 
```
gcc (GCC) 7.2.1 20180116
Copyright © 2017 Free Software Foundation, Inc.
Ce logiciel est un logiciel libre; voir les sources pour les conditions de copie.  Il n'y a
AUCUNE GARANTIE, pas même pour la COMMERCIALISATION ni L'ADÉQUATION À UNE TÂCHE PARTICULIÈRE.
```

which is apparently not handled properly by `scripts/mk_make.py`:

```
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/armael/.opam/4.04.2/.opam-switch/build/z3.4.6/scripts/mk_util.py", line 2619, in mk_makefile
    mk_config()
  File "/home/armael/.opam/4.04.2/.opam-switch/build/z3.4.6/scripts/mk_util.py", line 2482, in mk_config
    if is_CXX_clangpp():
  File "/home/armael/.opam/4.04.2/.opam-switch/build/z3.4.6/scripts/mk_util.py", line 897, in is_CXX_clangpp
    return is_clang_in_gpp_form(CXX)
  File "/home/armael/.opam/4.04.2/.opam-switch/build/z3.4.6/scripts/mk_util.py", line 892, in is_clang_in_gpp_form
    version_string = check_output([cc, '--version']).encode('utf-8').decode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 35: ordinal not in range(128)
```

**Comment by NikolajBjorner** [comment]
Try if 0ce200144923fe5856054bcad11c9f5471f0d791 helps you

**Comment by Armael** [comment]
It seems to have fixed the issue, thanks! (although I'm getting the following error at a later stage, but I assume it is unrelated)

```
File "../src/api/ml/z3.ml", line 1405, characters 103-124:
Error: This variant expression is expected to have type Z3enums.decl_kind
       The constructor OP_PR_PULL_QUANT_STAR does not belong to type Z3enums.decl_kind
```
