### ISSUE TITLE
oserror: exception: access violation writing 0x0000000000000008

### ISSUE THREAD

**Issue by szhong12** [Z3Prover/z3#1578]
**An error occurred after running example.py:**
 x = Real('x')
  File "D:\chrome\downloads\z3-master\build\python\z3\z3.py", line 2920, in Real
    ctx = _get_ctx(ctx)
  File "D:\chrome\downloads\z3-master\build\python\z3\z3.py", line 225, in _get_ctx
    return main_ctx()
  File "D:\chrome\downloads\z3-master\build\python\z3\z3.py", line 220, in main_ctx
    _main_ctx = Context()
  File "D:\chrome\downloads\z3-master\build\python\z3\z3.py", line 178, in __init__
    self.ctx = Z3_mk_context_rc(conf)
  File "D:\chrome\downloads\z3-master\build\python\z3\z3core.py", line 1369, in Z3_mk_context_rc
    r = _elems.f(a0)
OSError: exception: access violation writing 0x0000000000000008
Exception ignored in: <bound method Context.__del__ of <z3.z3.Context object at 0x000000000221A048>>
Traceback (most recent call last):
  File "D:\chrome\downloads\z3-master\build\python\z3\z3.py", line 184, in __del__
    Z3_del_context(self.ctx)        
AttributeError: 'Context' object has no attribute 'ctx'

**Comment by Lizenan1995** [comment]
Is now the problem solved? I encountered the same problem, then I deleted and reinstalled z3. It doesn't appear any more. I gauss it was due to my mistaken installation previously.

**Comment by NikolajBjorner** [comment]
Corrupt installation issue

**Comment by Tridu33** [comment]
> Is now the problem solved? I encountered the same problem, then I deleted and reinstalled z3. It doesn't appear any more. I gauss it was due to my mistaken installation previously.

me too. reinstall z3 can not help me for this problem.
it runs well sometime but sometime it just crashes saying "oserror: exception: access violation writing".

**Comment by Tridu33** [comment]
then i try it in windows wsl ubuntu, it runs well sometime but sometime it just crashes saying"Segmentation fault (core dumped)"

**Comment by Tridu33** [comment]
but I do not know why the same source code just works well sometimes.
