### ISSUE TITLE
python build (mk_util) failing

### ISSUE THREAD

**Issue by bannsec** [Z3Prover/z3#1584]
Just tried updating to master branch and am getting the following build error:

```
Host platform:  Linux
C++ Compiler:   g++
C Compiler  :   gcc
Archive Tool:   ar
Arithmetic:     internal
OpenMP:         True
Prefix:         /home/pySym/.virtualenvs/pySym
64-bit:         True
FP math:        SSE2-GCC
Python pkg dir: /home/pySym/.virtualenvs/pySym/lib/python3.6/site-packages
Python version: 3.6
Writing build/Makefile
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/pySym/pySym/lib/z3/scripts/mk_util.py", line 2667, in mk_makefile
    c.mk_makefile(out)
  File "/home/pySym/pySym/lib/z3/scripts/mk_util.py", line 1103, in mk_makefile
    Component.mk_makefile(self, out)
  File "/home/pySym/pySym/lib/z3/scripts/mk_util.py", line 1050, in mk_makefile
    self.add_cpp_rules(out, include_defs, cppfile)
  File "/home/pySym/pySym/lib/z3/scripts/mk_util.py", line 1007, in add_cpp_rules
    self.add_rule_for_each_include(out, cppfile)
  File "/home/pySym/pySym/lib/z3/scripts/mk_util.py", line 984, in add_rule_for_each_include
    includes = extract_c_includes(fullname)
  File "/home/pySym/pySym/lib/z3/scripts/mk_util.py", line 785, in extract_c_includes
    for line in f:
  File "/home/pySym/.virtualenvs/pySym/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2407: ordinal not in range(128)
The command '/bin/sh -c mkdir /home/pySym/.virtualenvs &&     sudo chown -R pySym:pySym /home/pySym/. &&     python3 -m virtualenv --python=$(which python3) ~/.virtualenvs/pySym &&     echo ". ~/.virtualenvs/pySym/bin/activate" >> ~/.bashrc &&     . ~/.virtualenvs/pySym/bin/activate && cd pySym && PYSYM_NO_Z3=True pip install -e .[dev] &&     cd lib/z3 && python scripts/mk_make.py --python &&     cd build && make -j$(nproc) && make install' returned a non-zero code: 1
The command "docker build -t bannsec/pysym ." failed and exited with 1 during .
```

**Comment by NikolajBjorner** [comment]
So I planted a Unicode character easteregg in some file?

**Comment by bannsec** [comment]
Looks like it! I haven't had a chance yet to dig into where exactly it is, unfortunately.

**Comment by NikolajBjorner** [comment]
Suggestion: instrument the python file to print file name and line. I don't seem to be able to reproduce this locally so one possibility is a file corruption.
