### ISSUE TITLE
ImportError: No module named config

### ISSUE THREAD

**Issue by Youlor** [Z3Prover/z3#1657]
My Enviroment: Windows 10

When I use a script, I get this error:
    from z3.config import get_config
    ImportError: No module named config

But when I use python on cmd, "from z3.config import get_config" is fine. How can I solve this problem?
Thanks!

**Comment by Youlor** [comment]
Log:
Traceback (most recent call last):
  File "C:\python27-x64\Scripts\z3-script.py", line 11, in <module>
  File "C:\python27-x64\Scripts\z3-script.py", line 11, in <module>
    load_entry_point('z3==0.2.0', 'console_scripts', 'z3')()
      File "c:\python27-x64\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
load_entry_point('z3==0.2.0', 'console_scripts', 'z3')()
  File "c:\python27-x64\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27-x64\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27-x64\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
        return ep.load()
return ep.load()
  File "c:\python27-x64\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
  File "c:\python27-x64\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
      File "c:\python27-x64\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
return self.resolve()
  File "c:\python27-x64\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27-x64\lib\site-packages\z3\snap.py", line 14, in <module>
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
from z3.config import get_config
  File "c:\python27-x64\lib\site-packages\z3\snap.py", line 14, in <module>
ImportError: No module named configfrom z3.config import get_config

**Comment by NikolajBjorner** [comment]
It seems there is some package manager that includes Z3. I am not sure where this is. 
Could you help locate the git repo where this is defined and file an issue there (and add a link to this issue and I can update links from here to there for easier discoverability).

**Comment by NikolajBjorner** [comment]
Not sure how this is actionable in context of Z3. Seems to be an external issue.
