### ISSUE TITLE
UnsatisfiedLinkError in Z3 JavaExample (Windows10)

### ISSUE THREAD

**Issue by NicStarzi** [Z3Prover/z3#1885]
I am trying to run the JavaExample from github (Link: https://github.com/Z3Prover/z3/tree/master/examples/java) and I get an UnsatisfiedLinkError: Can't find dependent libraries.

I have downloaded the latest version (z3-4.8.1.016872a5e0f6-x64-win.zip) from https://github.com/Z3Prover/z3/releases. I have added the bin directory to my PATH variable. I can use "where libz3.dll" and "where libz3java.dll" and I get the correct output:

C:\Users\ds>where libz3java.dll
C:\Users\ds\Desktop\z3-4.8.1.016872a5e0f6-x64-win\bin\libz3java.dll

---------------------------------------------

Compiling the JavaExample with the provided jar works fine. When I try to run the example using:

java -cp "z3.jar;." JavaExample

I get the following error:
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\ds\Desktop\z3-4.8.1.016872a5e0f6-x64-win\bin\libz3java.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2649)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
        at java.base/java.lang.System.loadLibrary(System.java:1867)
        at com.microsoft.z3.Native.<clinit>(Native.java:14)
        at com.microsoft.z3.Global.ToggleWarningMessages(Global.java:87)
        at JEx.main(JEx.java:2267)

---------------------------------------------

I get the same error when I put the compiled class files and the jar into the same directory as the binaries and use:

java "-Djava.library.path=." -cp "z3.jar;." JavaExample

Maybe there is some step I have forgotten to do?
Help is greatly appreciated.

**Comment by NicStarzi** [comment]
I have got it to work now after installing microsoft visual studio. I am not certain, that this is the reason why the problem went away but it is pretty much the only thing I did that should be relevant to the fix. Can somebody confirm if this is indeed necessary to use Z3 with Java?

**Comment by wintersteiger** [comment]
No, Visual Studio is only necessary to _build_ Z3 for Windows, not to use pre-built binaries with Java.

One of the usual problems is a mismatch between 32-bit and 64-bit binaries/libraries. Java 64-bit can only load 64-bit libraries and some flavours of Java will throw an UnsatisfiedLinkError without further information. 

Depending on the OS and the flavour of Java, the path to the .dll also needs to be in `PATH`, `LD_LIBRARY_PATH`, or `DYLD_LIBRARY_PATH` and `java.library.path`.
