### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by abarbaro** [Z3Prover/z3#1925]
Hi all,
I'm experimenting with KLEE and I would like to compile z3 on the same container. Unfortunately I have the following error

```
Traceback (most recent call last):
  File "scripts/mk_make.py", line 17, in <module>
    mk_auto_src()
  File "/home/klee/z3/scripts/mk_util.py", line 2909, in mk_auto_src
    mk_all_install_tactic_cpps()
  File "/home/klee/z3/scripts/mk_util.py", line 3028, in mk_all_install_tactic_cpps
    mk_install_tactic_cpp(cnames, c.src_dir)
  File "/home/klee/z3/scripts/mk_util.py", line 3017, in mk_install_tactic_cpp
    generated_file = mk_genfile_common.mk_install_tactic_cpp_internal(h_files_full_path, path)
  File "/home/klee/z3/scripts/mk_genfile_common.py", line 699, in mk_install_tactic_cpp_internal
    for line in fin:
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1809: ordinal not in range(128)
```

I'm using python 3.4.3

Thanks

**Comment by NikolajBjorner** [comment]
try the cmake based build system README-cmake.md.

**Comment by NikolajBjorner** [comment]
Did this reveal the offending character?

**Comment by NikolajBjorner** [comment]
I use python 3.6 and have since this was opened run the build scripts on several platforms without encountering errors. I have to presume you have a corrupted file.
