### ISSUE TITLE
Installation issues on Windows

### ISSUE THREAD

**Issue by Jayzh7** [Z3Prover/z3#1943]
Hi there,

I was trying to install z3 and found it a bit more challenging than expected.

Firstly, I followed https://github.com/Z3Prover/z3/wiki/Using-Z3Py-on-Windows. I downloaded the binaries , added those sub-directories to environment variables, then I try to execute 'from z3 import *' in python and failed with 

```
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "D:\Z3Py\z3-4.6.0-x64-win\bin\python\z3\z3.py", line 44, in <module>
     from . import z3core
 ImportError: attempted relative import with no known parent package

```

Second, I tried to execute 'pip install z3-solver'. But an error occured
```
Collecting z3-solver
  Using cached https://files.pythonhosted.org/packages/83/7e/9e3b84ed773945cfa3c00e64c3ef49c492bf4b6f60cf6223b8756053e7f4/z3-solver-4.8.0.0.post1.tar.gz
Installing collected packages: z3-solver
  Running setup.py install for z3-solver ... error
    Complete output from command d:\python3.7\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Jayzh\\AppData\\Local\\Temp\\pip-install-zb_18o7w\\z3-solver\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Jayzh\AppData\Local\Temp\pip-record-zovevlux\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Configuring Z3
    opt = -x, arg =
    ...
    Listing 'src\\api\\python\\z3'...
    Compiling 'src\\api\\python\\z3\\z3consts.py'...
    Compiling 'src\\api\\python\\z3\\z3core.py'...
    Generated python bytecode
    Copied 'z3consts.py'
    Copied 'z3core.py'
    Copied 'z3consts.cpython-37.pyc'
    Copied 'z3core.cpython-37.pyc'
    Testing OpenMP...
    64-bit:         True
    OpenMP:         False
    Writing build\Makefile
    Copied Z3Py example 'all_interval_series.py' to 'build\python'
    Copied Z3Py example 'example.py' to 'build\python'
    Copied Z3Py example 'parallel.py' to 'build\python'
    Copied Z3Py example 'socrates.py' to 'build\python'
    Copied Z3Py example 'visitor.py' to 'build\python'
    Makefile was successfully generated.
      compilation mode: Release
      platform: x64

    To build Z3, open a [Visual Studio x64 Command Prompt], then
    type 'cd C:\Users\Jayzh\AppData\Local\Temp\pip-install-zb_18o7w\z3-solver\core\build && nmake'

    Remark: to open a Visual Studio Command Prompt, go to: "Start > All Programs > Visual Studio > Visual Studio Tools"
    Building Z3
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "d:\python3.7\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Jayzh\\AppData\\Local\\Temp\\pip-install-zb_18o7w\\z3-solver\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Jayzh\AppData\Local\Temp\pip-record-zovevlux\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Jayzh\AppData\Local\Temp\pip-install-zb_18o7w\z3-solver\

```
Does this mean that I need to install Visual Studio?

Thanks for the help!

**Comment by LeventErkok** [comment]
Also related: https://github.com/Z3Prover/bin/tree/master/nightly no longer has a windows release listed.

**Comment by NikolajBjorner** [comment]
- If you build z3 using scripts/mk_make.py, then there is a python subdirectory with examples. You can run those examples.

- The web site https://pypi.org/project/z3-solver/ tells to submit issues to a different GitHub project. I don't have first-hand support for pip. Perhaps a valid thing to support, but requires bandwidth. Currently, the bandwidth is spent on ensuring we get nuget packages for the .net standard.

- windows builds will reappear when the mk_win_dist.py scripts work again. I broke them the past few days.
