### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 1811: illegal  multibyte sequence

### ISSUE THREAD

**Issue by chuzhifeng** [Z3Prover/z3#1959]
Hi, I would like to compile z3 on the windows.Unfortunately,I have the following error,how to solve it ,thanks

Traceback (most recent call last):
  File "D:\DevelopSoftware\z3-master\scripts\mk_genfile_common.py", line 700, in
 mk_install_tactic_cpp_internal
    for line in fin:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 1811: illegal
 multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/mk_make.py", line 17, in <module>
    mk_auto_src()
  File "D:\DevelopSoftware\z3-master\scripts\mk_util.py", line 2936, in mk_auto_
src
    mk_all_install_tactic_cpps()
  File "D:\DevelopSoftware\z3-master\scripts\mk_util.py", line 3055, in mk_all_i
nstall_tactic_cpps
    mk_install_tactic_cpp(cnames, c.src_dir)
  File "D:\DevelopSoftware\z3-master\scripts\mk_util.py", line 3044, in mk_insta
ll_tactic_cpp
    generated_file = mk_genfile_common.mk_install_tactic_cpp_internal(h_files_fu
ll_path, path)
  File "D:\DevelopSoftware\z3-master\scripts\mk_genfile_common.py", line 721, in
 mk_install_tactic_cpp_internal
    except e:
UnboundLocalError: local variable 'e' referenced before assignment

**Comment by NikolajBjorner** [comment]
can you try again with the latest update to mk_genfile_common.py?
It should print out which file contains an illegal character. This does not happen on my side, so there could be something with locales.

**Comment by NikolajBjorner** [comment]
right, this is the second report we get on an exception in this part of the build generation, but I haven't seen the culprit file that would contain the non-ascii character. we had those in the past, for sure, but they were easy to detect because the build scripts would pick them up.

**Comment by waywardmonkeys** [comment]
I have an idea for how to debug this ... once I am back home later today.
