### ISSUE TITLE
Python3 build for version 4.8.4 fails: codec can't decode byte 0xe2 in position 1809

### ISSUE THREAD

**Issue by yurivict** [Z3Prover/z3#2131]
```
Component shell
Failed to read file src/ast/recfun_decl_plugin.h

Traceback (most recent call last):
  File "/wrkdirs/usr/ports/math/py-z3-solver/work-py36/z3-z3-4.8.4/src/api/python/../../../scripts/mk_make.py", line 17, in <module>
    mk_auto_src()
  File "/wrkdirs/usr/ports/math/py-z3-solver/work-py36/z3-z3-4.8.4/scripts/mk_util.py", line 3017, in mk_auto_src
    mk_all_install_tactic_cpps()
  File "/wrkdirs/usr/ports/math/py-z3-solver/work-py36/z3-z3-4.8.4/scripts/mk_util.py", line 3136, in mk_all_install_tactic_cpps
    mk_install_tactic_cpp(cnames, c.src_dir)
  File "/wrkdirs/usr/ports/math/py-z3-solver/work-py36/z3-z3-4.8.4/scripts/mk_util.py", line 3125, in mk_install_tactic_cpp
    generated_file = mk_genfile_common.mk_install_tactic_cpp_internal(h_files_full_path, path)
  File "/wrkdirs/usr/ports/math/py-z3-solver/work-py36/z3-z3-4.8.4/scripts/mk_genfile_common.py", line 723, in mk_install_tactic_cpp_internal
    raise e
  File "/wrkdirs/usr/ports/math/py-z3-solver/work-py36/z3-z3-4.8.4/scripts/mk_genfile_common.py", line 700, in mk_install_tactic_cpp_internal
    for line in fin: 
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1809: ordinal not in range(128)
error: Unable to configure Z3.
```

**Comment by yurivict** [comment]
Adding ellipsis into the comment in that file (```f(t1…tn) = rhs```) isn't a good idea. Now you have to fix the python code that fails to parse it.
