### ISSUE TITLE
AttributeError: module 'z3' has no attribute 'lib'

### ISSUE THREAD

**Issue by nikhilh-20** [Z3Prover/z3#2274]
I was going through the [constraint solving docs](https://docs.angr.io/core-concepts/solver#constraint-solving) of `angr` which uses `z3` internally and I'm hitting this error: `AttributeError: module 'z3' has no attribute 'lib'`

```
...
Traceback (most recent call last):
  File "solver.py", line 68, in <module>
    print(state.solver.eval(x))
  File "/usr/local/lib/python3.6/dist-packages/angr/state_plugins/solver.py", line 724, in eval
    return self.eval_upto(e, 1, **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/angr/state_plugins/solver.py", line 707, in eval_upto
    cast_vals = [self._cast_to(e, v, cast_to) for v in self._eval(e, n, **kwargs)]
  File "/usr/local/lib/python3.6/dist-packages/angr/state_plugins/solver.py", line 154, in concrete_shortcut_tuple
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/angr/state_plugins/sim_action_object.py", line 57, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/angr/state_plugins/solver.py", line 87, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/angr/state_plugins/solver.py", line 499, in _eval
    return self._solver.eval(e, n, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontend_mixins/concrete_handler_mixin.py", line 7, in eval
    return super(ConcreteHandlerMixin, self).eval(e, n, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 40, in eval
    return super(ConstraintFilterMixin, self).eval(e, n, extra_constraints=ec, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontend_mixins/sat_cache_mixin.py", line 56, in eval
    extra_constraints=extra_constraints, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontend_mixins/simplify_helper_mixin.py", line 13, in eval
    return super(SimplifyHelperMixin, self).eval(e, n, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontend_mixins/constraint_expansion_mixin.py", line 12, in eval
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontends/composite_frontend.py", line 317, in eval
    self._ensure_sat(extra_constraints=extra_constraints)
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontends/composite_frontend.py", line 266, in _ensure_sat
    if self._unsat or (len(extra_constraints) == 0 and not self.satisfiable()):
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 34, in satisfiable
    return super(ConstraintFilterMixin, self).satisfiable(extra_constraints=ec, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontend_mixins/sat_cache_mixin.py", line 45, in satisfiable
    extra_constraints=extra_constraints, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontends/composite_frontend.py", line 314, in satisfiable
    return all(s.satisfiable(exact=exact) for s in self._solver_list)
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontends/composite_frontend.py", line 314, in <genexpr>
    return all(s.satisfiable(exact=exact) for s in self._solver_list)
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontend_mixins/sat_cache_mixin.py", line 45, in satisfiable
    extra_constraints=extra_constraints, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontend_mixins/model_cache_mixin.py", line 240, in satisfiable
    return super(ModelCacheMixin, self).satisfiable(extra_constraints=extra_constraints, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/claripy/frontends/full_frontend.py", line 102, in satisfiable
    solver=self._get_solver(), model_callback=self._model_hook
  File "/usr/local/lib/python3.6/dist-packages/claripy/backends/__init__.py", line 639, in satisfiable
    return self._satisfiable(extra_constraints=self.convert_list(extra_constraints), solver=solver, model_callback=model_callback)
  File "/usr/local/lib/python3.6/dist-packages/claripy/backends/backend_z3.py", line 679, in _satisfiable
    model_callback(self._generic_model(solver.model()))
  File "/usr/local/lib/python3.6/dist-packages/claripy/backends/backend_z3.py", line 656, in _generic_model
    n = _z3_decl_name_str(m_f.ctx.ctx, m_f.ast).decode()
  File "/usr/local/lib/python3.6/dist-packages/claripy/backends/backend_z3.py", line 73, in _z3_decl_name_str
    lib = z3.lib()
AttributeError: module 'z3' has no attribute 'lib'
```

It seems like `z3` has a potential issue.
```
nikhilh@ubuntu:~/angr$ cat check.py 
#!/usr/bin/python3

import z3
a = z3.lib()
```
Error:
```
nikhilh@ubuntu:~/angr$ python3 check.py 
Traceback (most recent call last):
  File "check.py", line 4, in <module>
    a = z3.lib()
AttributeError: module 'z3' has no attribute 'lib'
```

Here's some information on my system and installed `z3`:
```
nikhilh@ubuntu:~/angr$ z3 -h
Z3 [version 4.8.5 - 64 bit]. (C) Copyright 2006-2016 Microsoft Corp.
Usage: z3 [options] [-file:]file
...
...
```
```
nikhilh@ubuntu:~/angr$ python3 -V
Python 3.6.7

nikhilh@ubuntu:~/angr$ uname -a
Linux ubuntu 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Is the above problem expected? Have I made a mistake in `z3` installation?

**Comment by nikhilh-20** [comment]
I made a mistake with `angr` installation. This issue can be closed. Thanks!

**Comment by strawberrylady99** [comment]
may I know how you get question solved

**Comment by nikhilh-20** [comment]
Unfortunately, I no longer remember but I guess I must have reinstalled `angr` correctly.
