### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by geraw** [Z3Prover/z3#2277]
The code:

```python
from z3 import *

x0, x1, y0, y1, p = Reals('x1 x0 y0 y1 p')

sl = Optimize()

sl.add(
    Or(And(x0 + x1 == 2, y0 + y1 == 2, p == 2),
       And(x0 + x1 == 3, y0 + y1 == 3, p == 3)))

sl.maximize(p)
sl.check()
```

Crashes Z3:

```
Traceback (most recent call last):
  File "bug.py", line 12, in <module>
    sl.check()
  File "z3.py", line 7252, in check
    return CheckSatResult(Z3_optimize_check(self.ctx.ref(), self.optimize))
  File "z3core.py", line 3993, in Z3_optimize_check
    r = _elems.f(a0, a1)
OSError: exception: access violation reading 0x0000018851C3F6DC
```

**Comment by Tridu33** [comment]
NikolajBjorner in this url https://github.com/Z3Prover/z3/issues/1578 says "Corrupt installation issue". but reinstall z3 cannot fix this problem.
