### ISSUE TITLE
Model not available exception s.check() is returning 'sat'

### ISSUE THREAD

**Issue by Ipsitakoley** [Z3Prover/z3#2461]
I am using z3py.
s.check() is returning 'sat' however it is giving the following exception

Traceback (most recent call last):
  File "understeerSlow.py", line 3788, in <module>
    m = s.model()
  File "/usr/lib/python2.7/dist-packages/z3.py", line 5989, in model
    raise Z3Exception("model is not available")
z3types.Z3Exception: model is not available

**Comment by NikolajBjorner** [comment]
It is not possible to address this issue without a repro
