### ISSUE TITLE
Timeout and segmentation fault

### ISSUE THREAD

**Issue by 1one-w01f** [Z3Prover/z3#2534]
Hi,

I noticed that Z3 seems to be occasionally crashing when timeout is in place. The Z3 I'm using is a built of commit 2f60bcbfcbff5245d2780ab33e4b67468c7068f9.

For example, Z3 would sometimes run into a segmentation fault when given the following input (taken from the [AppScan benchmark from Z3str3](https://sites.google.com/site/z3strsolver/benchmarks)) with a 1 second timeout on my machine.
```
(set-logic QF_S)
(set-option :produce-models true)
(set-info :status sat)

(declare-fun cookie () String)
(declare-fun cookie_part1 () String)
(declare-fun cookie_part2 () String)
(declare-fun cookie_part3 () String)
(declare-fun lang () String)
(declare-fun idx1 () Int)
(declare-fun len1 () Int)
(declare-fun l1 () String)



(assert (= cookie  (str.++ cookie_part1 cookie_part2 cookie_part3) ) ) 

(assert (str.in.re cookie_part2 (re.++ (re.union (str.to.re "?") (str.to.re ";") ) 
                                       (str.to.re "searchLang=")
                                       (re.* (re.union (str.to.re "a") (str.to.re "b") (str.to.re "c") (str.to.re "d") (str.to.re "e") (str.to.re "f") (str.to.re "g") (str.to.re "h") (str.to.re "i") (str.to.re "j") (str.to.re "k") (str.to.re "l") (str.to.re "m") (str.to.re "n") ) )
                                )
        )
)

(assert (=> (not (= "" cookie_part3) ) (= cookie_part3 (str.++ ";" l1) ) ) )

(assert (> (str.len cookie_part2) 11) )

(assert (= cookie "expires=Thu, 18 Dec 2013 12:00:00 UTC;searchLang=nb;domain=local;") )

(assert (= idx1 (+ (str.indexof  cookie_part2  "="  0) 1 ) ) )

(assert (= len1 (str.len cookie_part2) ) )

(assert (> idx1 0) )

(assert (> len1 idx1))

(assert (= lang (str.substr cookie_part2 idx1 (- len1 idx1) ) ) )


(check-sat)
```

Z3 doesn't always crash on that input; so I had to iterate it a lot of times in bash to see a segmentation fault:
```bash
for n in {1..500}; do cat ./test.smt2 | z3 -smt2 -in -T:1; done
```

And if it'd help, here is the output of doing a backtrace over the core dump with `gdb`:
```
(gdb) bt
#0  _int_malloc (av=av@entry=0x7ff819144b20 <main_arena>, bytes=bytes@entry=48) at malloc.c:3516
#1  0x00007ff818e04184 in __GI___libc_malloc (bytes=48) at malloc.c:2913
#2  0x00000000014d240a in memory::allocate(unsigned long) ()
#3  0x000000000057b07b in old_vector<ref_vector<expr, ast_manager>, true, unsigned int>::expand_vector() ()
#4  0x000000000057b2e0 in old_vector<ref_vector<expr, ast_manager>, true, unsigned int>::push_back(ref_vector<expr, ast_manager> const&)
    ()
#5  0x0000000000af6e75 in smt::theory_seq::new_diseq_eh(int, int) ()
#6  0x0000000000949177 in smt::context::propagate_th_diseqs() ()
#7  0x0000000000956bcb in smt::context::propagate() ()
#8  0x00000000009597f7 in smt::context::bounded_search() ()
#9  0x0000000000959b88 in smt::context::search() ()
#10 0x000000000095abec in smt::context::check(unsigned int, expr* const*, bool) ()
#11 0x000000000095ae8f in smt::context::setup_and_check(bool) ()
#12 0x00000000008fd9d4 in smt_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ()
#13 0x0000000000fc4efb in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ()
#14 0x0000000000fc4efb in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ()
#15 0x0000000000fbbec4 in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&) ()
#16 0x0000000000fbc49a in check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
#17 0x0000000000f5daa2 in (anonymous namespace)::tactic2solver::check_sat_core2(unsigned int, expr* const*) ()
#18 0x0000000000f35602 in solver_na2as::check_sat_core(unsigned int, expr* const*) ()
#19 0x0000000000f483df in combined_solver::check_sat_core(unsigned int, expr* const*) ()
#20 0x0000000000f5929c in solver::check_sat(unsigned int, expr* const*) ()
#21 0x0000000000f063a0 in cmd_context::check_sat(unsigned int, expr* const*) ()
#22 0x0000000000edfd8a in smt2::parser::parse_cmd() ()
#23 0x0000000000edfff8 in smt2::parser::operator()() ()
#24 0x0000000000ecb2e0 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) ()
#25 0x00000000004369d8 in read_smtlib2_commands(char const*) ()
#26 0x000000000041cb00 in main ()
```

Interestingly, if I iterate it 500 times without the timeout, Z3 doesn't seem to crash, and would output "sat":
```bash
for n in {1..500}; do cat ./test.smt2 | z3 -smt2 -in; done
```

So I'm guessing the problem perhaps lies in some of the clean-up routines being invoked after timeout?

**Comment by nunoplopes** [comment]
Could you compile Z3 in debug mode and send us a stack trace again pls?

**Comment by nunoplopes** [comment]
Also, using latest master, since we've done some fixes in the meantime. Thanks!

**Comment by 1one-w01f** [comment]
Looks like the latest master no longer crashes when timeout on the given output. Thanks!
