### ISSUE TITLE
A z3 question with python API

### ISSUE THREAD

**Issue by sdasgup3** [Z3Prover/z3#2669]
I was trying to encode the following smtlib query
```
(declare-const x Int)
(declare-const cf Int)
(declare-const cf2 Int)

(assert (not (=
    (= cf2 (ite (> x 0) 1 (ite (< x 0) -1 0)))
    (and
        (=> (> x 0) (= cf2  1))
        (=> (= x 0) (= cf2  0))
        (=> (< x 0) (= cf2 -1))
    )
)))
(check-sat)
```
using python APIs and follwoing code seems to do the job. However,  if I comment out the `remove the comment` line and comment-in the above line instead, then I get errors (pased after the code). Can somebody help me understand why  `z3.If(x1 > 0, cf == 1, z3.If(x1 < 0, cf == -1, cf == 0))` and `(cf == z3.If(x1 > 0, 1, z3.If(x1 < 0, -1, 0))) ` are differnet?

```
x1 = z3.Ints('x1')
x2 = z3.Ints('x2')
cf = z3.Ints('cf')

s = z3.Solver()
s.add(x1 == x2)

var1 = z3.If(x1 > 0, cf == 1, z3.If(x1 < 0, cf == -1, cf == 0))  # <--- comment this instead
#var1 = (cf == z3.If(x1 > 0, 1, z3.If(x1 < 0, -1, 0)))                 # <---- remove the comment

var2 = z3.And(
      z3.Implies(x2 > 0, cf == 1),
      z3.Implies(x2 == 0, cf == 0),
      z3.Implies(x2 < 0, cf == -1)
    )

s.add(var1 != var2)
print(s.check());
```

Error:
```
Traceback (most recent call last):
  File "/home/sdasgup3/Github/validating-binary-decompilation/docs/z3_artifcats/sideConds.py", line 34, in <module>
    var1 = (cf == var11)
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 850, in __eq__
    a, b = _coerce_exprs(self, other)
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 1018, in _coerce_exprs
    b = s.cast(b)
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 2021, in cast
    return IntVal(val, self.ctx)
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 2808, in IntVal
    return IntNumRef(Z3_mk_numeral(ctx.ref(), _to_int_str(val), IntSort(ctx).ast), ctx)
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 2797, in _to_int_str
    _z3_assert(False, "Python value cannot be used as a Z3 integer")
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 91, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: Python value cannot be used as a Z3 integer
```

**Comment by NikolajBjorner** [comment]
python does some type overloading.
It may interpret 0 as BoolVal(False) and 1 as BoolVar(True). 
To avoid type disambiguation issues use IntVal (and BoolVal) as appropriate.

**Comment by sdasgup3** [comment]
@NikolajBjorner **Thanks for your kind help.**

I tried the folloing experiments, but still getting similar error (I pasted it as the after the follwoing code). Do you mind skimming through the following code changes. 
```
x1 = z3.Ints('x1')
x2 = z3.Ints('x2')
cf = z3.Ints('cf')

s = z3.Solver()
s.add(x1 == x2)

var1 = (cf ==  z3.If(x1 > 0, z3.IntVal(4), z3.IntVal(5)))  # <-- does not work
#var1 = (cf ==  z3.If(x1 > 0, 4, 5))                        # <-- does not work
#var1 = z3.If(x1 > 0, cf == 4, cf == 5)                      # <-- this works

var2 = z3.And(
      z3.Implies(x2 > 0,  cf == 4),  # <-- Also I tried adding InVal(4) here, but z3 py complains about the line with var1 
      z3.Implies(x2 <= 0, cf == 5)
    )

s.add(var1 != var2)
print(s.check());
```

Error
```
Traceback (most recent call last):
  File "/home/sdasgup3/Github/validating-binary-decompilation/docs/z3_artifcats/sideConds.py", line 29, in <module>
    var1 = (cf ==  z3.If(x1 > 0, z3.IntVal(4), z3.IntVal(5)))  # <-- does not work
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 850, in __eq__
    a, b = _coerce_exprs(self, other)
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 1018, in _coerce_exprs
    b = s.cast(b)
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 2021, in cast
    return IntVal(val, self.ctx)
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 2808, in IntVal
    return IntNumRef(Z3_mk_numeral(ctx.ref(), _to_int_str(val), IntSort(ctx).ast), ctx)
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 2797, in _to_int_str
    _z3_assert(False, "Python value cannot be used as a Z3 integer")
  File "/home/sdasgup3/.local/lib/python2.7/site-packages/z3/z3.py", line 91, in _z3_assert
    raise Z3Exception(msg)
z3.z3types.Z3Exception: Python value cannot be used as a Z3 integer
```

**Comment by wintersteiger** [comment]
`cf = z3.Ints('cf')` produces a _list_ of integers, not a single one. The "Python value" that Python complains about is this list and it is right in that the list can't be converted to a Z3 integer. For single variables, use `z3.Int('cf')` (no `s`), or alternatively let Python know that you want to convert the list into a tuple of size 1, by adding a comma: `cf, = z3.Ints('cf')`.

**Comment by sdasgup3** [comment]
@wintersteiger Thanks a lot for the help. That works.
