### ISSUE TITLE
Coping SolverFor 

### ISSUE THREAD

**Issue by gmCAD** [Z3Prover/z3#2805]
Assertions do not copy if the z3 solver is created using SolverFor().  

```python 
>>> from z3 import *
>>> x, y = Bools('x y')
>>> s = SolverFor('QF_FD')
>>> s.add( And(x,y) )
>>> copySolver = copy.copy(s) #deepcopy doesn't work either
>>> s.assertions()
['y', 'x']  # The printing of QF_FD Solver assertions looks weird, shouldn't it be [And(x, y)]?
>>> copySolver.assertions()
[]
```

This test case was created using Python 3.6, Z3 4.8.8.0, and Windows 10.

**Comment by gmCAD** [comment]
I have also noticed that when coping the solver that the OS will throw an exception saying "access violation reading".

Here is the trackback.  Any idea why coping the Solver would cause an exception like this?  

```python
2019-12-16 17:24:01,831 - __main__ - ERROR: exception: access violation reading 0x0000026CA99DD698
Traceback (most recent call last):
  File "__main__.py", line 275, in main
  File "__main__.py", line 142, in MTGeneration
  File "modeTable.py", line 31, in __init__
  File "timeFunc.py", line 9, in timed
  File ".py", line 94, in evaLMT
  File ".py", line 65, in SolverReset
  File ".py", line 63, in SolverReset
  File "copy.py", line 161, in deepcopy
  File "z3\z3.py", line 6878, in __deepcopy__
  File "z3\z3.py", line 6871, in translate
  File "z3\z3core.py", line 3637, in Z3_solver_translate
OSError: exception: access violation reading 0x0000026CA99DD698
```

**Comment by NikolajBjorner** [comment]
fixed the first reported issue. Not sure if there is a repro on the reported access violation.
