### ISSUE TITLE
z3 segfault (QF_NIA)

### ISSUE THREAD

**Issue by dddejan** [Z3Prover/z3#281]
Z3 segfaults when running on  ``QF_NIA/AProVE/884278/aproveSMT8166223887396796858.smt2`` from smtlib.

This is on latest master (b75780ce2b53d71f2ba298c48fcd053bf2621b61)

Backtrace:

```
#0  0x00000000008c10ac in int smt::theory_arith<smt::i_ext>::select_pivot_core<true>(int, rational&) ()
#1  0x00000000008de225 in smt::theory_arith<smt::i_ext>::make_var_feasible(int) ()
#2  0x00000000008de30a in smt::theory_arith<smt::i_ext>::make_feasible() ()
#3  0x000000000091385a in smt::theory_arith<smt::i_ext>::propagate_core() ()
#4  0x0000000000913ce0 in smt::theory_arith<smt::i_ext>::max_min(svector<int, unsigned int> const&) ()
#5  0x00000000009140b0 in smt::theory_arith<smt::i_ext>::max_min_nl_vars() ()
#6  0x00000000009141ef in smt::theory_arith<smt::i_ext>::process_non_linear() ()
#7  0x00000000009144c8 in smt::theory_arith<smt::i_ext>::final_check_core() ()
#8  0x00000000009145b4 in smt::theory_arith<smt::i_ext>::final_check_eh() ()
#9  0x000000000095dced in smt::context::final_check() ()
#10 0x0000000000967476 in smt::context::bounded_search() ()
#11 0x0000000000967700 in smt::context::search() ()
#12 0x0000000000967c58 in smt::context::setup_and_check(bool) ()
#13 0x0000000000841e35 in smt_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) ()
#14 0x0000000000dcd533 in or_else_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) ()
#15 0x0000000000dcf142 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) ()
#16 0x0000000000dd30e0 in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) ()
#17 0x0000000000dd354d in check_sat(tactic&, ref<goal>&, ref<model>&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::string&) ()
#18 0x0000000000c49497 in tactic2solver::check_sat_core(unsigned int, expr* const*) ()
#19 0x0000000000c47e24 in solver_na2as::check_sat(unsigned int, expr* const*) ()
#20 0x0000000000c4ab73 in combined_solver::check_sat(unsigned int, expr* const*) ()
#21 0x0000000000b9bfb0 in cmd_context::check_sat(unsigned int, expr* const*) ()
#22 0x0000000000b6b80e in smt2::parser::parse_check_sat() ()
#23 0x0000000000b73548 in smt2::parser::operator()() ()
#24 0x0000000000b63f1b in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&) ()
#25 0x000000000041cfb5 in read_smtlib2_commands(char const*) ()
#26 0x000000000040ede3 in main ()
```

**Comment by NikolajBjorner** [comment]
Thanks for giving something to do over the weekend
