### ISSUE TITLE
Error generating Makefile

### ISSUE THREAD

**Issue by GuzTech** [Z3Prover/z3#2810]
With the latest master, I'm getting an error that the ```dd_pdd.h``` file cannot be found when I run ```python scripts/mk_make.py```:

```
New component: 'util'
New component: 'polynomial'
New component: 'dd'
New component: 'sat'
New component: 'nlsat'
New component: 'lp'
New component: 'hilbert'
New component: 'simplex'
New component: 'automata'
New component: 'interval'
New component: 'realclosure'
New component: 'subpaving'
New component: 'ast'
New component: 'rewriter'
New component: 'macros'
New component: 'normal_forms'
New component: 'model'
New component: 'tactic'
New component: 'substitution'
New component: 'parser_util'
New component: 'grobner'
New component: 'euclid'
New component: 'proofs'
New component: 'solver'
New component: 'cmd_context'
New component: 'sat_tactic'
New component: 'smt2parser'
New component: 'pattern'
New component: 'core_tactics'
New component: 'arith_tactics'
New component: 'nlsat_tactic'
New component: 'subpaving_tactic'
New component: 'aig_tactic'
New component: 'ackermannization'
New component: 'fpa'
New component: 'bit_blaster'
New component: 'smt_params'
New component: 'proto_model'
New component: 'smt'
New component: 'bv_tactics'
New component: 'fuzzing'
New component: 'smt_tactic'
New component: 'sls_tactic'
New component: 'qe'
New component: 'sat_solver'
New component: 'fd_solver'
New component: 'muz'
New component: 'dataflow'
New component: 'transforms'
New component: 'rel'
New component: 'spacer'
New component: 'clp'
New component: 'tab'
New component: 'ddnf'
New component: 'bmc'
New component: 'fp'
New component: 'ufbv_tactic'
New component: 'smtlogic_tactics'
New component: 'fpa_tactics'
New component: 'portfolio'
New component: 'opt'
New component: 'api'
New component: 'extra_cmds'
New component: 'shell'
New component: 'test'
New component: 'api_dll'
New component: 'dotnet'
New component: 'java'
New component: 'ml'
New component: 'cpp'
Python bindings directory was detected.
New component: 'python'
New component: 'python_install'
New component: 'js'
New component: 'cpp_example'
New component: 'z3_tptp'
New component: 'c_example'
New component: 'maxsat'
New component: 'dotnet_example'
New component: 'java_example'
New component: 'ml_example'
New component: 'py_example'
Generating src/util/z3_version.h from src/util/z3_version.h.in
Generated 'src/util/z3_version.h'
Generated 'src/model/model_params.hpp'
Generated 'src/model/model_evaluator_params.hpp'
Generated 'src/util/lp/lp_params.hpp'
Generated 'src/sat/sat_scc_params.hpp'
Generated 'src/sat/sat_asymm_branch_params.hpp'
Generated 'src/sat/sat_simplifier_params.hpp'
Generated 'src/sat/sat_params.hpp'
Generated 'src/muz/base/fp_params.hpp'
Generated 'src/tactic/tactic_params.hpp'
Generated 'src/tactic/sls/sls_params.hpp'
Generated 'src/tactic/smtlogics/qfufbv_tactic_params.hpp'
Generated 'src/solver/combined_solver_params.hpp'
Generated 'src/solver/parallel_params.hpp'
Generated 'src/solver/solver_params.hpp'
Generated 'src/smt/params/smt_params_helper.hpp'
Generated 'src/ackermannization/ackermannization_params.hpp'
Generated 'src/ackermannization/ackermannize_bv_tactic_params.hpp'
Generated 'src/ast/pp_params.hpp'
Generated 'src/ast/pattern/pattern_inference_params_helper.hpp'
Generated 'src/ast/normal_forms/nnf_params.hpp'
Generated 'src/ast/fpa/fpa2bv_rewriter_params.hpp'
Generated 'src/ast/rewriter/bv_rewriter_params.hpp'
Generated 'src/ast/rewriter/poly_rewriter_params.hpp'
Generated 'src/ast/rewriter/arith_rewriter_params.hpp'
Generated 'src/ast/rewriter/rewriter_params.hpp'
Generated 'src/ast/rewriter/fpa_rewriter_params.hpp'
Generated 'src/ast/rewriter/bool_rewriter_params.hpp'
Generated 'src/ast/rewriter/array_rewriter_params.hpp'
Generated 'src/nlsat/nlsat_params.hpp'
Generated 'src/parsers/util/parser_params.hpp'
Generated 'src/math/polynomial/algebraic_params.hpp'
Generated 'src/math/realclosure/rcf_params.hpp'
Generated 'src/opt/opt_params.hpp'
Generated 'src/ast/pattern/database.h'
Component api
Component portfolio
Component smtlogic_tactics
Component ackermannization
Component model
Component rewriter
Component ast
Component util
Component polynomial
Component automata
Component solver
Component tactic
Component proofs
Component sat_solver
Component core_tactics
Component macros
Component normal_forms
Component pattern
Component smt2parser
Component cmd_context
Component parser_util
Component aig_tactic
Component bv_tactics
Component bit_blaster
Component arith_tactics
Component sat
Component dd
Component sat_tactic
Component nlsat_tactic
Component nlsat
Component smt_tactic
Component smt
Component proto_model
Component smt_params
Component substitution
Component grobner
Component euclid
Component simplex
Component fpa
Component lp
Component fp
Component muz
Component qe
Component clp
Component transforms
Component hilbert
Component dataflow
Component tab
Component rel
Component bmc
Component fd_solver
Component ddnf
Component spacer
Component ufbv_tactic
Component fpa_tactics
Component sls_tactic
Component subpaving_tactic
Component subpaving
Component interval
Component realclosure
Component opt
Component extra_cmds
Component shell
Generated 'src/shell/install_tactic.cpp'
Component api
Component portfolio
Component smtlogic_tactics
Component ackermannization
Component model
Component rewriter
Component ast
Component util
Component polynomial
Component automata
Component solver
Component tactic
Component proofs
Component sat_solver
Component core_tactics
Component macros
Component normal_forms
Component pattern
Component smt2parser
Component cmd_context
Component parser_util
Component aig_tactic
Component bv_tactics
Component bit_blaster
Component arith_tactics
Component sat
Component dd
Component sat_tactic
Component nlsat_tactic
Component nlsat
Component smt_tactic
Component smt
Component proto_model
Component smt_params
Component substitution
Component grobner
Component euclid
Component simplex
Component fpa
Component lp
Component fp
Component muz
Component qe
Component clp
Component transforms
Component hilbert
Component dataflow
Component tab
Component rel
Component bmc
Component fd_solver
Component ddnf
Component spacer
Component ufbv_tactic
Component fpa_tactics
Component sls_tactic
Component subpaving_tactic
Component subpaving
Component interval
Component realclosure
Component opt
Component fuzzing
Component test
Generated 'src/test/install_tactic.cpp'
Component api
Component portfolio
Component smtlogic_tactics
Component ackermannization
Component model
Component rewriter
Component ast
Component util
Component polynomial
Component automata
Component solver
Component tactic
Component proofs
Component sat_solver
Component core_tactics
Component macros
Component normal_forms
Component pattern
Component smt2parser
Component cmd_context
Component parser_util
Component aig_tactic
Component bv_tactics
Component bit_blaster
Component arith_tactics
Component sat
Component dd
Component sat_tactic
Component nlsat_tactic
Component nlsat
Component smt_tactic
Component smt
Component proto_model
Component smt_params
Component substitution
Component grobner
Component euclid
Component simplex
Component fpa
Component lp
Component fp
Component muz
Component qe
Component clp
Component transforms
Component hilbert
Component dataflow
Component tab
Component rel
Component bmc
Component fd_solver
Component ddnf
Component spacer
Component ufbv_tactic
Component fpa_tactics
Component sls_tactic
Component subpaving_tactic
Component subpaving
Component interval
Component realclosure
Component opt
Component extra_cmds
Component api_dll
Generated 'src/api/dll/install_tactic.cpp'
Generated 'src/shell/mem_initializer.cpp'
Generated 'src/test/mem_initializer.cpp'
Generated 'src/api/dll/mem_initializer.cpp'
Generated 'src/shell/gparams_register_modules.cpp'
Generated 'src/test/gparams_register_modules.cpp'
Generated 'src/api/dll/gparams_register_modules.cpp'
Generated 'src/api/python/z3/z3consts.py
Generated 'src/api/api_log_macros.h'
Generated 'src/api/api_log_macros.cpp'
Generated 'src/api/api_commands.cpp'
Generated 'src/api/python/z3/z3core.py'
Listing 'src/api/python/z3'...
Compiling 'src/api/python/z3/__init__.py'...
Compiling 'src/api/python/z3/z3.py'...
Compiling 'src/api/python/z3/z3consts.py'...
Compiling 'src/api/python/z3/z3core.py'...
Compiling 'src/api/python/z3/z3num.py'...
Compiling 'src/api/python/z3/z3poly.py'...
Compiling 'src/api/python/z3/z3printer.py'...
Compiling 'src/api/python/z3/z3rcf.py'...
Compiling 'src/api/python/z3/z3types.py'...
Compiling 'src/api/python/z3/z3util.py'...
Generated python bytecode
Copied 'z3.py'
Copied 'z3poly.py'
Copied 'z3consts.py'
Copied 'z3rcf.py'
Copied 'z3types.py'
Copied '__init__.py'
Copied 'z3num.py'
Copied 'z3core.py'
Copied 'z3util.py'
Copied 'z3printer.py'
Copied 'z3util.cpython-38.pyc'
Copied 'z3rcf.cpython-38.pyc'
Copied '__init__.cpython-38.pyc'
Copied 'z3consts.cpython-38.pyc'
Copied 'z3num.cpython-38.pyc'
Copied 'z3.cpython-38.pyc'
Copied 'z3poly.cpython-38.pyc'
Copied 'z3types.cpython-38.pyc'
Copied 'z3core.cpython-38.pyc'
Copied 'z3printer.cpython-38.pyc'
Testing ar...
Testing g++...
Testing gcc...
Testing floating point support...
Host platform:  Linux
C++ Compiler:   g++
C Compiler  :   gcc
Archive Tool:   ar
Arithmetic:     internal
Prefix:         /usr
64-bit:         True
FP math:        SSE2-GCC
Python pkg dir: /usr/lib/python3.8/site-packages
Python version: 3.8
Writing build/Makefile
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/oguz286/Software/SymbiYosys/z3/scripts/mk_util.py", line 2724, in mk_makefile
    c.mk_makefile(out)
  File "/home/oguz286/Software/SymbiYosys/z3/scripts/mk_util.py", line 1116, in mk_makefile
    Component.mk_makefile(self, out)
  File "/home/oguz286/Software/SymbiYosys/z3/scripts/mk_util.py", line 1063, in mk_makefile
    self.add_cpp_rules(out, include_defs, cppfile)
  File "/home/oguz286/Software/SymbiYosys/z3/scripts/mk_util.py", line 1020, in add_cpp_rules
    self.add_rule_for_each_include(out, cppfile)
  File "/home/oguz286/Software/SymbiYosys/z3/scripts/mk_util.py", line 1000, in add_rule_for_each_include
    owner.add_h_rule(out, include)
  File "/home/oguz286/Software/SymbiYosys/z3/scripts/mk_util.py", line 1012, in add_h_rule
    self.add_rule_for_each_include(out, include)
  File "/home/oguz286/Software/SymbiYosys/z3/scripts/mk_util.py", line 999, in add_rule_for_each_include
    owner = self.find_file(include, fullname)
  File "/home/oguz286/Software/SymbiYosys/z3/scripts/mk_util.py", line 983, in find_file
    raise MKException("Failed to find include file '%s' for '%s' when processing '%s'." % (fname, ownerfile, self.name))
mk_exception.MKException: "Failed to find include file 'dd_pdd.h' for 'src/math/grobner/pdd_grobner.h' when processing 'grobner'."
```

The file is present in ```src/math/dd/``` but the Python script cannot find it for some reason.

**Comment by NikolajBjorner** [comment]
wait for builds to be green
