### ISSUE TITLE
forall

### ISSUE THREAD

**Issue by dah-fari7009** [Z3Prover/z3#2884]
Hello,
I am trying to make a forall on the expression I obtain from context.mkApp(....)
(forall (f a) ... where f is a function )
I obtain the following exception:
com.microsoft.z3.Z3Exception: invalid argument
	at com.microsoft.z3.Native.mkQuantifierConst(Native.java:2446)
	at com.microsoft.z3.Quantifier.of(Quantifier.java:224)
	at com.microsoft.z3.Context.mkForall(Context.java:2468)
	at GradDiff.GradDiff.getNextToRefine(GradDiff.java:158)
	at GradDiff.GradDiff.equivalenceResult(GradDiff.java:66)
	at DSE.DSE.runEquivalenceChecking(DSE.java:123)
	at GradDiff.GradDiff.main(GradDiff.java:183)

Am I doing something wrong ? Do you know of any other way to achieve what I am trying to do (quantify over the application, and possibly other expressions)

**Comment by NikolajBjorner** [comment]
you quantify over constant symbols. JavaExample.java contains a few examples of legal ways to use quantification.

**Comment by dah-fari7009** [comment]
Thank you for this answer. 
It was my understanding that a function application is a constant (since it is a fixed result)

**Comment by NikolajBjorner** [comment]
I don't understand the background for this question. Quantifiers are over variables. Variables are not compound expressions. I am afraid I can't say anything else than you shouldn't try to bind compound expressions in a quantifier.
