### ISSUE TITLE
Can't generate makefiles from scripts/mk_make.py

### ISSUE THREAD

**Issue by asedel** [Z3Prover/z3#2906]
on tag z3-4.8.7 ( which is green) I am trying to compile on centOS6; python version is 2.6.6, make version is 4.2 and gcc/g++ are RedHat 4.9.2-6

> /source/z3@(z3-4.8.7) $ python scripts/mk_make.py
> New component: 'util'
> New component: 'polynomial'
> New component: 'sat'
> New component: 'nlsat'
> New component: 'lp'
> New component: 'hilbert'
> New component: 'simplex'
> New component: 'automata'
> New component: 'interval'
> New component: 'realclosure'
> New component: 'subpaving'
> New component: 'ast'
> New component: 'rewriter'
> New component: 'macros'
> New component: 'normal_forms'
> New component: 'model'
> New component: 'tactic'
> New component: 'substitution'
> New component: 'parser_util'
> New component: 'grobner'
> New component: 'euclid'
> New component: 'proofs'
> New component: 'solver'
> New component: 'cmd_context'
> New component: 'sat_tactic'
> New component: 'smt2parser'
> New component: 'pattern'
> New component: 'core_tactics'
> New component: 'arith_tactics'
> New component: 'nlsat_tactic'
> New component: 'subpaving_tactic'
> New component: 'aig_tactic'
> New component: 'ackermannization'
> New component: 'fpa'
> New component: 'bit_blaster'
> New component: 'smt_params'
> New component: 'proto_model'
> New component: 'smt'
> New component: 'bv_tactics'
> New component: 'fuzzing'
> New component: 'smt_tactic'
> New component: 'sls_tactic'
> New component: 'qe'
> New component: 'sat_solver'
> New component: 'fd_solver'
> New component: 'muz'
> New component: 'dataflow'
> New component: 'transforms'
> New component: 'rel'
> New component: 'spacer'
> New component: 'clp'
> New component: 'tab'
> New component: 'ddnf'
> New component: 'bmc'
> New component: 'fp'
> New component: 'ufbv_tactic'
> New component: 'smtlogic_tactics'
> New component: 'fpa_tactics'
> New component: 'portfolio'
> New component: 'opt'
> New component: 'api'
> New component: 'extra_cmds'
> New component: 'shell'
> New component: 'test'
> New component: 'api_dll'
> New component: 'dotnet'
> New component: 'java'
> New component: 'ml'
> New component: 'cpp'
> Python bindings directory was detected.
> New component: 'python'
> New component: 'python_install'
> New component: 'js'
> New component: 'cpp_example'
> New component: 'z3_tptp'
> New component: 'c_example'
> New component: 'maxsat'
> New component: 'dotnet_example'
> New component: 'java_example'
> New component: 'ml_example'
> New component: 'py_example'
> Traceback (most recent call last):
>   File "scripts/mk_make.py", line 16, in <module>
>     update_version()
>   File "/source/z3/scripts/mk_util.py", line 2800, in update_version
>     mk_version_dot_h(major, minor, build, revision)
>   File "/source/z3/scripts/mk_util.py", line 2827, in mk_version_dot_h
>     'Z3_FULL_VERSION': get_full_version_string(major, minor, build, revision)
>   File "/source/z3/scripts/mk_util.py", line 3461, in configure_file
>     print("Generating {} from {}".format(output_file_path, template_file_path))
> ValueError: zero length field name in format

I have also tried cmake (3.16.3) and I get a similar error in a slightly different spot:
the cmake action succeeds: 

> /source/z3/build@(z3-4.8.7) $ cmake -G "Unix Makefiles" ../
> -- The CXX compiler identification is GNU 4.9.2
> -- Check for working CXX compiler: /usr/local/bin/c++
> -- Check for working CXX compiler: /usr/local/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Z3 version 4.8.7.0
> -- Found simple git working directory
> -- Found git directory "/source/z3"
> CMake Warning (dev) at cmake/git_utils.cmake:57 (message):
>   Git head file "/source/z3/HEAD" cannot be found
> Call Stack (most recent call first):
>   CMakeLists.txt:75 (add_git_dir_dependency)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning at CMakeLists.txt:103 (message):
>   Failed to add git dependency.
> 
> 
> CMake Warning at CMakeLists.txt:60 (message):
>   Disabling Z3_INCLUDE_GIT_DESCRIBE
> Call Stack (most recent call first):
>   CMakeLists.txt:104 (disable_git_describe)
> 
> 
> CMake Warning at CMakeLists.txt:64 (message):
>   Disabling Z3_INCLUDE_GIT_HASH
> Call Stack (most recent call first):
>   CMakeLists.txt:105 (disable_git_hash)
> 
> 
> -- CMake generator: Unix Makefiles
> -- CMAKE_BUILD_TYPE is not set. Setting default
> -- The available build types are: Debug;Release;RelWithDebInfo;MinSizeRel
> CMake Warning (dev) at CMakeLists.txt:142 (set):
>   implicitly converting 'String' to 'STRING' type.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Build type: RelWithDebInfo
> -- Found PythonInterp: /usr/bin/python (found version "2.6.6")
> -- PYTHON_EXECUTABLE: /usr/bin/python
> -- Detected target architecture: x86_64
> -- Platform: Linux
> -- Not using libgmp
> -- Not using Z3_API_LOG_SYNC
> -- Thread-safe build
> -- Performing Test HAS_SSE2
> -- Performing Test HAS_SSE2 - Success
> -- Looking for C++ include pthread.h
> -- Looking for C++ include pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Performing Test HAS__Wall
> -- Performing Test HAS__Wall - Success
> -- C++ compiler supports -Wall
> -- Treating only serious compiler warnings as errors
> -- Performing Test HAS__Werror_odr
> -- Performing Test HAS__Werror_odr - Failed
> -- C++ compiler does not support -Werror=odr
> -- Performing Test HAS__fvisibility_hidden
> -- Performing Test HAS__fvisibility_hidden - Success
> -- C++ compiler supports -fvisibility=hidden
> -- Performing Test HAS__fPIC
> -- Performing Test HAS__fPIC - Success
> -- C++ compiler supports -fPIC
> -- LTO disabled
> -- CMAKE_CXX_FLAGS: ""
> -- CMAKE_EXE_LINKER_FLAGS: ""
> -- CMAKE_STATIC_LINKER_FLAGS: ""
> -- CMAKE_SHARED_LINKER_FLAGS: ""
> -- CMAKE_CXX_FLAGS_RELWITHDEBINFO: "-O2 -g -DNDEBUG"
> -- CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO: ""
> -- CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO: ""
> -- CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO: ""
> -- Z3_COMPONENT_CXX_DEFINES: $<$<CONFIG:Debug>:Z3DEBUG>;$<$<CONFIG:Release>:_EXTERNAL_RELEASE>;$<$<CONFIG:RelWithDebInfo>:_EXTERNAL_RELEASE>;-D_LINUX_;-D_USE_THREAD_LOCAL;-D_MP_INTERNAL;$<$<CONFIG:Debug>:_TRACE>
> -- Z3_COMPONENT_CXX_FLAGS: -mfpmath=sse;-msse;-msse2;-Wall;-fvisibility=hidden;-fPIC
> -- Z3_DEPENDENT_LIBS: -lpthread
> -- Z3_COMPONENT_EXTRA_INCLUDE_DIRS: /source/z3/build/src;/source/z3/src
> -- Z3_DEPENDENT_EXTRA_CXX_LINK_FLAGS:
> -- CMAKE_INSTALL_LIBDIR: "lib64"
> -- CMAKE_INSTALL_BINDIR: "bin"
> -- CMAKE_INSTALL_INCLUDEDIR: "include"
> -- CMAKE_INSTALL_PKGCONFIGDIR: "lib64/pkgconfig"
> -- CMAKE_INSTALL_Z3_CMAKE_PACKAGE_DIR: "lib64/cmake/z3"
> -- Adding component util
> -- Adding component polynomial
> -- Adding rule to generate "algebraic_params.hpp"
> -- Adding component sat
> -- Adding rule to generate "sat_asymm_branch_params.hpp"
> -- Adding rule to generate "sat_params.hpp"
> -- Adding rule to generate "sat_scc_params.hpp"
> -- Adding rule to generate "sat_simplifier_params.hpp"
> -- Adding component nlsat
> -- Adding rule to generate "nlsat_params.hpp"
> -- Adding component lp
> -- Adding rule to generate "lp_params.hpp"
> -- Adding component hilbert
> -- Adding component simplex
> -- Adding component automata
> -- Adding component interval
> -- Adding component realclosure
> -- Adding rule to generate "rcf_params.hpp"
> -- Adding component subpaving
> -- Adding component ast
> -- Adding rule to generate "pp_params.hpp"
> -- Adding component rewriter
> -- Adding rule to generate "arith_rewriter_params.hpp"
> -- Adding rule to generate "array_rewriter_params.hpp"
> -- Adding rule to generate "bool_rewriter_params.hpp"
> -- Adding rule to generate "bv_rewriter_params.hpp"
> -- Adding rule to generate "fpa_rewriter_params.hpp"
> -- Adding rule to generate "poly_rewriter_params.hpp"
> -- Adding rule to generate "rewriter_params.hpp"
> -- Adding component normal_forms
> -- Adding rule to generate "nnf_params.hpp"
> -- Adding component model
> -- Adding rule to generate "model_evaluator_params.hpp"
> -- Adding rule to generate "model_params.hpp"
> -- Adding component tactic
> -- Adding rule to generate "tactic_params.hpp"
> -- Adding component substitution
> -- Adding component parser_util
> -- Adding rule to generate "parser_params.hpp"
> -- Adding component grobner
> -- Adding component euclid
> -- Adding component core_tactics
> -- Adding component subpaving_tactic
> -- Adding component aig_tactic
> -- Adding component solver
> -- Adding rule to generate "combined_solver_params.hpp"
> -- Adding rule to generate "parallel_params.hpp"
> -- Adding rule to generate "solver_params.hpp"
> -- Adding component sat_tactic
> -- Adding component arith_tactics
> -- Adding component nlsat_tactic
> -- Adding component ackermannization
> -- Adding rule to generate "ackermannization_params.hpp"
> -- Adding rule to generate "ackermannize_bv_tactic_params.hpp"
> -- Adding component cmd_context
> -- Adding component extra_cmds
> -- Adding component smt2parser
> -- Adding component proofs
> -- Adding component fpa
> -- Adding rule to generate "fpa2bv_rewriter_params.hpp"
> -- Adding component macros
> -- Adding component pattern
> -- Adding rule to generate "pattern_inference_params_helper.hpp"
> -- Adding component bit_blaster
> -- Adding component smt_params
> -- Adding rule to generate "smt_params_helper.hpp"
> -- Adding component proto_model
> -- Adding component smt
> -- Adding component bv_tactics
> -- Adding component smt_tactic
> -- Adding component sls_tactic
> -- Adding rule to generate "sls_params.hpp"
> -- Adding component qe
> -- Adding component muz
> -- Adding rule to generate "fp_params.hpp"
> -- Adding component dataflow
> -- Adding component transforms
> -- Adding component rel
> -- Adding component clp
> -- Adding component tab
> -- Adding component bmc
> -- Adding component ddnf
> -- Adding component spacer
> -- Adding component fp
> -- Adding component ufbv_tactic
> -- Adding component sat_solver
> -- Adding component smtlogic_tactics
> -- Adding rule to generate "qfufbv_tactic_params.hpp"
> -- Adding component fpa_tactics
> -- Adding component fd_solver
> -- Adding component portfolio
> -- Adding component opt
> -- Adding rule to generate "opt_params.hpp"
> -- Adding component api
> -- Adding component api_dll
> -- Adding component fuzzing
> -- Building documentation disabled
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /source/z3/build

but the make portion fails 

> /source/z3/build@(z3-4.8.7) $ make -j8
> [  0%] Building CXX object src/util/CMakeFiles/util.dir/approx_nat.cpp.o
> [  0%] Building CXX object src/util/CMakeFiles/util.dir/approx_set.cpp.o
> [  0%] Building CXX object src/util/CMakeFiles/util.dir/bit_util.cpp.o
> [  0%] Building CXX object src/util/CMakeFiles/util.dir/common_msgs.cpp.o
> [  0%] Building CXX object src/util/CMakeFiles/util.dir/bit_vector.cpp.o
> [  1%] Building CXX object src/util/CMakeFiles/util.dir/cmd_context_types.cpp.o
> [  1%] Building CXX object src/util/CMakeFiles/util.dir/debug.cpp.o
> [  1%] Building CXX object src/util/CMakeFiles/util.dir/env_params.cpp.o
> [  1%] Building CXX object src/util/CMakeFiles/util.dir/fixed_bit_vector.cpp.o
> [  1%] Building CXX object src/util/CMakeFiles/util.dir/gparams.cpp.o
> [  1%] Building CXX object src/util/CMakeFiles/util.dir/hash.cpp.o
> [  1%] Building CXX object src/util/CMakeFiles/util.dir/hwf.cpp.o
> [  1%] Building CXX object src/util/CMakeFiles/util.dir/inf_int_rational.cpp.o
> [  2%] Building CXX object src/util/CMakeFiles/util.dir/inf_rational.cpp.o
> [  2%] Building CXX object src/util/CMakeFiles/util.dir/inf_s_integer.cpp.o
> [  2%] Building CXX object src/util/CMakeFiles/util.dir/lbool.cpp.o
> [  2%] Building CXX object src/util/CMakeFiles/util.dir/luby.cpp.o
> [  2%] Building CXX object src/util/CMakeFiles/util.dir/memory_manager.cpp.o
> [  2%] Building CXX object src/util/CMakeFiles/util.dir/min_cut.cpp.o
> [  2%] Building CXX object src/util/CMakeFiles/util.dir/mpbq.cpp.o
> [  2%] Building CXX object src/util/CMakeFiles/util.dir/mpf.cpp.o
> [  2%] Building CXX object src/util/CMakeFiles/util.dir/mpff.cpp.o
> [  3%] Building CXX object src/util/CMakeFiles/util.dir/mpfx.cpp.o
> [  3%] Building CXX object src/util/CMakeFiles/util.dir/mpn.cpp.o
> [  3%] Building CXX object src/util/CMakeFiles/util.dir/mpq.cpp.o
> [  3%] Building CXX object src/util/CMakeFiles/util.dir/mpq_inf.cpp.o
> [  3%] Building CXX object src/util/CMakeFiles/util.dir/mpz.cpp.o
> [  3%] Building CXX object src/util/CMakeFiles/util.dir/page.cpp.o
> [  3%] Building CXX object src/util/CMakeFiles/util.dir/params.cpp.o
> [  3%] Building CXX object src/util/CMakeFiles/util.dir/permutation.cpp.o
> [  4%] Building CXX object src/util/CMakeFiles/util.dir/prime_generator.cpp.o
> [  4%] Building CXX object src/util/CMakeFiles/util.dir/rational.cpp.o
> [  4%] Building CXX object src/util/CMakeFiles/util.dir/region.cpp.o
> [  4%] Building CXX object src/util/CMakeFiles/util.dir/rlimit.cpp.o
> [  4%] Building CXX object src/util/CMakeFiles/util.dir/scoped_ctrl_c.cpp.o
> [  4%] Building CXX object src/util/CMakeFiles/util.dir/scoped_timer.cpp.o
> [  4%] Building CXX object src/util/CMakeFiles/util.dir/sexpr.cpp.o
> [  4%] Building CXX object src/util/CMakeFiles/util.dir/s_integer.cpp.o
> [  4%] Building CXX object src/util/CMakeFiles/util.dir/small_object_allocator.cpp.o
> [  6%] Building CXX object src/util/CMakeFiles/util.dir/smt2_util.cpp.o
> [  6%] Building CXX object src/util/CMakeFiles/util.dir/stack.cpp.o
> [  6%] Building CXX object src/util/CMakeFiles/util.dir/statistics.cpp.o
> [  6%] Building CXX object src/util/CMakeFiles/util.dir/symbol.cpp.o
> [  6%] Building CXX object src/util/CMakeFiles/util.dir/timeit.cpp.o
> [  6%] Building CXX object src/util/CMakeFiles/util.dir/timeout.cpp.o
> [  6%] Building CXX object src/util/CMakeFiles/util.dir/trace.cpp.o
> [  6%] Building CXX object src/util/CMakeFiles/util.dir/util.cpp.o
> [  6%] Building CXX object src/util/CMakeFiles/util.dir/warning.cpp.o
> [  7%] Building CXX object src/util/CMakeFiles/util.dir/z3_exception.cpp.o
> [  7%] Built target util
> Scanning dependencies of target automata
> Scanning dependencies of target hilbert
> Scanning dependencies of target interval
> Scanning dependencies of target simplex
> [  7%] Generating "/source/z3/build/src/math/polynomial/algebraic_params.hpp" from "algebraic_params.pyg"
> Scanning dependencies of target euclid
> [  7%] Generating "/source/z3/build/src/sat/sat_asymm_branch_params.hpp" from "sat_asymm_branch_params.pyg"
> [  7%] Generating "/source/z3/build/src/sat/sat_simplifier_params.hpp" from "sat_simplifier_params.pyg"
> Traceback (most recent call last):
>   File "/source/z3/scripts/pyg2hpp.py", line 35, in <module>
>     sys.exit(main(sys.argv[1:]))
>   File "/source/z3/scripts/pyg2hpp.py", line 29, in main
> Traceback (most recent call last):
>   File "/source/z3/scripts/pyg2hpp.py", line 35, in <module>
>     logging.info('Using {}'.format(pyg_full_path))
> ValueError: zero length field name in format
>     sys.exit(main(sys.argv[1:]))
>   File "/source/z3/scripts/pyg2hpp.py", line 29, in main
> Traceback (most recent call last):
>   File "/source/z3/scripts/pyg2hpp.py", line 35, in <module>
> make[2]: *** [src/sat/CMakeFiles/sat.dir/build.make:82: src/sat/sat_simplifier_params.hpp] Error 1
>     logging.info('Using {}'.format(pyg_full_path))
> make[2]: *** Waiting for unfinished jobs....
> ValueError: zero length field name in format
>     sys.exit(main(sys.argv[1:]))
>   File "/source/z3/scripts/pyg2hpp.py", line 29, in main
> make[2]: *** [src/math/polynomial/CMakeFiles/polynomial.dir/build.make:64: src/math/polynomial/algebraic_params.hpp] Error 1
>     logging.info('Using {}'.format(pyg_full_path))
> ValueError: zero length field name in format
> make[1]: *** [CMakeFiles/Makefile2:1643: src/math/polynomial/CMakeFiles/polynomial.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make[2]: *** [src/sat/CMakeFiles/sat.dir/build.make:64: src/sat/sat_asymm_branch_params.hpp] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1670: src/sat/CMakeFiles/sat.dir/all] Error 2
> [  7%] Building CXX object src/math/automata/CMakeFiles/automata.dir/automaton.cpp.o
> [  7%] Building CXX object src/math/euclid/CMakeFiles/euclid.dir/euclidean_solver.cpp.o
> [  7%] Building CXX object src/math/interval/CMakeFiles/interval.dir/interval_mpq.cpp.o
> [  8%] Building CXX object src/math/hilbert/CMakeFiles/hilbert.dir/hilbert_basis.cpp.o
> [  9%] Building CXX object src/math/simplex/CMakeFiles/simplex.dir/simplex.cpp.o
> [  9%] Building CXX object src/math/simplex/CMakeFiles/simplex.dir/model_based_opt.cpp.o
> [  9%] Built target interval
> [  9%] Built target automata
> [  9%] Built target euclid
> [  9%] Built target hilbert
> [  9%] Built target simplex
> make: *** [Makefile:130: all] Error 2

**Comment by asedel** [comment]
seem to have fixed by upgrading to python 2.7.16
