### ISSUE TITLE
Example on python api document about z3.z3util.prove not working

### ISSUE THREAD

**Issue by Party4Bread** [Z3Prover/z3#3000]
On the example of prove
http://z3prover.github.io/api/html/z3.z3util.html#-prove
```python
from z3 import And,Bools
from z3.z3util import prove
x,y=Bools('x y')
r,m = prove(And(x,True),assume=y,verbose=0); r,model_str(m,as_str=False)
```
raise error of 
```
Traceback (most recent call last):
  File ".\z3fragment.py", line 31, in <module>
    r,m = prove(And(x,True),assume=y,verbose=0); r,model_str(m,as_str=False)
  File "C:\Users\solsa\Miniconda3\envs\math\lib\site-packages\z3\z3util.py", line 232, in prove
    assert not assume or is_expr(assume)
  File "C:\Users\solsa\Miniconda3\envs\math\lib\site-packages\z3\z3.py", line 343, in __bool__
    raise Z3Exception("Symbolic expressions cannot be cast to concrete Boolean values.")
z3.z3types.Z3Exception: Symbolic expressions cannot be cast to concrete Boolean values.
```

**Comment by Party4Bread** [comment]
Maybe api document is just outdated

**Comment by NikolajBjorner** [comment]
sometimes it is, but you can run the example directly from python using python's "help" facility.
So do help(prove) and it will rerun the example.
