### ISSUE TITLE
Debug branch: LeakSantizer at ../src/util/memory_manager.cpp:268

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3121]
Hi,
For the two formulas :
[boolean20.txt](https://github.com/Z3Prover/z3/files/4280881/boolean20.txt)
[boolean39.txt](https://github.com/Z3Prover/z3/files/4280889/boolean39.txt)

ASAN detects a memory leak
~~~~
==191600==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 320 byte(s) in 8 object(s) allocated from:
    #0 0x7fb5cbd81602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x256f179 in memory::allocate(unsigned long) ../src/util/memory_manager.cpp:268
    #2 0x25a5c4a in mpz_manager<true>::allocate(unsigned int) ../src/util/mpz.cpp:195
    #3 0x25a835f in mpz_manager<true>::big_set(mpz&, mpz const&) ../src/util/mpz.cpp:1497
    #4 0x46494f in mpz_manager<true>::set(mpz&, mpz const&) ../src/util/mpz.h:530
    #5 0x464630 in mpq_manager<true>::set(mpz&, mpz const&) ../src/util/mpq.h:653
    #6 0x463330 in mpq_manager<true>::set(mpq&, mpq const&) ../src/util/mpq.h:656
    #7 0x46109b in rational::rational(rational const&) ../src/util/rational.h:43
    #8 0x11cc5bd in std::pair<unsigned int, rational>::pair(std::pair<unsigned int, rational> const&) /usr/include/c++/5/bits/stl_pair.h:127
    #9 0x11cc89a in vector_value_trail<smt::context, std::pair<unsigned int, rational>, true>::vector_value_trail(vector_value_trail<smt::context, std::pair<unsigned int, rational>, true> const&) (/home/peisen/test/tofuzz/z3-debug/build/z3+0x11cc89a)
    #10 0x11cc985 in void smt::context::push_trail<vector_value_trail<smt::context, std::pair<unsigned int, rational>, true> >(vector_value_trail<smt::context, std::pair<unsigned int, rational>, true> const&) (/home/peisen/test/tofuzz/z3-debug/build/z3+0x11cc985)
    #11 0x11bb07d in smt::theory_lra::imp::set_bound(unsigned int, unsigned int, rational const&, bool) ../src/smt/theory_lra.cpp:3078
    #12 0x11bac63 in smt::theory_lra::imp::set_upper_bound(unsigned int, unsigned int, rational const&) ../src/smt/theory_lra.cpp:3063
    #13 0x11ba8a9 in smt::theory_lra::imp::propagate_eqs(unsigned int, unsigned int, lp::lconstraint_kind, lp_api::bound&) ../src/smt/theory_lra.cpp:3046
    #14 0x11ba328 in smt::theory_lra::imp::assert_bound(int, bool, lp_api::bound&) ../src/smt/theory_lra.cpp:2993
    #15 0x11b4fa0 in smt::theory_lra::imp::propagate() ../src/smt/theory_lra.cpp:2281
    #16 0x11950f0 in smt::theory_lra::propagate() ../src/smt/theory_lra.cpp:3929
~~~~

z3 is compiled with ASAN and debug mode
~~~~
CFLAGS="-fsanitize=address -fno-omit-frame-pointer" CXXFLAGS="-fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-fsanitize=address" python scripts/mk_make.py --debug
~~~~

OS: Ubuntu 16.04
Commit: `9f16feee2`

**Comment by rainoftime** [comment]
After patching the commit, I found another leak. The source may be different, but the final program point in the trace is still ../src/util/memory_manager.cpp:268

[268.txt](https://github.com/Z3Prover/z3/files/4284829/268.txt)

**Comment by NikolajBjorner** [comment]
maybe you can suggest a fix?
