### ISSUE TITLE
ASAN SEGV for QF_BV instance at ../src/ast/rewriter/bv_trailing.cpp

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3143]
Hi,
For this formula

[bvtrial.txt](https://github.com/Z3Prover/z3/files/4287076/bvtrial.txt)

ASAN detects an SEGV.

z3 is compiled with ASAN and debug mode
~~~~
CFLAGS="-fsanitize=address -fno-omit-frame-pointer" CXXFLAGS="-fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-fsanitize=address" python scripts/mk_make.py --debug
~~~~

OS: Ubuntu 16.04
Commit: fcbf660592c

The error information is as below:
~~~~
ASAN:SIGSEGV
=================================================================
==102780==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000004 (pc 0x000000467af5 bp 0x7ffda924cd50 sp 0x7ffda924cd40 T0)
    #0 0x467af4 in ast::get_kind() const ../src/ast/ast.h:504
    #1 0x21e7e90 in get_sort(expr const*) ../src/ast/ast.cpp:423
    #2 0x468013 in ast_manager::get_sort(expr const*) const ../src/ast/ast.h:1735
    #3 0x55e1b3 in bv_util::get_bv_size(expr const*) const (/home/peisen/test/tofuzz/z3-debug/build/z3+0x55e1b3)
    #4 0x1c52c3d in bv_trailing::imp::remove_trailing_mul(app*, unsigned int, obj_ref<expr, ast_manager>&, unsigned int) ../src/ast/rewriter/bv_trailing.cpp:162
    #5 0x1c53b0d in bv_trailing::imp::remove_trailing_core(expr*, unsigned int, obj_ref<expr, ast_manager>&, unsigned int) ../src/ast/rewriter/bv_trailing.cpp:237
    #6 0x1c51d6e in bv_trailing::imp::remove_trailing(expr*, unsigned int, obj_ref<expr, ast_manager>&, unsigned int) ../src/ast/rewriter/bv_trailing.cpp:94
    #7 0x1c5145d in bv_trailing::imp::eq_remove_trailing(expr*, expr*, obj_ref<expr, ast_manager>&) ../src/ast/rewriter/bv_trailing.cpp:73
    #8 0x1c506fe in bv_trailing::eq_remove_trailing(expr*, expr*, obj_ref<expr, ast_manager>&) ../src/ast/rewriter/bv_trailing.cpp:392
    #9 0x1bd7884 in bv_rewriter::mk_eq_core(expr*, expr*, obj_ref<expr, ast_manager>&) ../src/ast/rewriter/bv_rewriter.cpp:2612
    #10 0x1b712bf in reduce_app_core ../src/ast/rewriter/th_rewriter.cpp:178
    #11 0x1b74408 in reduce_app ../src/ast/rewriter/th_rewriter.cpp:618
    #12 0x1b81217 in process_app<false> ../src/ast/rewriter/rewriter_def.h:291
    #13 0x1b7b9c3 in resume_core<false> ../src/ast/rewriter/rewriter_def.h:742
    #14 0x1b7a7b8 in main_loop<false> ../src/ast/rewriter/rewriter_def.h:703
    #15 0x1b790dc in operator() ../src/ast/rewriter/rewriter_def.h:773
    #16 0x1b76910 in th_rewriter::operator()(expr*, obj_ref<expr, ast_manager>&, obj_ref<app, ast_manager>&) ../src/ast/rewriter/th_rewriter.cpp:854
    #17 0x17d9f95 in simplify_tactic::imp::operator()(goal&) ../src/tactic/core/simplify_tactic.cpp:59
    #18 0x17d9387 in simplify_tactic::operator()(ref<goal> const&, sref_buffer<goal, 
  ....
~~~~

**Comment by NikolajBjorner** [comment]
Why does ASAN exercise code that isn't reached with normal debug mode?
Can the analysis explain this first, then it could be easier to debug.
