### ISSUE TITLE
ASAN SEGV at smt_enode.h:201

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3260]
Hi, for the following formulas

Case 1
~~~~
(set-logic NIA)
(set-option :smt.arith.solver 4)
(declare-const i7 Int)
(assert (forall ((q0 Bool) (q1 Int) (q2 Int) (q3 Bool)) (not (distinct q1 82))))
(push 1)
(assert (xor true true true (= i7 0) true true))
(check-sat)
~~~~
Case 2
~~~~
(set-logic NIA)
(declare-fun _substvar_18_ () Int)
(set-option :smt.arith.solver 4)
(assert (forall ((q0 Bool) (q1 Int) (q2 Int) (q3 Bool)) (not (distinct q1 82))))
(push 1)
(assert (<= _substvar_18_ 286))
(check-sat)
~~~~

Z3 throws a SIGSEGV
~~~~
=================================================================
==76356==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x000000c2fb9d bp 0x7ffe177b8b40 sp 0x7ffe177b8b30 T0)
    #0 0xc2fb9c in smt::enode::get_root() const ../src/smt/smt_enode.h:201
    #1 0xeb9754 in smt::enode::init(ast_manager&, void*, old_ptr_vector<smt::enode> const&, app*, unsigned int, bool, bool, unsigned int, bool, bool) ../src/smt/smt_enode.cpp:57
    #2 0xeb9ac5 in smt::enode::mk(ast_manager&, region&, old_ptr_vector<smt::enode> const&, app*, unsigned int, bool, bool, unsigned int, bool, bool) ../src/smt/smt_enode.cpp:70
    #3 0xf33740 in smt::context::mk_enode(app*, bool, bool, bool) ../src/smt/smt_internalizer.cpp:947
    #4 0x10a8c47 in smt::theory_utvpi<smt::rdl_ext>::mk_num(app*, rational const&) ../src/smt/theory_utvpi_def.h:574
    #5 0x10a84e9 in smt::theory_utvpi<smt::rdl_ext>::mk_term(app*) ../src/smt/theory_utvpi_def.h:540
    #6 0x10a3182 in smt::theory_utvpi<smt::rdl_ext>::internalize_term(app*) ../src/smt/theory_utvpi_def.h:374
    #7 0xf31a6d in smt::context::internalize_theory_term(app*) ../src/smt/smt_internalizer.cpp:834
    #8 0xf30c43 in smt::context::internalize_term(app*) ../src/smt/smt_internalizer.cpp:773
    #9 0xf2cc1d in smt::context::internalize_rec(expr*, bool) ../src/smt/smt_internalizer.cpp:358
    #10 0xf2c553 in smt::context::internalize(expr*, bool, unsigned int) ../src/smt/smt_internalizer.cpp:323
    #11 0x124b525 in smt::model_checker::assert_new_instances() ../src/smt/smt_model_checker.cpp:609
    #12 0x124adaf in smt::model_checker::restart_eh() ../src/smt/smt_model_checker.cpp:576
    #13 0xfef0a9 in smt::default_qm_plugin::restart_eh() ../src/smt/smt_quantifier.cpp:698
    #14 0xfec97d in smt::quantifier_manager::imp::restart_eh() ../src/smt/smt_quantifier.cpp:312
    #15 0xfe9fd3 in smt::quantifier_manager::restart_eh() ../src/smt/smt_quantifier.cpp:468
    #16 0xee52c5 in smt::context::restart(lbool&, unsigned int) ../src/smt/smt_context.cpp:3674
    #17 0xee41b3 in smt::context::search() ../src/smt/smt_context.cpp:3605
    #18 0xee24c3 in smt::context::check(unsigned int, expr* const*, bool) ../src/smt/smt_context.cpp:3485
~~~~

Commit a02d3e9

**Comment by NikolajBjorner** [comment]
belongs to master branch
