### ISSUE TITLE
ctx-solver-simplify memory leak

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3284]
Hi, for the following formula
~~~~
(set-logic NRA)
(set-option :model_validate true)
(set-option :model true)
(set-option :rewriter.blast_distinct true)
(declare-const r0 Real)
(declare-const r6 Real)
(declare-const r9 Real)
(declare-const r10 Real)
(declare-const r11 Real)
(assert (or (distinct r10 (+ 4892973057.0 r6 (* r9 595627.0 r11 595627.0) r11) 6.849034153 r0 r9)))
(check-sat-using (then simplify ctx-solver-simplify))
~~~~
asan detects a memory leak
~~~~
   .....
    #15 0x127e3fe in smt::theory_arith<smt::mi_ext>::process_non_linear() ../src/smt/theory_arith_nl.h:2454
    #16 0x1239a6a in smt::theory_arith<smt::mi_ext>::final_check_core() ../src/smt/theory_arith_core.h:1485
    #17 0x123a1c6 in smt::theory_arith<smt::mi_ext>::final_check_eh() ../src/smt/theory_arith_core.h:1523
    #18 0xcfeaf9 in smt::context::final_check() ../src/smt/smt_context.cpp:3904
    #19 0xcfdb02 in smt::context::bounded_search() ../src/smt/smt_context.cpp:3819
    #20 0xcfb23d in smt::context::search() ../src/smt/smt_context.cpp:3646
    #21 0xcf97c5 in smt::context::check(unsigned int, expr* const*, bool) ../src/smt/smt_context.cpp:3531
    #22 0xcd42a6 in smt::kernel::imp::check(unsigned int, expr* const*) ../src/smt/smt_kernel.cpp:116
    #23 0xcd2e8b in smt::kernel::check(unsigned int, expr* const*) ../src/smt/smt_kernel.cpp:296
    #24 0xc46b9a in ctx_solver_simplify_tactic::simplify_bool(expr*, obj_ref<expr, ast_manager>&) (/home/rainoftime/Work/tofuzz/z3/build/z3+0xc46b9a)
    #25 0xc45f4f in ctx_solver_simplify_tactic::reduce(obj_ref<expr, ast_manager>&) (/home/rainoftime/Work/tofuzz/z3/build/z3+0xc45f4f)
    #26 0xc4485c in ctx_solver_simplify_tactic::reduce(goal&) (/home/rainoftime/Work/tofuzz/z3/build/z3+0xc4485c)
    #27 0xc4444b in ctx_solver_simplify_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) (/home/rainoftime/Work/tofuzz/z3/build/z3+0xc4444b)
    #28 0x19f385d in cleanup_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:909
    #29 0x19ec779 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120

**SUMMARY: AddressSanitizer: 35160 byte(s) leaked in 879 allocation(s).**
~~~~

Commit 6f2b569

**Comment by NikolajBjorner** [comment]
feel free to add pull request with fix.
