### ISSUE TITLE
rewriter.blast_distinct + ctx-solver-simplify memory leak

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3296]
Hi, for the following formula

[leak.txt](https://github.com/Z3Prover/z3/files/4332975/leak.txt)

asan detects a memory leak
~~~~
    #9 0x1cd4295 in interval_manager<dep_intervals::im_config>::mul(dep_intervals::im_config::interval const&, dep_intervals::im_config::interv
al const&, dep_intervals::im_config::interval&) ../src/math/interval/interval_def.h:1208
    #10 0x1c883c8 in dep_intervals::mul(dep_intervals::im_config::interval const&, dep_intervals::im_config::interval const&, dep_intervals::im
_config::interval&) ../src/math/interval/dep_intervals.h:199
    #11 0x1c9012c in dep_intervals::im_config::interval dd::pdd_interval::get_interval<(dep_intervals::with_deps_t)1>(dd::pdd const&) ../src/ma
th/dd/pdd_interval.h:60
    #12 0x1c7cc7e in nla::core::check_pdd_eq(dd::solver::equation const*) ../src/math/lp/nla_core.cpp:1497
    #13 0x1c7bc09 in nla::core::run_grobner() ../src/math/lp/nla_core.cpp:1408
    #14 0x1c7a587 in nla::core::inner_check(bool) ../src/math/lp/nla_core.cpp:1288
    #15 0x1c7ad7c in nla::core::check(old_vector<nla::lemma, true, unsigned int>&) ../src/math/lp/nla_core.cpp:1341
    #16 0x1c485b5 in nla::solver::check(old_vector<nla::lemma, true, unsigned int>&) ../src/math/lp/nla_solver.cpp:40
    #17 0x1097699 in smt::theory_lra::imp::check_nra() ../src/smt/theory_lra.cpp:2250
    #18 0x1090373 in smt::theory_lra::imp::final_check_eh() (/home/rainoftime/Work/tofuzz/z3/build/z3+0x1090373)
    #19 0x10773fa in smt::theory_lra::final_check_eh() ../src/smt/theory_lra.cpp:3971
    #20 0xcfeaf9 in smt::context::final_check() ../src/smt/smt_context.cpp:3904
    #21 0xcfdb02 in smt::context::bounded_search() ../src/smt/smt_context.cpp:3819
    #22 0xcfb23d in smt::context::search() ../src/smt/smt_context.cpp:3646
    #23 0xcf97c5 in smt::context::check(unsigned int, expr* const*, bool) ../src/smt/smt_context.cpp:3531
    #24 0xcd42a6 in smt::kernel::imp::check(unsigned int, expr* const*) ../src/smt/smt_kernel.cpp:116
    #25 0xcd2e8b in smt::kernel::check(unsigned int, expr* const*) ../src/smt/smt_kernel.cpp:296
    #26 0xc46b9a in ctx_solver_simplify_tactic::simplify_bool(expr*, obj_ref<expr, ast_manager>&) (/home/rainoftime/Work/tofuzz/z3/build/z3+0xc
46b9a)
    #27 0xc45f4f in ctx_solver_simplify_tactic::reduce(obj_ref<expr, ast_manager>&) 
+0xc4444b)
~~~~

The parameters are
~~~~
(set-option :model_validate true)
(set-option :model true)
(set-option :rewriter.blast_distinct true)
(set-option :smt.arith.solver 6)
....

(check-sat-using (then simplify qe-light ctx-solver-simplify))
~~~~

Commit: 6f2b569

**Comment by NikolajBjorner** [comment]
I can't take bugs against arith-solver = 6 in the master branch. This is what the debug branch is for.
Also, this leak was just fixed in the debug branch.

Note also: This is only a real memory leak in debug mode.
In release mode, the memory is maintained by small_object_allocator that, on Windows, prints a warning.
