### ISSUE TITLE
Memory leak at theory_arith_nl.h:1492

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3337]
Hi, for the following instance,
[leak.txt](https://github.com/Z3Prover/z3/files/4334408/leak.txt)

ASAN detects a memory leak issue in z3 master branch (Commit 894702d)
~~~~
Direct leak of 40 byte(s) in 1 object(s) allocated from:
  ....
    #9 0x1348eaf in smt::theory_arith<smt::inf_ext>::horner(unsigned int, old_sbuffer<std::pair<rational, expr*>, 16u>&, expr*) ../src/smt/theo
ry_arith_nl.h:1492
    #10 0x134a41d in smt::theory_arith<smt::inf_ext>::cross_nested(unsigned int, old_sbuffer<std::pair<rational, expr*>, 16u>&, expr*) ../src/s
mt/theory_arith_nl.h:1607
    #11 0x134aa58 in smt::theory_arith<smt::inf_ext>::is_cross_nested_consistent(old_sbuffer<std::pair<rational, expr*>, 16u>&) ../src/smt/theo
ry_arith_nl.h:1629
    #12 0x134ba78 in smt::theory_arith<smt::inf_ext>::is_cross_nested_consistent(smt::theory_arith<smt::inf_ext>::row const&) ../src/smt/theory
_arith_nl.h:1717
    #13 0x134bd8f in smt::theory_arith<smt::inf_ext>::is_cross_nested_consistent(old_svector<int, unsigned int> const&) ../src/smt/theory_arith
_nl.h:1731
    #14 0x1357e90 in smt::theory_arith<smt::inf_ext>::process_non_linear() ../src/smt/theory_arith_nl.h:2454
    #15 0x13129d6 in smt::theory_arith<smt::inf_ext>::final_check_core() ../src/smt/theory_arith_core.h:1485
    #16 0x1313132 in smt::theory_arith<smt::inf_ext>::final_check_eh() ../src/smt/theory_arith_core.h:1523
    #17 0xcfdf7d in smt::context::final_check() ../src/smt/smt_context.cpp:3904
    #18 0xcfcf86 in smt::context::bounded_search() ../src/smt/smt_context.cpp:3819
    #19 0xcfa6c1 in smt::context::search() ../src/smt/smt_context.cpp:3646
    #20 0xcf80bc in smt::context::setup_and_check(bool) ../src/smt/smt_context.cpp:3471
    #21 0xcd3690 in smt::kernel::imp::setup_and_check() ../src/smt/smt_kernel.cpp:108
    #22 0xcd226f in smt::kernel::setup_and_check() ../src/smt/smt_kernel.cpp:292
    #23 0x5a53e8 in opt::opt_solver::check_sat_core2(unsigned int, expr* const*) ../src/opt/opt_solver.cpp:183
    #24 0x197e6b7 in solver_na2as::check_sat_core(unsigned int, expr* const*) ../src/solver/solver_na2as.cpp:67
    #25 0x1976745 in solver::check_sat(unsigned int, expr* const*) ../src/solver/solver.cpp:330
    #26 0x57a480 in opt::context::optimize(ref_vector<expr, ast_manager> const&) ../src/opt/opt_context.cpp:300
    #27 0x192d877 in cmd_context::check_sat(unsigned int, expr* const*) ../src/cmd_context/cmd_context.cpp:1557
    #28 0x18bc469 in smt2::parser::parse_check_sat() ../src/parsers/smt2/smt2parser.cpp:2596
    #29 0x18c0405 in smt2::parser::parse_cmd() ../src/parsers/smt2/smt2parser.cpp:2938
~~~~

**Comment by rainoftime** [comment]
Here is another instance "72960 byte(s) leaked in 1824 allocation(s)."
[leak2.txt](https://github.com/Z3Prover/z3/files/4334448/leak2.txt)
