### ISSUE TITLE
Memory leak for QF_LRA instance

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3503]
Hi, for the following instance, when executing 
~~~
./z3 timeout=5000 fname.smt2
~~~
asan detects a memory leak in z3 (Commit 41c68d6) 

~~~~
(set-logic QF_LRA)
(set-option :model_validate true)
(set-option :model true)
(declare-const v0 Bool)
(declare-const v1 Bool)
(declare-const v2 Bool)
(declare-const v3 Bool)
(declare-const v4 Bool)
(declare-const r1 Real)
(declare-const r2 Real)
(declare-const r3 Real)
(declare-const r4 Real)
(declare-const r6 Real)
(declare-const r10 Real)
(declare-const r11 Real)
(assert-soft (not v0))
(assert v0)
(declare-const v7 Bool)
(assert v1)
(declare-const v8 Bool)
(assert v3)
(declare-const v9 Bool)
(assert-soft (=> v0 (not v0)))
(declare-const r15 Real)
(declare-const v10 Bool)
(assert-soft (distinct v0 v3 (=> v4 (xor (> (* r11 0.906306328 561710254.0 r4 r10) r10 r6) v0 v1 (> r1 r3 r11 r4) (not v0))) v8 v3))
(declare-const v11 Bool)
(assert v1)
(assert-soft (> (* r11 0.906306328 561710254.0 r4 r10) r10 r6))
(assert-soft v1)
(assert-soft v9)
(check-sat)
~~~~

~~~~
=================================================================
==127230==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 680 byte(s) in 17 object(s) allocated from:
    #0 0x7effd1cb0602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x254ced9 in memory::allocate(unsigned long) ../src/util/memory_manager.cpp:268
    #2 0x257cea9 in small_object_allocator::allocate(unsigned long) ../src/util/small_object_allocator.cpp:103
    #3 0x25950a5 in mpz_manager<false>::allocate(unsigned int) ../src/util/mpz.cpp:198
    #4 0x259780d in mpz_manager<false>::big_set(mpz&, mpz const&) ../src/util/mpz.cpp:1497
    #5 0x562083 in mpz_manager<false>::set(mpz&, mpz const&) ../src/util/mpz.h:530
    #6 0x563ab8 in mpq_manager<false>::set(mpz&, mpz const&) ../src/util/mpq.h:653
    #7 0x563689 in mpq_manager<false>::set(mpq&, mpq const&) ../src/util/mpq.h:657
    #8 0x1e1303a in dep_intervals::im_config::set_upper(dep_intervals::im_config::interval&, mpq const&) const ../src/math/interval/dep_intervals.h:93
    #9 0x1e13440 in dep_intervals::set_upper(dep_intervals::im_config::interval&, rational const&) const ../src/math/interval/dep_intervals.h:188
    #10 0x23f3485 in dep_intervals::set_interval_for_scalar(dep_intervals::im_config::interval&, rational const&) ../src/math/interval/dep_intervals.cpp:31
    #11 0x1d91c4b in dep_intervals::im_config::interval dd::pdd_interval::get_interval<(dep_intervals::with_deps_t)1>(dd::pdd const&) ../src/math/dd/pdd_interval.h:42
    #12 0x1d91ce5 in dep_intervals::im_config::interval dd::pdd_interval::get_interval<(dep_intervals::with_deps_t)1>(dd::pdd const&) ../src/math/dd/pdd_interval.h:47
    #13 0x1d91d2e in dep_intervals::im_config::interval dd::pdd_interval::get_interval<(dep_intervals::with_deps_t)1>(dd::pdd const&) ../src/math/dd/pdd_interval.h:48
    #14 0x1d91d2e in dep_intervals::im_config::interval dd::pdd_interval::get_interval<(dep_intervals::with_deps_t)1>(dd::pdd const&) ../src/math/dd/pdd_interval.h:48
    #15 0x1d91d2e in dep_intervals::im_config::interval dd::pdd_interval::get_interval<(dep_intervals::with_deps_t)1>(dd::pdd const&) ../src/math/dd/pdd_interval.h:48
    #16 0x1d80440 in nla::core::check_pdd_eq(dd::solver::equation const*) ../src/math/lp/nla_core.cpp:1497
    #17 0x1d7f3cb in nla::core::run_grobner() ../src/math/lp/nla_core.cpp:1408
    #18 0x1d7dd49 in nla::core::inner_check(bool) ../src/math/lp/nla_core.cpp:1288
    #19 0x1d7e53e in nla::core::check(old_vector<nla::lemma, true, unsigned int>&) ../src/math/lp/nla_core.cpp:1341
    #20 0x1c7bed3 in nla::solver::check(old_vector<nla::lemma, true, unsigned int>&) ../src/math/lp/nla_solver.cpp:40
    #21 0x1190ec7 in smt::theory_lra::imp::check_nra() ../src/smt/theory_lra.cpp:2252
    #22 0x1189ba1 in smt::theory_lra::imp::final_check_eh() ../src/smt/theory_lra.cpp:1753
    #23 0x11716c2 in smt::theory_lra::final_check_eh() ../src/smt/theory_lra.cpp:3976
    #24 0xf8bc35 in smt::context::final_check() ../src/smt/smt_context.cpp:3907
    #25 0xf8ac3e in smt::context::bounded_search() ../src/smt/smt_context.cpp:3823
    #26 0xf88379 in smt::context::search() ../src/smt/smt_context.cpp:3650
    #27 0xf85d74 in smt::context::setup_and_check(bool) ../src/smt/smt_context.cpp:3475
    #28 0xd04bea in smt::kernel::imp::setup_and_check() ../src/smt/smt_kernel.cpp:108
    #29 0xd03805 in smt::kernel::setup_and_check() ../src/smt/smt_kernel.cpp:292
~~~~

**Comment by NikolajBjorner** [comment]
this is a debug mode only leak, which is fixed in debug branch.
