### ISSUE TITLE
heap-buffer-overflow for QF_NRA instance

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3610]
Hi, for the following formula
~~~~
(set-logic QF_NRA)
(set-option :trace true)
(set-option :parallel.enable true)
(declare-const v0 Bool)
(declare-const v3 Bool)
(declare-const v5 Bool)
(declare-const v8 Bool)
(declare-const v13 Bool)
(declare-const r0 Real)
(declare-const r1 Real)
(declare-const r2 Real)
(declare-const r3 Real)
(declare-const r5 Real)
(declare-const r6 Real)
(declare-const v16 Bool)
(assert (or (<= (+ r0 r2 r2 (- r1) r3) r0 r2 (* r0 r1 r2))))
(assert (or (= r6 66991.0 r2 r3)))
(assert (or v16 v8 (= r6 66991.0 r2 r3)))
(assert (or (xor v8 (=> v3 (< r0 r2 r0)) (= r0 r1 r2 (- r1) r3) v0 v5 (distinct r2 r2) v13) v16))
(check-sat-using (then simplify qfuf))
~~~~

z3 commit cf0952c throws a heap-buffer-overflow
~~~~
=================================================================
==47754==AddressSanitizer: while reporting a bug found another one. Ignoring.
==47754==AddressSanitizer: while reporting a bug found another one. Ignoring.
==47754==AddressSanitizer: while reporting a bug found another one. Ignoring.
==47754==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x625000007100 at pc 0x7f65c489ca5a bp 0x7f65c08c1e00 sp 0x7f65c08c15a8
READ of size 8196 at 0x625000007100 thread T2
==47754==AddressSanitizer: while reporting a bug found another one. Ignoring.
==47754==AddressSanitizer: while reporting a bug found another one. Ignoring.
    #0 0x7f65c489ca59  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x46a59)
    #1 0x7f65c489cdec in writev (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x46dec)
    #2 0x7f65c431cf55 in std::__basic_file<char>::xsputn_2(char const*, long, char const*, long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xc6f55)
    #3 0x7f65c435a19d in std::basic_filebuf<char, std::char_traits<char> >::xsputn(char const*, long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x10419d)
    #4 0x7f65c43750f7 in std::ostreambuf_iterator<char, std::char_traits<char> > std::num_put<char, std::ostreambuf_iterator<char, std::char_traits<char> > >::_M_insert_int<unsigned long>(std::ostreambuf_
iterator<char, std::char_traits<char> >, std::ios_base&, char, unsigned long) const (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x11f0f7)
    #5 0x7f65c4382b65 in std::ostream& std::ostream::_M_insert<unsigned long>(unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x12cb65)
    #6 0x21de0d0 in ast_manager::mk_app_core(func_decl*, unsigned int, expr* const*) ../src/ast/ast.cpp:2273
    #7 0x21df0b4 in ast_manager::mk_app(func_decl*, unsigned int, expr* const*) ../src/ast/ast.cpp:2362
    #8 0x213be67 in format_ns::flat_visitor::visit(app*, app* const*) ../src/ast/format.cpp:137
    #9 0x213c47a in recurse_expr<app*, format_ns::flat_visitor, true, true>::process(expr*) ../src/ast/recurse_expr_def.h:68
    #10 0x213c06b in recurse_expr<app*, format_ns::flat_visitor, true, true>::operator()(expr*) ../src/ast/recurse_expr_def.h:103
    #11 0x213a2a0 in format_ns::flat(ast_manager&, app*) ../src/ast/format.cpp:144
    #12 0x213aaa6 in format_ns::mk_group(ast_manager&, app*) ../src/ast/format.cpp:180
    #13 0x221f8ca in smt2_printer::process_app(app*, smt2_printer::frame&) ../src/ast/ast_smt2_pp.cpp:781
    #14 0x2223322 in smt2_printer::process(expr*, obj_ref<app, ast_manager>&) ../src/ast/ast_smt2_pp.cpp:1060
    #15 0x2223f89 in smt2_printer::operator()(expr*, unsigned int, char const*, obj_ref<app, ast_manager>&, old_sbuffer<symbol, 16u>&) ../src/ast/ast_smt2_pp.cpp:1125
    #16 0x22180e3 in mk_smt2_format(expr*, smt2_pp_environment&, params_ref const&, unsigned int, char const*, obj_ref<app, ast_manager>&, old_sbuffer<symbol, 16u>&) ../src/ast/ast_smt2_pp.cpp:1201
    #17 0x2218dc8 in ast_smt2_pp(std::ostream&, expr*, smt2_pp_environment&, params_ref const&, unsigned int, unsigned int, char const*) ../src/ast/ast_smt2_pp.cpp:1240
    #18 0x221a792 in operator<<(std::ostream&, mk_ismt2_pp const&) ../src/ast/ast_smt2_pp.cpp:1341
    #19 0x107599e in smt::context::display_literal_smt2(std::ostream&, smt::literal) const ../src/smt/smt_context_pp.cpp:108
    #20 0x1075a5c in smt::context::display_literals_smt2(std::ostream&, unsigned int, smt::literal const*) const ../src/smt/smt_context_pp.cpp:114
    #21 0x107b06c in smt::context::display(std::ostream&, smt::b_justification) const ../src/smt/smt_context_pp.cpp:604
    #22 0x107b3a0 in smt::context::trace_assign(smt::literal, smt::b_justification, bool) const ../src/smt/smt_context_pp.cpp:629
    #23 0xf669b7 in smt::context::assign_core(smt::literal, smt::b_justification, bool) ../src/smt/smt_context.cpp:345
    #24 0xf67935 in smt::context::bcp() ../src/smt/smt_context.cpp:445
    #25 0xf74aae in smt::context::propagate() ../src/smt/smt_context.cpp:1726
    #26 0x11003cc in smt::lookahead::choose() ../src/smt/smt_lookahead.cpp:107
    #27 0xd04db3 in smt::kernel::imp::next_cube() ../src/smt/smt_kernel.cpp:193
    #28 0xd03c25 in smt::kernel::next_cube() ../src/smt/smt_kernel.cpp:367
    #29 0x109bb83 in cube ../src/smt/smt_solver.cpp:45
    #30 0x109e2e0 in cube ../src/smt/smt_solver.cpp:288
    #31 0x1974f1f in parallel_tactic::cube_and_conquer(parallel_tactic::solver_state&) ../src/solver/parallel_tactic.cpp:486
    #32 0x1975fbd in parallel_tactic::run_solver() ../src/solver/parallel_tactic.cpp:614
    #33 0x1976695 in parallel_tactic::solve(ref<model>&)::{lambda()#1}::operator()() const (/home/peisen/test/tofuzz/z3-debug/build/z3+0x1976695)
    #34 0x197c649 in void std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) /usr/include/c++/5/functional:1531
    #35 0x197c55d in std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()>::operator()() /usr/include/c++/5/functional:1520
    #36 0x197c4ed in std::thread::_Impl<std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()> >::_M_run() /usr/include/c++/5/thread:115
    #37 0x7f65c4326b8d  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0b8d)
    #38 0x7f65c46406b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #39 0x7f65c3a7241c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)

~~~~

**Comment by NikolajBjorner** [comment]
trace + anything multi-threaded is not going to work. Users of "trace" would have to temper their use in order to get meaningful proof traces.
