### ISSUE TITLE
local search segment fault  at ast.h:504

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3639]
Hi, for the following formula,
~~~~
(set-logic QF_BV)
(set-option :parallel.enable true)
(set-option :sat.local_search true)
(set-option :sat.xor.solver true)
(declare-const bv_16-0 (_ BitVec 16))
(assert (= (bvshl bv_16-0 bv_16-0) (bvsrem bv_16-0 bv_16-0) bv_16-0 bv_16-0))
(check-sat)
~~~~

asan detects a SEGV in z3 (commit 1d6fb63)
~~~~
==79811==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000004 (pc 0x000000467c2b bp 0x7fdaf395d8c0 sp 0x7fdaf395d8b0 T2)
ASAN:SIGSEGV
==79811==AddressSanitizer: while reporting a bug found another one. Ignoring.
    #0 0x467c2a in ast::get_kind() const ../src/ast/ast.h:504
    #1 0x468098 in is_uninterp_const(expr const*) ../src/ast/ast.h:1375
    #2 0xaacafd in inc_sat_solver::is_literal(expr*) (/home/peisen/test/tofuzz/z3-debug/build/z3+0xaacafd)
    #3 0xaacb86 in inc_sat_solver::is_clause(expr*) (/home/peisen/test/tofuzz/z3-debug/build/z3+0xaacb86)
    #4 0xaa6462 in inc_sat_solver::assert_expr_core(expr*) ../src/sat/sat_solver/inc_sat_solver.cpp:298
    #5 0x19681cc in solver::assert_expr(expr*) ../src/solver/solver.cpp:210
    #6 0x4687f8 in solver::assert_expr(ref_vector<expr, ast_manager> const&) ../src/solver/solver.h:109
    #7 0x197912f in parallel_tactic::solver_state::assert_cube(ref_vector<expr, ast_manager> const&) ../src/solver/parallel_tactic.cpp:279
    #8 0x197b72c in parallel_tactic::cube_and_conquer(parallel_tactic::solver_state&) ../src/solver/parallel_tactic.cpp:464
    #9 0x197ca23 in parallel_tactic::run_solver() ../src/solver/parallel_tactic.cpp:621
    #10 0x197d0fb in parallel_tactic::solve(ref<model>&)::{lambda()#1}::operator()() const (/home/peisen/test/tofuzz/z3-debug/build/z3+0x197d0fb)
    #11 0x19831a3 in void std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) /usr/include/c++/5/functional:1531
    #12 0x19830b7 in std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()>::operator()() /usr/include/c++/5/functional:1520
    #13 0x1983047 in std::thread::_Impl<std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()> >::_M_run() /usr/include/c++/5/thread:115
    #14 0x7fdaf7481b8d  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0b8d)
    #15 0x7fdaf779b6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #16 0x7fdaf6bcd41c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)
~~~~

**Comment by rainoftime** [comment]
According to https://github.com/Z3Prover/z3/issues/3636, "local search with parallel.enable aren't compatible".
@NikolajBjorner  Seems that the commit https://github.com/Z3Prover/z3/commit/79183b6339fd48cf6e984edd6f2938defde64ec7 code does not capture the conflict.
