### ISSUE TITLE
seg fault for QF_BV instance

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3692]
Hi, for the following formula,
[sat.txt](https://github.com/Z3Prover/z3/files/4419468/sat.txt)

z3 b686bb61fed28 throws an error
~~~~
==96618==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000004 (pc 0x000000467c2b bp 0x7fcdb082f8c0 sp 0x7fcdb082f8b0 T24)
ASAN:SIGSEGV
==96618==AddressSanitizer: while reporting a bug found another one. Ignoring.
    #0 0x467c2a in ast::get_kind() const ../src/ast/ast.h:504
    #1 0x468098 in is_uninterp_const(expr const*) ../src/ast/ast.h:1375
    #2 0xab0969 in inc_sat_solver::is_literal(expr*) (/home/peisen/test/tofuzz/z3-debug/build/z3+0xab0969)
    #3 0xab09f2 in inc_sat_solver::is_clause(expr*) (/home/peisen/test/tofuzz/z3-debug/build/z3+0xab09f2)
    #4 0xaaa2ce in inc_sat_solver::assert_expr_core(expr*) ../src/sat/sat_solver/inc_sat_solver.cpp:298
    #5 0x197aa2e in solver::assert_expr(expr*) ../src/solver/solver.cpp:210
    #6 0x4687f8 in solver::assert_expr(ref_vector<expr, ast_manager> const&) ../src/solver/solver.h:109
    #7 0x198b991 in parallel_tactic::solver_state::assert_cube(ref_vector<expr, ast_manager> const&) ../src/solver/parallel_tactic.cpp:279
    #8 0x198df8e in parallel_tactic::cube_and_conquer(parallel_tactic::solver_state&) ../src/solver/parallel_tactic.cpp:464
    #9 0x198f285 in parallel_tactic::run_solver() ../src/solver/parallel_tactic.cpp:621
    #10 0x198f95d in parallel_tactic::solve(ref<model>&)::{lambda()#1}::operator()() const (/home/peisen/test/tofuzz/z3-debug/build/z3+0x198f95d)
    #11 0x1995a05 in void std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) /usr/include/c++/5/functional:1531
    #12 0x1995919 in std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()>::operator()() /usr/include/c++/5/functional:1520
    #13 0x19958a9 in std::thread::_Impl<std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()> >::_M_run() /usr/include/c++/5/thread:115
    #14 0x7fcdbf582b8d  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0b8d)
    #15 0x7fcdbf89c6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #16 0x7fcdbecce41c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/ast/ast.h:504 ast::get_kind() const
Thread T24 created by T0 here:
    #0 0x7fcdbfae81e3 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x361e3)
    #1 0x7fcdbf582c93 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0c93)
~~~~

~~~~
(set-logic QF_BV)
(set-option :parallel.enable true)
(set-option :sat.local_search true)
(set-option :sat.xor.solver true)
~~~~

**Comment by rainoftime** [comment]
To https://github.com/Z3Prover/z3/issues/3694

**Comment by rainoftime** [comment]
Fixed
