### ISSUE TITLE
Memory leak for QF_ANIA instance (unsat_core + arith.solver 6)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3702]
Related issue: https://github.com/Z3Prover/z3/issues/3638

----

Hi, for the following formula,
~~~~
(set-logic QF_ANIA)
(set-option :unsat_core true)
(set-option :smt.arith.solver 6)
(declare-const i0 Int)
(declare-const i1 Int)
(declare-const i2 Int)
(declare-const i9 Int)
(declare-const i13 Int)
(declare-const i14 Int)
(assert (! (< i14 (* (* 79 (+ i14 i0 i2 44) 67 i9 636) i1 i13 97 74)) :named IP_48))
(check-sat)
~~~~

z3 b686bb61fed throws a leak
~~~~
==6666==ERROR: LeakSanitizer: detected memory leaks                                                                                                                                               [550/1545]

Direct leak of 80 byte(s) in 2 object(s) allocated from:
    #0 0x7f6b436c1662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x257357f in memory::allocate(unsigned long) ../src/util/memory_manager.cpp:268
    #2 0x25a354f in small_object_allocator::allocate(unsigned long) ../src/util/small_object_allocator.cpp:103
    #3 0x25bb6eb in mpz_manager<false>::allocate(unsigned int) ../src/util/mpz.cpp:198
    #4 0x25c729f in mpz_manager<false>::set_digits(mpz&, unsigned int, unsigned int const*) ../src/util/mpz.cpp:455
    #5 0x25bc7ac in mpz_manager<false>::set(mpz_cell&, mpz&, int, unsigned int) ../src/util/mpz.cpp:410
    #6 0x25cf52c in void mpz_manager<false>::big_add_sub<false>(mpz const&, mpz const&, mpz&) ../src/util/mpz.cpp:701
    #7 0x25bd91f in mpz_manager<false>::big_add(mpz const&, mpz const&, mpz&) ../src/util/mpz.cpp:746
    #8 0x25bf225 in mpz_manager<false>::add(mpz const&, mpz const&, mpz&) ../src/util/mpz.cpp:249
    #9 0xd7c675 in mpq_manager<false>::add(mpq const&, mpq const&, mpq&) ../src/util/mpq.h:235
    #10 0x1e3da68 in void add<mpq_manager<false> >(mpq_manager<false>&, mpq_manager<false>::numeral const&, ext_numeral_kind, mpq_manager<false>::numeral const&, ext_numeral_kind, mpq_manager<false>::nume
ral&, ext_numeral_kind&) ../src/util/ext_numeral.h:126
    #11 0x1e3b2fc in interval_manager<dep_intervals::im_config>::add(dep_intervals::im_config::interval const&, dep_intervals::im_config::interval const&, dep_intervals::im_config::interval&) ../src/math/
interval/interval_def.h:812
    #12 0x1dad510 in dep_intervals::add(dep_intervals::im_config::interval const&, dep_intervals::im_config::interval const&, dep_intervals::im_config::interval&) ../src/math/interval/dep_intervals.h:200
    #13 0x1e42894 in dep_intervals::im_config::interval nla::intervals::interval_of_sum_no_term<(dep_intervals::with_deps_t)1>(nla::nex_sum const&) (/home/peisen/test/tofuzz/z3-debug/build/z3+0x1e42894)
    #14 0x1e3e129 in dep_intervals::im_config::interval nla::intervals::interval_of_sum<(dep_intervals::with_deps_t)1>(nla::nex_sum const&) ../src/math/lp/nla_intervals.cpp:337
    #15 0x1e3ba32 in dep_intervals::im_config::interval nla::intervals::interval_of_expr<(dep_intervals::with_deps_t)1>(nla::nex const*, unsigned int) ../src/math/lp/nla_intervals.cpp:402
    #16 0x1e42728 in dep_intervals::im_config::interval nla::intervals::interval_of_sum_no_term<(dep_intervals::with_deps_t)1>(nla::nex_sum const&) (/home/peisen/test/tofuzz/z3-debug/build/z3+0x1e42728)
    #17 0x1e3e129 in dep_intervals::im_config::interval nla::intervals::interval_of_sum<(dep_intervals::with_deps_t)1>(nla::nex_sum const&) ../src/math/lp/nla_intervals.cpp:337
    #18 0x1e3ba32 in dep_intervals::im_config::interval nla::intervals::interval_of_expr<(dep_intervals::with_deps_t)1>(nla::nex const*, unsigned int) ../src/math/lp/nla_intervals.cpp:402
    #19 0x1e3540a in nla::intervals::check_nex(nla::nex const*, dependency_manager<scoped_dependency_manager<unsigned int>::config>::dependency*) ../src/math/lp/nla_intervals.cpp:75
~~~~

**Comment by NikolajBjorner** [comment]
see #3638
