### ISSUE TITLE
Memory leak for "ALL" formula (arith.solver 1)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#3945]
~~~~
(set-logic ALL)
(set-option :smt.arith.solver 1)
(declare-const v0 Bool)
(declare-const i0 Int)
(declare-const r3 Real)
(assert (forall ((q4 (Array (Array Real Bool) Real))) (distinct i0 89)))
(assert (or (<= 7.6 r3)))
(assert-soft (or v0 (<= 7.6 r3) (<= 7.6 r3) v0 v0 (<= 7.6 r3) v0 (<= 7.6 r3) (<= 7.6 r3)))
(check-sat)
~~~~
z3 01c12c9 throws a memory leak.
~~~~
(error "line 9 column 10: invalid rational value passed as an integer")                                                                                                                            

=================================================================
==67462==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 2 object(s) allocated from:
    #0 0x7efdbebfe662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x25f0351 in memory::allocate(unsigned long) ../src/util/memory_manager.cpp:268
    #2 0x25efe74 in memory::allocate(char const*, int, char const*, unsigned long) ../src/util/memory_manager.cpp:207
    #3 0xd5deb7 in smt::theory_diff_logic<smt::rdl_ext>::mk_value(smt::enode*, smt::model_generator&) (/home/peisen/test/tofuzz/z3-debug/build/z3+0xd5deb7)
    #4 0x11203ad in smt::model_generator::mk_value_procs(obj_map<smt::enode, smt::model_value_proc*>&, old_ptr_vector<smt::enode>&, old_ptr_vector<smt::model_value_proc>&) ../src/smt/smt_model_generator.c
pp:113
    #5 0x11229d9 in smt::model_generator::mk_values() ../src/smt/smt_model_generator.cpp:297
    #6 0x1125ee7 in smt::model_generator::mk_model() ../src/smt/smt_model_generator.cpp:500
    #7 0xfca8c4 in smt::context::mk_proto_model() ../src/smt/smt_context.cpp:4441
    #8 0xfcaf11 in smt::context::get_model(ref<model>&) ../src/smt/smt_context.cpp:4472
    #9 0xd349be in smt::kernel::imp::get_model(ref<model>&) ../src/smt/smt_kernel.cpp:136
    #10 0xd33792 in smt::kernel::get_model(ref<model>&) ../src/smt/smt_kernel.cpp:319
    #11 0x5c5483 in opt::opt_solver::check_sat_core2(unsigned int, expr* const*) ../src/opt/opt_solver.cpp:190
    #12 0x19e02db in solver_na2as::check_sat_core(unsigned int, expr* const*) ../src/solver/solver_na2as.cpp:67
    #13 0x19e4345 in solver::check_sat(unsigned int, expr* const*) ../src/solver/solver.cpp:330
    #14 0x57b65a in opt::context::optimize(ref_vector<expr, ast_manager> const&) ../src/opt/opt_context.cpp:301
    #15 0x199c977 in cmd_context::check_sat(unsigned int, expr* const*) ../src/cmd_context/cmd_context.cpp:1527
    #16 0x192d403 in smt2::parser::parse_check_sat() ../src/parsers/smt2/smt2parser.cpp:2596
    #17 0x193139f in smt2::parser::parse_cmd() ../src/parsers/smt2/smt2parser.cpp:2938
~~~~

**Comment by rainoftime** [comment]
Seems the formula are not outside the scope of diff logic
