### ISSUE TITLE
something wrong with python binding ?

### ISSUE THREAD

**Issue by numairmansur** [Z3Prover/z3#3947]
Hi,
I think something is wrong with the python wrapper.
On doing
`from z3Build.z3Python.z3 import *`

I now get:
```
Traceback (most recent call last):
  File "testZ3.py", line 1, in <module>
    from z3Build.z3Python.z3 import *
  File "/home/numair/z3Build/z3Python/z3/__init__.py", line 1, in <module>
    from .z3 import *
  File "/home/numair/z3Build/z3Python/z3/z3.py", line 43, in <module>
    from . import z3core
  File "/home/numair/z3Build/z3Python/z3/z3core.py", line 182, in <module>
    _lib.Z3_mk_rec_func_decl.restype = FuncDecl
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/libz3.so: undefined symbol: Z3_mk_rec_func_decl
```
It used to work perfectly fine for me. I am not sure what commit introduced this.

OS: 16.04.6 LTS (Xenial Xerus)

Can you confirm, or is something wrong with my system. Although I did not do anything new, just updated z3.

**Comment by NikolajBjorner** [comment]
maybe your have incompatible versions of z3 in the install path?

**Comment by numairmansur** [comment]
Ah that's right ! Thank you !
