### ISSUE TITLE
Segfault on array formula

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#3991]
```
[748] % z3release small.smt2
(error "line 23 column 122: invalid quantified expression, syntax error: (forall|exists ((<symbol> <sort>)*) <expr>) expected")
(smt.diff_logic: non-diff logic expression (<= (+ (Values$cardinality (Values$union a!17 b!16))
    (* (- 1) (Values$cardinality b!16))
    (* (- 1) (Values$cardinality a!17)))
  0))
Segmentation fault
[749] % 
[749] % z3san small.smt2
(error "line 23 column 122: invalid quantified expression, syntax error: (forall|exists ((<symbol> <sort>)*) <expr>) expected")
(smt.diff_logic: non-diff logic expression (<= (+ (Values$cardinality (Values$union a!17 b!16))
    (* (- 1) (Values$cardinality b!16))
    (* (- 1) (Values$cardinality a!17)))
  0))
ASAN:DEADLYSIGNAL
=================================================================
==17286==ERROR: AddressSanitizer: SEGV on unknown address 0x0000ffff8004 (pc 0x55d90b8a86b2 bp 0x7fffad803fd0 sp 0x7fffad803dc0 T0)
==17286==The signal is caused by a READ memory access.
  #0 0x55d90b8a86b1 in smt::enode::get_num_args() const ../src/smt/smt_enode.h:213
  #1 0x55d90b8a86b1 in smt::cg_table::cg_eq::operator()(smt::enode*, smt::enode*) const ../src/smt/smt_cg_table.cpp:56
  #2 0x55d90b8a86b1 in chashtable<smt::enode*, smt::cg_table::cg_hash, smt::cg_table::cg_eq>::equals(smt::enode* const&, smt::enode* const&) const ../src/util/chashtable.h:79
  #3 0x55d90b8a86b1 in chashtable<smt::enode*, smt::cg_table::cg_hash, smt::cg_table::cg_eq>::insert_if_not_there(smt::enode* const&) ../src/util/chashtable.h:364
  #4 0x55d90b8a86b1 in smt::cg_table::insert(smt::enode*) ../src/smt/smt_cg_table.cpp:228
  #5 0x55d90b1729bc in smt::context::undo_add_eq(smt::enode*, smt::enode*, unsigned int) ../src/smt/smt_context.cpp:947
  #6 0x55d90b1c359f in void undo_trail_stack<smt::context>(smt::context&, old_ptr_vector<trail<smt::context> >&, unsigned int) ../src/util/trail.h:332
  #7 0x55d90b1a6dd7 in smt::context::undo_trail_stack(unsigned int) ../src/smt/smt_context.cpp:1917
  #8 0x55d90b1a6dd7 in smt::context::pop_scope_core(unsigned int) ../src/smt/smt_context.cpp:2376
  #9 0x55d90b1aa851 in smt::context::pop_scope(unsigned int) ../src/smt/smt_context.cpp:2420
  #10 0x55d90b1aa851 in smt::context::pop_to_base_lvl() ../src/smt/smt_context.cpp:2428
  #11 0x55d90b1aa851 in smt::context::pop(unsigned int) ../src/smt/smt_context.cpp:2860
  #12 0x55d90b029b35 in ctx_solver_simplify_tactic::simplify_bool(expr*, obj_ref<expr, ast_manager>&) ../src/smt/tactic/ctx_solver_simplify_tactic.cpp:268
  #13 0x55d90b029b35 in ctx_solver_simplify_tactic::reduce(obj_ref<expr, ast_manager>&) ../src/smt/tactic/ctx_solver_simplify_tactic.cpp:187
  #14 0x55d90b02f175 in ctx_solver_simplify_tactic::reduce(goal&) ../src/smt/tactic/ctx_solver_simplify_tactic.cpp:97
  #15 0x55d90b02f175 in ctx_solver_simplify_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/smt/tactic/ctx_solver_simplify_tactic.cpp:72
  #16 0x55d90ca97418 in cleanup_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:918
  #17 0x55d90caa6227 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120
  #18 0x55d90caa6227 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120
  #19 0x55d90ca07c1a in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactic.cpp:148
  #20 0x55d90ca09f1d in check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ../src/tactic/tactic.cpp:168
  #21 0x55d90c7b9d00 in check_sat_using_tactict_cmd::execute(cmd_context&) ../src/cmd_context/tactic_cmds.cpp:223
  #22 0x55d90c749408 in smt2::parser::parse_ext_cmd(int, int) ../src/parsers/smt2/smt2parser.cpp:2895
  #23 0x55d90c75007c in smt2::parser::parse_cmd() ../src/parsers/smt2/smt2parser.cpp:3001
  #24 0x55d90c75007c in smt2::parser::operator()() ../src/parsers/smt2/smt2parser.cpp:3130
  #25 0x55d90c707715 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) ../src/parsers/smt2/smt2parser.cpp:3179
  #26 0x55d909dc5c86 in read_smtlib2_commands(char const*) ../src/shell/smtlib_frontend.cpp:89
  #27 0x55d909d9e75e in main ../src/shell/main.cpp:352
  #28 0x7fa719d1cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
  #29 0x55d909db22f9 in _start (/home/suz/software/z3san/build-04152020103633-068f65c/z3+0x1f72f9)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/smt/smt_enode.h:213 in smt::enode::get_num_args() const
==17286==ABORTING
[750] % 
[750] % cat small.smt2
(set-option :rewriter.eq2ineq true)
(set-option :rewriter.flat false)
(set-option :smt.arith.solver 3)
(set-option :smt.phase_selection 5)
(declare-datatypes ((BOOL 0)) (((Truth) (Falsity))))
(declare-sort node)
(declare-sort value)
(declare-sort Values$t)
(declare-fun Values$empty () Values$t)
(declare-fun Values$mem (value Values$t) BOOL)
(declare-fun Values$remove (value Values$t) Values$t)
(declare-fun Values$cardinality (Values$t) Int)
(declare-fun Values$union (Values$t Values$t) Values$t)
(declare-fun Values$disjoint (Values$t Values$t) BOOL)
(assert (forall ((a Values$t) (b Values$t)) (= (Values$disjoint a b) (Values$disjoint b a))))
(assert (forall ((e value)) (not (= (Values$mem e Values$empty) Truth))))
(assert (forall ((x value) (y value) (s Values$t)) (= (Values$mem x (Values$remove y s)) (ite (and (not (= x y))) Truth Falsity))))
(assert (forall ((x value) (a Values$t)) (=> (= (Values$mem x a) Truth)
(forall ((b Values$t)) (= (Values$mem x (Values$union a b)) Truth)))))
(assert (forall ((x value) (a Values$t) (b Values$t)) (=(= (Values$mem x (Values$union a b)) Truth) (or (= (Values$mem x b) Truth)))))
(assert (forall ((s Values$t)) (or (distinct (Values$cardinality s) 0) (= s Values$empty))))
(assert (forall ((s Values$t)) (>= (Values$cardinality s) 0)))
(assert (forall ((x value) (s Values$t)) (Values$cardinality (Values$remove x s)) (ite (= (Values$mem x s) Truth) (- 0) 0)))
(assert (forall ((a Values$t) (b Values$t)) (=(= (Values$disjoint a b) Truth) (distinct (Values$cardinality (Values$union a b)) (+ (Values$cardinality a) (Values$cardinality b))))))
(define-fun null_message () Values$t Values$empty)
(declare-fun mk_array_6 () (Array node Values$t))
(assert (exists ((mk_array_6_index node)) (= (select mk_array_6 mk_array_6_index) null_message)))
(define-fun null_state () Values$t Values$empty)
(declare-fun mk_array_7 () (Array node Values$t))
(assert (forall ((mk_array_7_index node)) (= (select mk_array_7 mk_array_7_index) null_state)))
(declare-fun choose (Values$t) value)
(assert (forall ((vals Values$t)) (or (= vals Values$empty) (= (Values$mem (choose vals) vals) Truth))))
(check-sat-using (then solve-eqs nnf ctx-solver-simplify))
[751] %

```

OS: Ubuntu 18.04
Commit: dde0c51

**Comment by NikolajBjorner** [comment]
The bug is still there. Will not fix it: it is triggered by a combination of parameters that don't resemble a reasonable use case.
