### ISSUE TITLE
Segfault QF_SLIA formula proof=true, rewriter.eqineq=true

### ISSUE THREAD

**Issue by wintered** [Z3Prover/z3#4010]
```
[589] % z3 small.smt2
Segmentation fault
[590] % z3release small.smt2
unknown
[591] % z3san small.smt2
Failed to verify: m.is_eq(atom, lhs, rhs)
ASAN:DEADLYSIGNAL
=================================================================
==6339==ERROR: AddressSanitizer: SEGV on unknown address 0x0001bfff804b (pc 0x55a2eaa3f016 bp 0x7fff88833940 sp 0x7fff88833920 T0)
==6339==The signal is caused by a READ memory access.
  #0 0x55a2eaa3f015 in smt::context::get_enode(expr const*) const ../src/smt/smt_context.h:278
  #1 0x55a2eaa3f015 in smt::theory_lra::imp::get_enode(expr*) const ../src/smt/theory_lra.cpp:370
  #2 0x55a2eaa3f015 in smt::theory_lra::imp::internalize_eq_eh(app*, int) ../src/smt/theory_lra.cpp:1106
  #3 0x55a2eaa3f015 in smt::theory_lra::internalize_eq_eh(app*, int) ../src/smt/theory_lra.cpp:3938
  #4 0x55a2eac71abc in smt::context::internalize_eq(app*, bool) ../src/smt/smt_internalizer.cpp:434
  #5 0x55a2eac71abc in smt::context::internalize_formula(expr*, bool) ../src/smt/smt_internalizer.cpp:408
  #6 0x55a2eac6c4e9 in smt::context::internalize_rec(expr*, bool) ../src/smt/smt_internalizer.cpp:350
  #7 0x55a2eac73dba in smt::context::internalize(expr*, bool) ../src/smt/smt_internalizer.cpp:339
  #8 0x55a2ea8c4fd4 in smt::theory::mk_eq(expr*, expr*, bool) ../src/smt/smt_theory.cpp:128
  #9 0x55a2eb0f3bdc in smt::theory_seq::add_length_axiom(expr*) ../src/smt/theory_seq.cpp:4705
  #10 0x55a2eb0f439a in smt::theory_seq::deque_axiom(expr*) ../src/smt/theory_seq.cpp:4623
  #11 0x55a2eb0f4b1d in smt::theory_seq::propagate() ../src/smt/theory_seq.cpp:4595
  #12 0x55a2ea5b1fb7 in smt::context::propagate_theories() ../src/smt/smt_context.cpp:1600
  #13 0x55a2ea5b1fb7 in smt::context::propagate() ../src/smt/smt_context.cpp:1683
  #14 0x55a2ea5bd9f1 in smt::context::bounded_search() ../src/smt/smt_context.cpp:3716
  #15 0x55a2ea5be497 in smt::context::search() ../src/smt/smt_context.cpp:3600
  #16 0x55a2ea5c04f9 in smt::context::check(unsigned int, expr* const*, bool) ../src/smt/smt_context.cpp:3483
  #17 0x55a2ea5c11d1 in smt::context::setup_and_check(bool) ../src/smt/smt_context.cpp:3419
  #18 0x55a2ea44278f in smt_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/smt/tactic/smt_tactic.cpp:201
  #19 0x55a2ebec8257 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120
  #20 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #21 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #22 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #23 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #24 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #25 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #26 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #27 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #28 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #29 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #30 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #31 0x55a2ebebabb1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #32 0x55a2ebec8257 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120
  #33 0x55a2ebe29c4a in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactic.cpp:148
  #34 0x55a2ebe2bf4d in check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ../src/tactic/tactic.cpp:168
  #35 0x55a2ebd2a8a8 in check_sat_core2 ../src/solver/tactic2solver.cpp:185
  #36 0x55a2ebd31c67 in solver_na2as::check_sat_core(unsigned int, expr* const*) ../src/solver/solver_na2as.cpp:67
  #37 0x55a2ebcef674 in combined_solver::check_sat_core(unsigned int, expr* const*) ../src/solver/combined_solver.cpp:246
  #38 0x55a2ebcd0761 in solver::check_sat(unsigned int, expr* const*) ../src/solver/solver.cpp:330
  #39 0x55a2ebc2b820 in cmd_context::check_sat(unsigned int, expr* const*) ../src/cmd_context/cmd_context.cpp:1551
  #40 0x55a2ebb72503 in smt2::parser::parse_check_sat() ../src/parsers/smt2/smt2parser.cpp:2596
  #41 0x55a2ebb72503 in smt2::parser::parse_cmd() ../src/parsers/smt2/smt2parser.cpp:2938
  #42 0x55a2ebb72503 in smt2::parser::operator()() ../src/parsers/smt2/smt2parser.cpp:3130
  #43 0x55a2ebb29a25 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) ../src/parsers/smt2/smt2parser.cpp:3179
  #44 0x55a2e91c8466 in read_smtlib2_commands(char const*) ../src/shell/smtlib_frontend.cpp:89
  #45 0x55a2e91a0e3e in main ../src/shell/main.cpp:352
  #46 0x7f6624eecb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
  #47 0x55a2e91b4ad9 in _start (/home/suz/software/z3san/build-04172020182140-3e9479d/z3+0x1f7ad9)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/smt/smt_context.h:278 in smt::context::get_enode(expr const*) const
==6339==ABORTING
[592] % 
[592] % cat small.smt2
(set-option :proof true)
(set-option :rewriter.eq2ineq true)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(declare-fun d () Int)
(declare-fun e () String)
(declare-fun f () String)
(declare-fun g () String)
(assert (= g (str.++ e f)))
(assert (= c d 20))
(assert (distinct a d (str.len g)))
(assert (= c (str.len e)))
(check-sat)
[593] %
```

OS: Ubuntu 18.04
Commit: 3e9479d

**Comment by zhendongsu** [comment]
Another simpler test that doesn't require the rewriter.eq2ineq option: 
```
[854] % z3san small.smt2
Failed to verify: m.is_eq(atom, lhs, rhs)
ASAN:DEADLYSIGNAL
=================================================================
==2110==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000598 (pc 0x562e341c6af3 bp 0x7ffd4c8761c0 sp 0x7ffd4c8761a0 T0)
==2110==The signal is caused by a READ memory access.
==2110==Hint: address points to the zero page.
    #0 0x562e341c6af2 in smt::context::get_enode(expr const*) const ../src/smt/smt_context.h:278
    #1 0x562e341c6af2 in smt::theory_lra::imp::get_enode(expr*) const ../src/smt/theory_lra.cpp:370
    #2 0x562e341c6af2 in smt::theory_lra::imp::internalize_eq_eh(app*, int) ../src/smt/theory_lra.cpp:1106
    #3 0x562e341c6af2 in smt::theory_lra::internalize_eq_eh(app*, int) ../src/smt/theory_lra.cpp:3938
    #4 0x562e343f958c in smt::context::internalize_eq(app*, bool) ../src/smt/smt_internalizer.cpp:434
    #5 0x562e343f958c in smt::context::internalize_formula(expr*, bool) ../src/smt/smt_internalizer.cpp:408
    #6 0x562e343f3fb9 in smt::context::internalize_rec(expr*, bool) ../src/smt/smt_internalizer.cpp:350
    #7 0x562e343fb88a in smt::context::internalize(expr*, bool) ../src/smt/smt_internalizer.cpp:339
    #8 0x562e3404caa4 in smt::theory::mk_eq(expr*, expr*, bool) ../src/smt/smt_theory.cpp:128
    #9 0x562e3487b6ac in smt::theory_seq::add_length_axiom(expr*) ../src/smt/theory_seq.cpp:4705
    #10 0x562e3487be6a in smt::theory_seq::deque_axiom(expr*) ../src/smt/theory_seq.cpp:4623
    #11 0x562e3487c5ed in smt::theory_seq::propagate() ../src/smt/theory_seq.cpp:4595
    #12 0x562e33d39a87 in smt::context::propagate_theories() ../src/smt/smt_context.cpp:1600
    #13 0x562e33d39a87 in smt::context::propagate() ../src/smt/smt_context.cpp:1683
    #14 0x562e33d454c1 in smt::context::bounded_search() ../src/smt/smt_context.cpp:3716
    #15 0x562e33d45f67 in smt::context::search() ../src/smt/smt_context.cpp:3600
    #16 0x562e33d47fc9 in smt::context::check(unsigned int, expr* const*, bool) ../src/smt/smt_context.cpp:3483
    #17 0x562e33d48ca1 in smt::context::setup_and_check(bool) ../src/smt/smt_context.cpp:3419
    #18 0x562e33bca25f in smt_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/smt/tactic/smt_tactic.cpp:201
    #19 0x562e3564fc87 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120
    #20 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #21 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #22 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #23 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #24 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #25 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #26 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #27 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #28 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #29 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #30 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #31 0x562e356425e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
    #32 0x562e3564fc87 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120
    #33 0x562e355b167a in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactic.cpp:148
    #34 0x562e355b397d in check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ../src/tactic/tactic.cpp:168
    #35 0x562e354b22d8 in check_sat_core2 ../src/solver/tactic2solver.cpp:185
    #36 0x562e354b9697 in solver_na2as::check_sat_core(unsigned int, expr* const*) ../src/solver/solver_na2as.cpp:67
    #37 0x562e354770a4 in combined_solver::check_sat_core(unsigned int, expr* const*) ../src/solver/combined_solver.cpp:246
    #38 0x562e35458191 in solver::check_sat(unsigned int, expr* const*) ../src/solver/solver.cpp:330
    #39 0x562e353b3250 in cmd_context::check_sat(unsigned int, expr* const*) ../src/cmd_context/cmd_context.cpp:1551
    #40 0x562e352f9f33 in smt2::parser::parse_check_sat() ../src/parsers/smt2/smt2parser.cpp:2596
    #41 0x562e352f9f33 in smt2::parser::parse_cmd() ../src/parsers/smt2/smt2parser.cpp:2938
    #42 0x562e352f9f33 in smt2::parser::operator()() ../src/parsers/smt2/smt2parser.cpp:3130
    #43 0x562e352b1455 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) ../src/parsers/smt2/smt2parser.cpp:3179
    #44 0x562e3294ff66 in read_smtlib2_commands(char const*) ../src/shell/smtlib_frontend.cpp:89
    #45 0x562e3292899e in main ../src/shell/main.cpp:352
    #46 0x7f9117030b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #47 0x562e3293c5d9 in _start (/home/suz/software/z3san/build-04182020194526-bcbe802/z3+0x1f75d9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/smt/smt_context.h:278 in smt::context::get_enode(expr const*) const
==2110==ABORTING
[855] % 
[855] % cat small.smt2
(set-option :proof true)
(declare-fun a () Int)
(declare-fun b () String)
(declare-fun c () String)
(declare-fun d () String)
(assert (<= 20 a))
(assert (= d (str.++ b c)))
(assert (= a (str.len d)))
(check-sat)
[856] % 
```

**Comment by NikolajBjorner** [comment]
duplicate
