### ISSUE TITLE
(smt.phase_selection, smt.arith.solver=3, trace, proof) Segmentation fault on QF_S formula

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4022]
Hi,
For this case, Z3  throws out a segmentation fault:
```
[841] % z3 small.smt2
(smt.diff_logic: non-diff logic expression (let ((a!1 (str.len (seq.p.suffix t
                 (str.++ (seq.unit #x61)
                     (seq.unit #x6c)
                     (seq.unit #x65)
                     (seq.unit #x72)
                     (seq.unit #x74)
                     (seq.unit #x30)
                     (seq.unit #x3b))))))
 (+ (str.len t) a!1)))
(smt.diff_logic: non-diff logic expression (let ((a!1 (str.len (seq.p.suffix t
                 (str.++ (seq.unit #x61)
                     (seq.unit #x6c)
                     (seq.unit #x65)
                     (seq.unit #x72)
                     (seq.unit #x74)
                     (seq.unit #x30)
                     (seq.unit #x3b))))))
 (+ (str.len t) a!1)))
Segmentation fault
[842] % z3release small.smt2
(smt.diff_logic: non-diff logic expression (let ((a!1 (str.len (seq.p.suffix t
                 (str.++ (seq.unit #x61)
                     (seq.unit #x6c)
                     (seq.unit #x65)
                     (seq.unit #x72)
                     (seq.unit #x74)
                     (seq.unit #x30)
                     (seq.unit #x3b))))))
 (+ (str.len t) a!1)))
(smt.diff_logic: non-diff logic expression (let ((a!1 (str.len (seq.p.suffix t
                 (str.++ (seq.unit #x61)
                     (seq.unit #x6c)
                     (seq.unit #x65)
                     (seq.unit #x72)
                     (seq.unit #x74)
                     (seq.unit #x30)
                     (seq.unit #x3b))))))
 (+ (str.len t) a!1)))
unknown
[843] % z3san small.smt2
(smt.diff_logic: non-diff logic expression (let ((a!1 (str.len (seq.p.suffix t
                 (str.++ (seq.unit #x61)
                     (seq.unit #x6c)
                     (seq.unit #x65)
                     (seq.unit #x72)
                     (seq.unit #x74)
                     (seq.unit #x30)
                     (seq.unit #x3b))))))
 (+ (str.len t) a!1)))
(smt.diff_logic: non-diff logic expression (let ((a!1 (str.len (seq.p.suffix t
                 (str.++ (seq.unit #x61)
                     (seq.unit #x6c)
                     (seq.unit #x65)
                     (seq.unit #x72)
                     (seq.unit #x74)
                     (seq.unit #x30)
                     (seq.unit #x3b))))))
 (+ (str.len t) a!1)))
ASAN:DEADLYSIGNAL
=================================================================
==11713==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x5647b2892c02 bp 0x7fffccc53fd0 sp 0x7fffccc53e90 T0)
==11713==The signal is caused by a READ memory access.
==11713==Hint: address points to the zero page.
  #0 0x5647b2892c01 in smt::enode::init(ast_manager&, void*, ptr_vector<smt::enode> const&, app*, unsigned int, bool, bool, unsigned int, bool, bool) ../src/smt/smt_enode.cpp:58
  #1 0x5647b2892c01 in smt::enode::mk(ast_manager&, region&, ptr_vector<smt::enode> const&, app*, unsigned int, bool, bool, unsigned int, bool, bool) ../src/smt/smt_enode.cpp:71
  #2 0x5647b2f1a1dd in smt::context::mk_enode(app*, bool, bool, bool) ../src/smt/smt_internalizer.cpp:940
  #3 0x5647b2f3372a in smt::context::internalize_formula_core(app*, bool) ../src/smt/smt_internalizer.cpp:619
  #4 0x5647b2f3834e in smt::context::internalize_eq(app*, bool) ../src/smt/smt_internalizer.cpp:425
  #5 0x5647b2f3834e in smt::context::internalize_formula(expr*, bool) ../src/smt/smt_internalizer.cpp:408
  #6 0x5647b2f32fb9 in smt::context::internalize_rec(expr*, bool) ../src/smt/smt_internalizer.cpp:350
  #7 0x5647b2f3a88a in smt::context::internalize(expr*, bool) ../src/smt/smt_internalizer.cpp:339
  #8 0x5647b2b8baa4 in smt::theory::mk_eq(expr*, expr*, bool) ../src/smt/smt_theory.cpp:128
  #9 0x5647b33ba6ac in smt::theory_seq::add_length_axiom(expr*) ../src/smt/theory_seq.cpp:4705
  #10 0x5647b33bae6a in smt::theory_seq::deque_axiom(expr*) ../src/smt/theory_seq.cpp:4623
  #11 0x5647b33bb5ed in smt::theory_seq::propagate() ../src/smt/theory_seq.cpp:4595
  #12 0x5647b2878a87 in smt::context::propagate_theories() ../src/smt/smt_context.cpp:1600
  #13 0x5647b2878a87 in smt::context::propagate() ../src/smt/smt_context.cpp:1683
  #14 0x5647b28844c1 in smt::context::bounded_search() ../src/smt/smt_context.cpp:3716
  #15 0x5647b2884f67 in smt::context::search() ../src/smt/smt_context.cpp:3600
  #16 0x5647b2886fc9 in smt::context::check(unsigned int, expr* const*, bool) ../src/smt/smt_context.cpp:3483
  #17 0x5647b2887ca1 in smt::context::setup_and_check(bool) ../src/smt/smt_context.cpp:3419
  #18 0x5647b270925f in smt_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/smt/tactic/smt_tactic.cpp:201
  #19 0x5647b418ec87 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120
  #20 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #21 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #22 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #23 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #24 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #25 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #26 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #27 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #28 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #29 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #30 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #31 0x5647b41815e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #32 0x5647b418ec87 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120
  #33 0x5647b40f067a in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactic.cpp:148
  #34 0x5647b40f297d in check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ../src/tactic/tactic.cpp:168
  #35 0x5647b3ff12d8 in check_sat_core2 ../src/solver/tactic2solver.cpp:185
  #36 0x5647b3ff8697 in solver_na2as::check_sat_core(unsigned int, expr* const*) ../src/solver/solver_na2as.cpp:67
  #37 0x5647b3fb60a4 in combined_solver::check_sat_core(unsigned int, expr* const*) ../src/solver/combined_solver.cpp:246
  #38 0x5647b3f97191 in solver::check_sat(unsigned int, expr* const*) ../src/solver/solver.cpp:330
  #39 0x5647b3ef2250 in cmd_context::check_sat(unsigned int, expr* const*) ../src/cmd_context/cmd_context.cpp:1551
  #40 0x5647b3e38f33 in smt2::parser::parse_check_sat() ../src/parsers/smt2/smt2parser.cpp:2596
  #41 0x5647b3e38f33 in smt2::parser::parse_cmd() ../src/parsers/smt2/smt2parser.cpp:2938
  #42 0x5647b3e38f33 in smt2::parser::operator()() ../src/parsers/smt2/smt2parser.cpp:3130
  #43 0x5647b3df0455 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) ../src/parsers/smt2/smt2parser.cpp:3179
  #44 0x5647b148ef66 in read_smtlib2_commands(char const*) ../src/shell/smtlib_frontend.cpp:89
  #45 0x5647b146799e in main ../src/shell/main.cpp:352
  #46 0x7efca1147b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
  #47 0x5647b147b5d9 in _start (/home/suz/software/z3san/build-04182020194526-bcbe802/z3+0x1f75d9)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/smt/smt_enode.cpp:58 in smt::enode::init(ast_manager&, void*, ptr_vector<smt::enode> const&, app*, unsigned int, bool, bool, unsigned int, bool, bool)
==11713==ABORTING
[844] % 
[844] % cat small.smt2
(set-option :smt.phase_selection 5)
(set-option :smt.arith.solver 3)
(set-option :trace true)
(set-option :proof true)
(declare-fun s () String)
(declare-fun t () String)
(assert (distinct t (str.++ "console.log('" s "');")))
(assert (str.<= t "alert0;"))
(assert (str.in.re t (re.+ (re.union (str.to.re "<>") (re.* (re.union (re.range " " ";") )) (str.to.re "/script")))))
(check-sat)
[845] %
```

OS: Ubuntu 18.04
Commit: bcbe802

**Comment by NikolajBjorner** [comment]
see #3999
