### ISSUE TITLE
(proof, trace, rewriter.arith_lhs, tactic.solve_eqs.theory_solver) Segmentation fault on QF_SLIA formula 

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#4023]
Hi,
For this case, Z3  throws out a segmentation fault:
```
[518] % z3-4.8.7 small.smt2
sat
[519] % z3 small.smt2
Segmentation fault
[520] % z3release small.smt2
unknown
[521] % z3san small.smt2
ASAN:DEADLYSIGNAL
=================================================================
==10803==ERROR: AddressSanitizer: SEGV on unknown address 0x622000e991d0 (pc 0x558f045edbca bp 0x7ffeb64bcaf0 sp 0x7ffeb64bc9b0 T0)
==10803==The signal is caused by a READ memory access.
  #0 0x558f045edbc9 in smt::enode::init(ast_manager&, void*, ptr_vector<smt::enode> const&, app*, unsigned int, bool, bool, unsigned int, bool, bool) ../src/smt/smt_enode.cpp:55
  #1 0x558f045edbc9 in smt::enode::mk(ast_manager&, region&, ptr_vector<smt::enode> const&, app*, unsigned int, bool, bool, unsigned int, bool, bool) ../src/smt/smt_enode.cpp:71
  #2 0x558f04c751dd in smt::context::mk_enode(app*, bool, bool, bool) ../src/smt/smt_internalizer.cpp:940
  #3 0x558f04c8e72a in smt::context::internalize_formula_core(app*, bool) ../src/smt/smt_internalizer.cpp:619
  #4 0x558f04c9334e in smt::context::internalize_eq(app*, bool) ../src/smt/smt_internalizer.cpp:425
  #5 0x558f04c9334e in smt::context::internalize_formula(expr*, bool) ../src/smt/smt_internalizer.cpp:408
  #6 0x558f04c8dfb9 in smt::context::internalize_rec(expr*, bool) ../src/smt/smt_internalizer.cpp:350
  #7 0x558f04c9588a in smt::context::internalize(expr*, bool) ../src/smt/smt_internalizer.cpp:339
  #8 0x558f048e6aa4 in smt::theory::mk_eq(expr*, expr*, bool) ../src/smt/smt_theory.cpp:128
  #9 0x558f051156ac in smt::theory_seq::add_length_axiom(expr*) ../src/smt/theory_seq.cpp:4705
  #10 0x558f05115e6a in smt::theory_seq::deque_axiom(expr*) ../src/smt/theory_seq.cpp:4623
  #11 0x558f051165ed in smt::theory_seq::propagate() ../src/smt/theory_seq.cpp:4595
  #12 0x558f045d3a87 in smt::context::propagate_theories() ../src/smt/smt_context.cpp:1600
  #13 0x558f045d3a87 in smt::context::propagate() ../src/smt/smt_context.cpp:1683
  #14 0x558f045df4c1 in smt::context::bounded_search() ../src/smt/smt_context.cpp:3716
  #15 0x558f045dff67 in smt::context::search() ../src/smt/smt_context.cpp:3600
  #16 0x558f045e1fc9 in smt::context::check(unsigned int, expr* const*, bool) ../src/smt/smt_context.cpp:3483
  #17 0x558f045e2ca1 in smt::context::setup_and_check(bool) ../src/smt/smt_context.cpp:3419
  #18 0x558f0446425f in smt_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/smt/tactic/smt_tactic.cpp:201
  #19 0x558f05ee9c87 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120
  #20 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #21 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #22 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #23 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #24 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #25 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #26 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #27 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #28 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #29 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #30 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #31 0x558f05edc5e1 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1034
  #32 0x558f05ee9c87 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:120
  #33 0x558f05e4b67a in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactic.cpp:148
  #34 0x558f05e4d97d in check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ../src/tactic/tactic.cpp:168
  #35 0x558f05d4c2d8 in check_sat_core2 ../src/solver/tactic2solver.cpp:185
  #36 0x558f05d53697 in solver_na2as::check_sat_core(unsigned int, expr* const*) ../src/solver/solver_na2as.cpp:67
  #37 0x558f05d110a4 in combined_solver::check_sat_core(unsigned int, expr* const*) ../src/solver/combined_solver.cpp:246
  #38 0x558f05cf2191 in solver::check_sat(unsigned int, expr* const*) ../src/solver/solver.cpp:330
  #39 0x558f05c4d250 in cmd_context::check_sat(unsigned int, expr* const*) ../src/cmd_context/cmd_context.cpp:1551
  #40 0x558f05b93f33 in smt2::parser::parse_check_sat() ../src/parsers/smt2/smt2parser.cpp:2596
  #41 0x558f05b93f33 in smt2::parser::parse_cmd() ../src/parsers/smt2/smt2parser.cpp:2938
  #42 0x558f05b93f33 in smt2::parser::operator()() ../src/parsers/smt2/smt2parser.cpp:3130
  #43 0x558f05b4b455 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) ../src/parsers/smt2/smt2parser.cpp:3179
  #44 0x558f031e9f66 in read_smtlib2_commands(char const*) ../src/shell/smtlib_frontend.cpp:89
  #45 0x558f031c299e in main ../src/shell/main.cpp:352
  #46 0x7f0bf2711b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
  #47 0x558f031d65d9 in _start (/home/suz/software/z3san/build-04182020194526-bcbe802/z3+0x1f75d9)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/smt/smt_enode.cpp:55 in smt::enode::init(ast_manager&, void*, ptr_vector<smt::enode> const&, app*, unsigned int, bool, bool, unsigned int, bool, bool)
==10803==ABORTING
[522] % 
[522] % cat small.smt2
(set-option :proof true)
(set-option :trace true)
(set-option :rewriter.arith_lhs true)
(set-option :tactic.solve_eqs.theory_solver false)
(declare-fun a () Int)
(declare-fun b () Bool)
(declare-fun c () String)
(assert (= a (str.len c)))
(assert (distinct b (> 50 a)))
(assert b)
(check-sat)
[523] %
```

OS: Ubuntu 18.04
Commit: bcbe802

**Comment by NikolajBjorner** [comment]
see #3999
