### ISSUE TITLE
Z3Exception: Overflow encountered when expanding vector

### ISSUE THREAD

**Issue by 0-14N** [Z3Prover/z3#417]
When I call "Expr.substitute" in Java, I got an exception "Overflow encountered when expanding vector":

```
Exception in thread "Thread-1" com.microsoft.z3.Z3Exception: Overflow encountered when expanding vector
	at com.microsoft.z3.Native.substitute(Native.java:2833)
	at com.microsoft.z3.Expr.substitute(Expr.java:149)
	at com.microsoft.z3.Expr.substitute(Expr.java:164)
```

 I took a look at the source code, the exception was thrown by the following code in z3/vector.h:

```
void expand_vector() {
        if (m_data == 0) {
            SZ capacity = 2;
            SZ * mem    = reinterpret_cast<SZ*>(memory::allocate(sizeof(T) * capacity + sizeof(SZ) * 2));
            *mem              = capacity; 
            mem++;
            *mem              = 0;        
            mem++;
            m_data            = reinterpret_cast<T *>(mem);
        }
        else {
            SASSERT(capacity() > 0);
            SZ old_capacity = reinterpret_cast<SZ *>(m_data)[CAPACITY_IDX];
            SZ old_capacity_T = sizeof(T) * old_capacity + sizeof(SZ) * 2;
            SZ new_capacity = (3 * old_capacity + 1) >> 1;
            SZ new_capacity_T = sizeof(T) * new_capacity + sizeof(SZ) * 2;
            if (new_capacity <= old_capacity || new_capacity_T <= old_capacity_T) {
                throw default_exception("Overflow encountered when expanding vector");
            }
            SZ *mem = (SZ*)memory::reallocate(reinterpret_cast<SZ*>(m_data)-2, new_capacity_T);
            *mem    = new_capacity;
            m_data  = reinterpret_cast<T *>(mem + 2);
        }
    }
```

**Comment by NikolajBjorner** [comment]
So the vector is expanded beyond 2^32. This is either because you generate huge formulas or due to a bug in Z3 that causes allocating large pieces of memory.

**Comment by wintersteiger** [comment]
What @NikolajBjorner said. Do you have a test case you can share, or an interaction log?

**Comment by wintersteiger** [comment]
Bumping this. Could you confirm that this problem still exists? An interaction log of your calls to the API functions would help us to get closer to this a lot quicker (use [Log.open](http://z3prover.github.io/api/html/classcom_1_1microsoft_1_1z3_1_1_log.html#ad57f9410a40ded1858176a544ee0944d) before calling any Z3 functions).

**Comment by wintersteiger** [comment]
Closing this issue as suspected non-issue and no replies.
