### ISSUE TITLE
Segmentation Fault when using quantifiers in recursive function definition

### ISSUE THREAD

**Issue by JamesShaker** [Z3Prover/z3#4394]
z3 version 4.8.8 - 64 bit on Ubuntu crashes with a Segmentation Fault when fed the following MWE:
```
(define-fun-rec f () Bool
    (forall ((x Int)) (= x 0)))
```
Also occurs when using `exists` instead of `forall`. No crash occurs when using non-recursive functions with quantifiers. Compiling with debug symbols and running through GDB gives:
```
Program received signal SIGSEGV, Segmentation fault.
recfun::decl::plugin::compute_scores (this=this@entry=0x555556df84f8, e=<optimised out>, scores=...)
    at ../src/ast/recfun_decl_plugin.cpp:470
470                     for (expr* t : by_depth[i]) {
```

**Comment by zhendongsu** [comment]
Also affects the trunk (https://github.com/Z3Prover/z3/commit/0f8f886389557b001e09a5e88c99e9cd5988a383):
```
[502] % z3debug bug.smt2
ASSERTION VIOLATION
File: ../src/util/map.h
Line: 157
e
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
a
[503] % z3release bug.smt2
Segmentation fault
[504] % z3san bug.smt2
ASAN:DEADLYSIGNAL
=================================================================
==19785==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x56136bb430c5 bp 0x7ffc47e9a570 sp 0x7ffc47e99c90 T0)
==19785==The signal is caused by a READ memory access.
==19785==Hint: address points to the zero page.
    #0 0x56136bb430c4 in vector<expr*, false, unsigned int>::begin() ../src/util/vector.h:311
    #1 0x56136bb430c4 in recfun::decl::plugin::compute_scores(expr*, obj_map<expr, unsigned int>&) ../src/ast/recfun_decl_plugin.cpp:470
    #2 0x56136bb52d4e in recfun::decl::plugin::redirect_ite(recfun::replace&, unsigned int, var* const*, expr*) ../src/ast/recfun_decl_plugin.cpp:488
    #3 0x56136bb5578b in recfun::util::set_definition(recfun::replace&, recfun::promise_def&, unsigned int, var* const*, expr*) ../src/ast/recfun_decl_plugin.cpp:337
    #4 0x56136bb5578b in recfun::decl::plugin::set_definition(recfun::replace&, recfun::promise_def&, unsigned int, var* const*, expr*) ../src/ast/recfun_decl_plugin.cpp:421
    #5 0x56136a7fc181 in cmd_context::insert_rec_fun(func_decl*, ref_vector<expr, ast_manager> const&, svector<symbol, unsigned int> const&, expr*) ../src/cmd_context/cmd_context.cpp:917
    #6 0x56136a7206b1 in smt2::parser::parse_rec_fun_body(func_decl*, ref_vector<expr, ast_manager> const&, svector<symbol, unsigned int> const&) ../src/parsers/smt2/smt2parser.cpp:2437
    #7 0x56136a721536 in smt2::parser::parse_define_fun_rec() ../src/parsers/smt2/smt2parser.cpp:2326
    #8 0x56136a722f67 in smt2::parser::parse_cmd() ../src/parsers/smt2/smt2parser.cpp:2985
    #9 0x56136a722f67 in smt2::parser::operator()() ../src/parsers/smt2/smt2parser.cpp:3129
    #10 0x56136a6da255 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) ../src/parsers/smt2/smt2parser.cpp:3178
    #11 0x561367d91ab6 in read_smtlib2_commands(char const*) ../src/shell/smtlib_frontend.cpp:90
    #12 0x561367d4a31e in main ../src/shell/main.cpp:352
    #13 0x7efe9dc58b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #14 0x561367d5e629 in _start (/local/suz-local/software/z3san/build-05182020202750-0f8f886/z3+0x213629)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/util/vector.h:311 in vector<expr*, false, unsigned int>::begin()
==19785==ABORTING
[505] % 
[505] % cat bug.smt2
(define-fun-rec f () Bool
    (forall ((x Int)) (= x 0)))
[506] % 
```
