### ISSUE TITLE
Memory leak on LRA formula at qe_arith_plugin.cpp:2419 (rlimit)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4441]
Hi, for the following formula, z3 (commit 18bb90f) throws a leak
~~~~
(set-logic LRA)
(set-option :rlimit 596)
(assert (exists ((q2 Real) (q3 Bool) (q4 Bool) (q5 Real) (q6 Bool)) (not (= q5 q5 r0 r12))))
(check-sat)
~~~~

~~~~
==101117==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 392 byte(s) in 1 object(s) allocated from:
    #0 0x7fc2e67fa662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x262f447 in memory::allocate(unsigned long) ../src/util/memory_manager.cpp:268
    #2 0x262ef6a in memory::allocate(char const*, int, char const*, unsigned long) ../src/util/memory_manager.cpp:207
    #3 0xb79e60 in qe::arith_plugin::update_bounds(contains_app&, expr*) ../src/qe/qe_arith_plugin.cpp:2419
    #4 0xb6f58e in qe::arith_plugin::get_num_branches(contains_app&, expr*, rational&) ../src/qe/qe_arith_plugin.cpp:1645
    #5 0xb0f342 in qe::quant_elim_plugin::find_min_weight(app*&, rational&) ../src/qe/qe.cpp:1988
    #6 0xb0e148 in qe::quant_elim_plugin::constrain_assignment() ../src/qe/qe.cpp:1911
    #7 0xb0cf43 in qe::quant_elim_plugin::pop(model_evaluator&) ../src/qe/qe.cpp:1791
    #8 0xb09498 in qe::quant_elim_plugin::final_check() ../src/qe/qe.cpp:1538
    #9 0xb0853a in qe::quant_elim_plugin::check(unsigned int, app* const*, expr*, obj_ref<expr, ast_manager>&, bool, ref_vector<app, ast_manager>&, qe::guarded_defs*) ../src/qe/qe.cpp:1451
    #10 0xb11151 in qe::quant_elim_new::eliminate_block(unsigned int, app* const*, obj_ref<expr, ast_manager>&, ref_vector<app, ast_manager>&, bool, qe::guarded_defs*) ../src/qe/qe.cpp:2157
    #11 0xb1095c in qe::quant_elim_new::eliminate_exists(unsigned int, app* const*, obj_ref<expr, ast_manager>&, ref_vector<app, ast_manager>&, bool, qe::guarded_defs*) ../src/qe/qe.cpp:2108
    #12 0xb11c3f in qe::quant_elim_new::eliminate_exists_bind(unsigned int, app* const*, obj_ref<expr, ast_manager>&) ../src/qe/qe.cpp:2201
    #13 0xb101f5 in qe::quant_elim_new::eliminate(bool, unsigned int, app* const*, obj_ref<expr, ast_manager>&) ../src/qe/qe.cpp:2072
    #14 0xaf96ca in qe::expr_quant_elim::elim(obj_ref<expr, ast_manager>&) ../src/qe/qe.cpp:2349
    #15 0xaf80a6 in qe::expr_quant_elim::operator()(expr*, expr*, obj_ref<expr, ast_manager>&) ../src/qe/qe.cpp:2240
    #16 0xb4e7a2 in qe_tactic::imp::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/qe/qe_tactic.cpp:65
    #17 0xb4eebd in qe_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/qe/qe_tactic.cpp:116
    #18 0x1a7c7d9 in cleanup_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:937
    #19 0x1a7537c in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:113
    #20 0x1a76947 in or_else_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:306
    #21 0x1a7db76 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1051
    #22 0x1a7db76 in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:1051
    #23 0x1a754cb in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:122
    #24 0x1a754cb in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:122
    #25 0x1a6f9b6 in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactic.cpp:150
    #26 0x1a6fe51 in check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ../src/tactic/tactic.cpp:170
    #27 0x19f5e2e in check_sat_core2 ../src/solver/tactic2solver.cpp:185
    #28 0x19faffb in solver_na2as::check_sat_core(unsigned int, expr* const*) ../src/solver/solver_na2as.cpp:67
    #29 0x1a01ef7 in combined_solver::check_sat_core(unsigned int, expr* const*) ../src/solver/combined_solver.cpp:246
~~~~

**Comment by NikolajBjorner** [comment]
formula seems not well formed. code path is not exercised
