### ISSUE TITLE
heap-buffer-over-flow on AUFNIRA formula at ast.cpp:94 (proof)

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4457]
Hi, for the following formula,
z3 (d6ad3719) throws an overflow
~~~~
(set-logic AUFNIRA)
(set-option :proof true)
(assert (! (exists ((q6 (Array Int (Array Int Int))) (q7 (Array Int Int)) (q8 Bool) (q9 (Array Int Int)) (q10 (Array (Array Bool (Array Int (Array Int Int))) Bool))) (=> true false)) :named IP_3))
(declare-const arr (Array (Array Int (Array Int Int)) (Array Int Int)))
~~~~

~~~~
==55137==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x604000001e80 at pc 0x000002290825 bp 0x7ffcfd526010 sp 0x7ffcfd526000
READ of size 4 at 0x604000001e80 thread T0
    #0 0x2290824 in parameter::operator==(parameter const&) const ../src/ast/ast.cpp:94
    #1 0x22b78d8 in bool compare_arrays<parameter>(parameter const*, parameter const*, unsigned int) ../src/util/util.h:308
    #2 0x22919c0 in decl_info::operator==(decl_info const&) const ../src/ast/ast.cpp:221
    #3 0x2292fef in compare_nodes(ast const*, ast const*) ../src/ast/ast.cpp:463
    #4 0x46839b in ast_eq_proc::operator()(ast const*, ast const*) const ../src/ast/ast.h:963
    #5 0x472a66 in chashtable<ast*, obj_ptr_hash<ast>, ast_eq_proc>::equals(ast* const&, ast* const&) const ../src/util/chashtable.h:79
    #6 0x470fab in chashtable<ast*, obj_ptr_hash<ast>, ast_eq_proc>::contains(ast* const&) const ../src/util/chashtable.h:430
    #7 0x22a1bae in ast_manager::register_node_core(ast*) ../src/ast/ast.cpp:1801
    #8 0x22baf1a in sort* ast_manager::register_node<sort>(sort*) ../src/ast/ast.h:1721
    #9 0x22a412a in ast_manager::mk_sort(symbol const&, sort_info*) ../src/ast/ast.cpp:2043
    #10 0x1a3a471 in ast_manager::mk_sort(symbol const&, sort_info const&) ../src/ast/ast.h:1757
    #11 0x2233b12 in array_decl_plugin::mk_sort(int, unsigned int, parameter const*) ../src/ast/array_decl_plugin.cpp:85
    #12 0x22a3b6d in ast_manager::mk_sort(int, int, unsigned int, parameter const*) ../src/ast/ast.cpp:1993
    #13 0x19926b7 in psort_builtin_decl::instantiate(pdecl_manager&, unsigned int, sort* const*) ../src/cmd_context/pdecl.cpp:391
    #14 0x193b703 in smt2::parser::pop_sort_app_frame() ../src/parsers/smt2/smt2parser.cpp:730
    #15 0x193b9e8 in smt2::parser::parse_sort(char const*) ../src/parsers/smt2/smt2parser.cpp:751
    #16 0x194ee18 in smt2::parser::parse_declare_const() ../src/parsers/smt2/smt2parser.cpp:2487
    #17 0x1954010 in smt2::parser::parse_cmd() ../src/parsers/smt2/smt2parser.cpp:2933
    #18 0x1955757 in smt2::parser::operator()() ../src/parsers/smt2/smt2parser.cpp:3129
    #19 0x1934774 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) ../src/parsers/smt2/smt2parser.cpp:3178
    #20 0x43c2d8 in read_smtlib2_commands(char const*) ../src/shell/smtlib_frontend.cpp:90
    #21 0x454408 in main ../src/shell/main.cpp:352
    #22 0x7f30fa8fd82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
~~~~

**Comment by NikolajBjorner** [comment]
fixed
