### ISSUE TITLE
Spacer seg fault in func_interp::get_array_interp (this=0x0, f=0x55555ea086d8) at src/model/func_interp.cpp:427

### ISSUE THREAD

**Issue by leonardoalt** [Z3Prover/z3#4690]
z3 version: 4.8.9

~~The query is https://gist.github.com/leonardoalt/ae660a952383d3f6aff50dc0eee96164.
The seg fault happens via the C++ API. I haven't managed yet to run the cli z3 because of https://github.com/Z3Prover/z3/issues/4689, so posting the stack trace for now. I'm trying to fix the smt2 file manually at the moment to check whether it is reproducible via cli z3.~~

The query is: https://gist.github.com/leonardoalt/9be6d535d0ee1aeecd8383d094283d8f.

Options used:
```
rewriter.pull_cheap_ite=true rlimit=12500000 fp.spacer.q3.use_qgen=true fp.spacer.mbqi=false fp.spacer.ground_pobs=false fp.xform.slice=false fp.xform.inline_linear=false fp.xform.inline_eager=false
```
Stack trace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ffff675b2b8 in func_interp::get_array_interp (this=0x0, f=0x55555ea086d8) at /home/leonardo/devel/z3_upstream/src/model/func_interp.cpp:427
427	    if (m_array_interp != nullptr)
(gdb) bt
#0  0x00007ffff675b2b8 in func_interp::get_array_interp (this=0x0, f=0x55555ea086d8) at /home/leonardo/devel/z3_upstream/src/model/func_interp.cpp:427
#1  0x00007ffff6762b67 in model::cleanup_expr (this=0x55555d07f558, ts=..., e=0x55555d392018, current_partition=0) at /home/leonardo/devel/z3_upstream/src/model/model.cpp:451
#2  0x00007ffff6761f4c in model::cleanup_interp (this=0x55555d07f558, ts=..., f=0x55555bd167f8) at /home/leonardo/devel/z3_upstream/src/model/model.cpp:330
#3  0x00007ffff676160d in model::compress (this=0x55555d07f558) at /home/leonardo/devel/z3_upstream/src/model/model.cpp:232
#4  0x00007ffff78196eb in spacer::ground_sat_answer_op::mk_children (this=0x7fffffffbea0, fr=..., todo=...) at /home/leonardo/devel/z3_upstream/src/muz/spacer/spacer_sat_answer.cpp:148
#5  0x00007ffff7818d41 in spacer::ground_sat_answer_op::operator() (this=0x7fffffffbea0, query=...) at /home/leonardo/devel/z3_upstream/src/muz/spacer/spacer_sat_answer.cpp:95
#6  0x00007ffff773a835 in spacer::context::get_ground_refutation (this=0x55555b50de88) at /home/leonardo/devel/z3_upstream/src/muz/spacer/spacer_context.cpp:2939
#7  0x00007ffff774750f in spacer::context::mk_sat_answer (this=0x55555b50de88) at /home/leonardo/devel/z3_upstream/src/muz/spacer/spacer_context.h:1023
#8  0x00007ffff773a5d3 in spacer::context::get_answer (this=0x55555b50de88) at /home/leonardo/devel/z3_upstream/src/muz/spacer/spacer_context.cpp:2915
#9  0x00007ffff7758367 in spacer::dl_interface::get_answer (this=0x555556544cd8) at /home/leonardo/devel/z3_upstream/src/muz/spacer/spacer_dl_interface.cpp:321
#10 0x00007ffff757fc01 in datalog::context::get_answer_as_formula (this=0x5555564a6378) at /home/leonardo/devel/z3_upstream/src/muz/base/dl_context.cpp:940
#11 0x00007ffff78dc300 in Z3_fixedpoint_get_answer (c=0x5555564932b8, d=0x5555564a2958) at /home/leonardo/devel/z3_upstream/src/api/api_datalog.cpp:333
#12 0x0000555555e762b2 in z3::fixedpoint::get_answer (this=0x555556492ac8) at /usr/include/z3++.h:2949
#13 0x0000555555e74032 in solidity::smtutil::Z3CHCInterface::query (this=0x555556492ab0, _expr=...) at /home/leonardo/devel/solidity/libsmtutil/Z3CHCInterface.cpp:81

(gdb) p m_array_interp 
Cannot access memory at address 0x30
(gdb) p this
$1 = (const func_interp * const) 0x0
```

**Comment by agurfinkel** [comment]
Looks like something unexpected happens in model compression

**Comment by leonardoalt** [comment]
Another case: https://gist.github.com/leonardoalt/bff93f047e649bde097c25f9a75938c1
Seg fault happens at the same location.
Same command line.

**Comment by agurfinkel** [comment]
@hgvk94 I think you looked at this already. What was the conclusion?

**Comment by NikolajBjorner** [comment]
doesn't repro
