### ISSUE TITLE
Sort mismatch with parallel solver

### ISSUE THREAD

**Issue by bctian** [Z3Prover/z3#4745]
Hi! I'm tring Z3 in java and notice there seems something wrong in multithread scenarios.
Here is an example:
```Java
import com.microsoft.z3.*;

public class TestZ3 {

    public static void main(String[] args) {
        Context ctx = new Context();
        Solver solver = ctx.mkSimpleSolver();
        Params param = ctx.mkParams();
        param.add("auto_config", false);
        param.add("threads", 1);
        solver.setParameters(param);

        int n = 1000;
        BitVecExpr[] bv = new BitVecExpr[n];
        for(int i = 0; i < n; ++i) {
            bv[i] = ctx.mkBVConst("bv" + i, 16);
        }
        BoolExpr[] bool = new BoolExpr[n - 2];
        for(int i = 0; i < n - 2; ++i) {
            bool[i] = ctx.mkBVULT(ctx.mkBVXOR(bv[i], bv[i + 1]), bv[i + 2]);
            if(i % 2 == 0) {
                bool[i] = ctx.mkNot(bool[i]);
            }
        }

        System.out.println(solver.check(ctx.mkAnd(bool)));
    }

}

```

It works well and we get a SAT. 
However, when I set the "threads" parameter to 2 or 4, rather than 1, the solver reports a sort mismatch error:
```
Exception in thread "main" com.microsoft.z3.Z3Exception: Sort mismatch at argument #2 for function (declare-fun => (Bool Bool) Bool) supplied sort is Bool
	at com.microsoft.z3.Native.solverCheckAssumptions(Native.java:4720)
	at com.microsoft.z3.Solver.check(Solver.java:228)
	at TestZ3.main(TestZ3.java:26)
```

It's really confusing that a Bool sort mismatches a Bool sort.

**Comment by NikolajBjorner** [comment]
it would happen if expressions are not properly translated between the solvers that are used internally.
I am unable to reproduce the bug, though.

**Comment by bctian** [comment]
Thanks Nikolaj.
I meet this problem in 4.8.8, but I cannot reproduce it after upgrading to 4.8.9. Maybe it has been fixed.
