### ISSUE TITLE
Unable to load shared library 'libz3' 

### ISSUE THREAD

**Issue by EdilsonGalvao** [Z3Prover/z3#4780]
Hello, 

Scenario:
Cent OS 7
Z3 From Nugget 4.8.4 (I used 4.8.9 as well)
C# Code.

Exception
```
---> (Inner Exception #32) System.DllNotFoundException: Unable to load shared library 'libz3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibz3: cannot open shared object file: No such file or directory
   at Microsoft.Z3.Native.LIB.Z3_mk_context_rc(IntPtr a0)
   at Microsoft.Z3.Native.Z3_mk_context_rc(IntPtr a0)
   at Microsoft.Z3.Context..ctor()
   at PVS.Program.<>c__DisplayClass10_0.<Solve>b__0(Equipaments c) in /home/../ESBMCPVS/Benchmark/vZ/Program.cs:line 159
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
```
1. The bin folder contains libz3.so
2. My case is so similar (https://stackoverflow.com/questions/53692341/dllnotfoundexception-for-libz3-dll-when-using-z3-via-nuget/55681867), but doenst work for me.
3.  use this command to `dotnet publish --runtime linux-x64 --self-contained true` publish

**Comment by nunoplopes** [comment]
can you try `export LD_LIBRARY_PATH=.`?

**Comment by EdilsonGalvao** [comment]
Same result.

After Command `dotnet publish --runtime linux-x64 --self-contained true`
I use export LD_LIBRARY_PATH=.

the publish folder contains

```
createdump                                      System.Net.Security.dll
libclrjit.so                                    System.Net.Security.Native.a
libcoreclr.so                                   System.Net.Security.Native.so
libcoreclrtraceptprovider.so                    System.Net.ServicePoint.dll
libdbgshim.so                                   System.Net.Sockets.dll
libhostfxr.so                                   System.Net.WebClient.dll
libhostpolicy.so                                System.Net.WebHeaderCollection.dll
libmscordaccore.so                              System.Net.WebProxy.dll
libmscordbi.so                                  System.Net.WebSockets.Client.dll
libz3.dll                                       System.Net.WebSockets.dll
libz3.so                                        System.Numerics.dll
Microsoft.CSharp.dll                            System.Numerics.Vectors.dll
Microsoft.VisualBasic.Core.dll                  System.ObjectModel.dll
Microsoft.VisualBasic.dll                       System.Private.CoreLib.dll
Microsoft.Win32.Primitives.dll                  System.Private.DataContractSerialization.dll
Microsoft.Win32.Registry.dll                    System.Private.Uri.dll
Microsoft.Z3.dll                                System.Private.Xml.dll
mscorlib.dll                                    System.Private.Xml.Linq.dll
netstandard.dll                                 System.Reflection.DispatchProxy.dll
PVS                                             System.Reflection.dll
PVS.deps.json                                   System.Reflection.Emit.dll
PVS.dll                                         System.Reflection.Emit.ILGeneration.dll
PVS.pdb                                         System.Reflection.Emit.Lightweight.dll
PVS.runtimeconfig.json                          System.Reflection.Extensions.dll
SOS_README.md                                   System.Reflection.Metadata.dll
System.AppContext.dll                           System.Reflection.Primitives.dll
System.Buffers.dll                              System.Reflection.TypeExtensions.dll
System.Collections.Concurrent.dll               System.Resources.Reader.dll
System.Collections.dll                          System.Resources.ResourceManager.dll
System.Collections.Immutable.dll                System.Resources.Writer.dll
System.Collections.NonGeneric.dll               System.Runtime.CompilerServices.Unsafe.dll
System.Collections.Specialized.dll              System.Runtime.CompilerServices.VisualC.dll
System.ComponentModel.Annotations.dll           System.Runtime.dll
System.ComponentModel.DataAnnotations.dll       System.Runtime.Extensions.dll
System.ComponentModel.dll                       System.Runtime.Handles.dll
System.ComponentModel.EventBasedAsync.dll       System.Runtime.InteropServices.dll
System.ComponentModel.Primitives.dll            System.Runtime.InteropServices.RuntimeInformation.dll
System.ComponentModel.TypeConverter.dll         System.Runtime.InteropServices.WindowsRuntime.dll
System.Configuration.dll                        System.Runtime.Intrinsics.dll
System.Console.dll                              System.Runtime.Loader.dll
System.Core.dll                                 System.Runtime.Numerics.dll
System.Data.Common.dll                          System.Runtime.Serialization.dll
System.Data.DataSetExtensions.dll               System.Runtime.Serialization.Formatters.dll
System.Data.dll                                 System.Runtime.Serialization.Json.dll
System.Diagnostics.Contracts.dll                System.Runtime.Serialization.Primitives.dll
System.Diagnostics.Debug.dll                    System.Runtime.Serialization.Xml.dll
System.Diagnostics.DiagnosticSource.dll         System.Runtime.WindowsRuntime.dll
System.Diagnostics.FileVersionInfo.dll          System.Runtime.WindowsRuntime.UI.Xaml.dll
System.Diagnostics.Process.dll                  System.Security.AccessControl.dll
System.Diagnostics.StackTrace.dll               System.Security.Claims.dll
System.Diagnostics.TextWriterTraceListener.dll  System.Security.Cryptography.Algorithms.dll
System.Diagnostics.Tools.dll                    System.Security.Cryptography.Cng.dll
System.Diagnostics.TraceSource.dll              System.Security.Cryptography.Csp.dll
System.Diagnostics.Tracing.dll                  System.Security.Cryptography.Encoding.dll
System.dll                                      System.Security.Cryptography.Native.OpenSsl.a
System.Drawing.dll                              System.Security.Cryptography.Native.OpenSsl.so
System.Drawing.Primitives.dll                   System.Security.Cryptography.OpenSsl.dll
System.Dynamic.Runtime.dll                      System.Security.Cryptography.Primitives.dll
System.Globalization.Calendars.dll              System.Security.Cryptography.X509Certificates.dll
System.Globalization.dll                        System.Security.dll
System.Globalization.Extensions.dll             System.Security.Principal.dll
System.Globalization.Native.so                  System.Security.Principal.Windows.dll
System.IO.Compression.Brotli.dll                System.Security.SecureString.dll
System.IO.Compression.dll                       System.ServiceModel.Web.dll
System.IO.Compression.FileSystem.dll            System.ServiceProcess.dll
System.IO.Compression.Native.a                  System.Text.Encoding.CodePages.dll
System.IO.Compression.Native.so                 System.Text.Encoding.dll
System.IO.Compression.ZipFile.dll               System.Text.Encoding.Extensions.dll
System.IO.dll                                   System.Text.Encodings.Web.dll
System.IO.FileSystem.AccessControl.dll          System.Text.Json.dll
System.IO.FileSystem.dll                        System.Text.RegularExpressions.dll
System.IO.FileSystem.DriveInfo.dll              System.Threading.Channels.dll
System.IO.FileSystem.Primitives.dll             System.Threading.dll
System.IO.FileSystem.Watcher.dll                System.Threading.Overlapped.dll
System.IO.IsolatedStorage.dll                   System.Threading.Tasks.Dataflow.dll
System.IO.MemoryMappedFiles.dll                 System.Threading.Tasks.dll
System.IO.Pipes.AccessControl.dll               System.Threading.Tasks.Extensions.dll
System.IO.Pipes.dll                             System.Threading.Tasks.Parallel.dll
System.IO.UnmanagedMemoryStream.dll             System.Threading.Thread.dll
System.Linq.dll                                 System.Threading.ThreadPool.dll
System.Linq.Expressions.dll                     System.Threading.Timer.dll
System.Linq.Parallel.dll                        System.Transactions.dll
System.Linq.Queryable.dll                       System.Transactions.Local.dll
System.Memory.dll                               System.ValueTuple.dll
System.Native.a                                 System.Web.dll
System.Native.so                                System.Web.HttpUtility.dll
System.Net.dll                                  System.Windows.dll
System.Net.Http.dll                             System.Xml.dll
System.Net.HttpListener.dll                     System.Xml.Linq.dll
System.Net.Http.Native.a                        System.Xml.ReaderWriter.dll
System.Net.Http.Native.so                       System.Xml.Serialization.dll
System.Net.Mail.dll                             System.Xml.XDocument.dll
System.Net.NameResolution.dll                   System.Xml.XmlDocument.dll
System.Net.NetworkInformation.dll               System.Xml.XmlSerializer.dll
System.Net.Ping.dll                             System.Xml.XPath.dll
System.Net.Primitives.dll                       System.Xml.XPath.XDocument.dll
System.Net.Requests.dll                         WindowsBase.dll
```

**Comment by wintersteiger** [comment]
Try setting `LD_DEBUG=all` before running you program to get more information. `strace` can be helpful too. 

`liblibz3: cannot open shared`: Maybe something added an unnecessary `lib` to the name?

Make sure that you're not mixing 32-bit and 64-bit libraries; in some cases the system will not produce any useful information other than "not found", if there's a mismatch.

**Comment by EdilsonGalvao** [comment]
1. I configured absolute path to LD_LIBRARY_PATH using many paths (included libz3 from debug folder) and I have no successful.

2. in Json Settings the runtime is described as below:
`<RuntimeIdentifier>win-x64</RuntimeIdentifier>`
The SO is x64 and Z3 as well.

3. To be honest, I don't know why the exception raise "liblibz3", anyway, I added libz3.dll as liblibz3 and libz3. More once I have no successful.

4. this is the good part, I performed strace (as you said) and LD_DEBUG as well.
The first problem that I found is: the self package does not create the "netcoredeps" folder, look this thread(https://github.com/dotnet/docs/issues/20772) 
The second problem is: The **strace** say that missing libpthread.so and **LB_DEBUG** libc library. There is no convergence in my point of view.
I will try create manually this folder and copy the libraries. Asap I will return with result.

**Strace**
```
execve("./PVS", ["./PVS", "1"], 0x7ffc015d5318 /* 28 vars */) = 0
brk(NULL)                               = 0x9bd000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5efb314000
readlink("/proc/self/exe", "/home/../ESBMCPVS/Be"..., 4096) = 56
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/home/../ESBMCPVS/Benchmark/vZ/linux-x64/netcoredeps/tls/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/../ESBMCPVS/Benchmark/vZ/linux-x64/netcoredeps/tls/x86_64", 0x7ffe954840b0) = -1 ENOENT (No such file or directory)
open("/home/../ESBMCPVS/Benchmark/vZ/linux-x64/netcoredeps/tls/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/../ESBMCPVS/Benchmark/vZ/linux-x64/netcoredeps/tls", 0x7ffe954840b0) = -1 ENOENT (No such file or directory)
open("/home/../ESBMCPVS/Benchmark/vZ/linux-x64/netcoredeps/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/../ESBMCPVS/Benchmark/vZ/linux-x64/netcoredeps/x86_64", 0x7ffe954840b0) = -1 ENOENT (No such file or directory)
open("/home/../ESBMCPVS/Benchmark/vZ/linux-x64/netcoredeps/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/../ESBMCPVS/Benchmark/vZ/linux-x64/netcoredeps", 0x7ffe954840b0) = -1 ENOENT (No such file or directory)
open("../vZ/libz3.dll/tls/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../vZ/libz3.dll/tls/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../vZ/libz3.dll/x86_64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("../vZ/libz3.dll/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
```

**LD_Debug**
```
15420:     find library=libc.so.6 [0]; searching
     15420:      search path=../vZ/libz3.dll/tls/x86_64:../vZ/libz3.dll/tls:../vZ/libz3.dll/x86_64:../vZ/libz3.dll              (LD_LIBRARY_PATH)
     15420:       trying file=../vZ/libz3.dll/tls/x86_64/libc.so.6
     15420:       trying file=../vZ/libz3.dll/tls/libc.so.6
     15420:       trying file=../vZ/libz3.dll/x86_64/libc.so.6
     15420:       trying file=../vZ/libz3.dll/libc.so.6
     15420:      search cache=/etc/ld.so.cache
     15420:       trying file=/lib64/libc.so.6
```

**Comment by KarimGhallab** [comment]
I'am facing the same issue, here. After publishing my app for linux and osx platforms, i get the exact same error.
`System.DllNotFoundException: Unable to load shared library 'libz3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibz3: cannot open shared object file: No such file or directory`

**Comment by OnlyFreeUsername** [comment]
I'm building for docker and having the exact same issue still. No fix available yet?

```
 ---> System.DllNotFoundException: Unable to load shared library 'libz3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibz3: cannot open shared object file: No such file or directory
   at Microsoft.Z3.Native.LIB.Z3_mk_context_rc(IntPtr a0)
   at Microsoft.Z3.Native.Z3_mk_context_rc(IntPtr a0)
   at Microsoft.Z3.Context..ctor()
```

**Comment by sfwester** [comment]
I ran into this issue as well.

It happened when I ran a app referencing:
- `<PackageReference Include="Microsoft.Z3.x64" Version="4.8.5" />` on a debian11 base image
- `<PackageReference Include="Microsoft.Z3" Version="4.8.14" />` on a debian10 base image

However, it was resolved when I did the opposite.  `4.8.14` on `debian11` works and `4.8.5` on `debian10` works.

**Comment by alberdingk-thijm** [comment]
I'm also dealing with this problem on a RHEL v8 machine. I have a project that references [`microsoft/Zen`](github.com/microsoft/Zen), which as of June 27, 2023, contains a [`<PackageReference Include="Microsoft.Z3" Version="4.11.0" />`](https://github.com/microsoft/Zen/blob/master/ZenLib/ZenLib.csproj#L39) directive.

Here is the error thrown:
```
 ---> System.DllNotFoundException: Unable to load shared library 'libz3' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: liblibz3: cannot open shared object file: No such file or directory
```

Running this command with `LD_DEBUG=libs` shows that both "libz3" is searched for *and* "liblibz3":
```
     48331:	/lib64/libstdc++.so.6: error: version lookup error: version `GLIBCXX_3.4.26' not found (required by /home/tthijm/Timepiece/Timepiece.Benchmarks/bin/Debug/net6.0/runtimes/linux-x64/native/libz3.so) (fatal)
     48331:	find library=libz3.so [0]; searching
     48331:	 search path=glibc-hwcaps/x86-64-v4:glibc-hwcaps/x86-64-v3:glibc-hwcaps/x86-64-v2:tls/haswell/avx512_1/x86_64:tls/haswell/avx512_1:tls/haswell/x86_64:tls/haswell:tls/avx512_1/x86_64:tls/avx512_1:tls/x86_64:tls:haswell/avx512_1/x86_64:haswell/avx512_1:haswell/x86_64:haswell:avx512_1/x86_64:avx512_1:x86_64:		(LD_LIBRARY_PATH)
     48331:	  trying file=glibc-hwcaps/x86-64-v4/libz3.so
     48331:	  trying file=glibc-hwcaps/x86-64-v3/libz3.so
     48331:	  trying file=glibc-hwcaps/x86-64-v2/libz3.so
     48331:	  trying file=tls/haswell/avx512_1/x86_64/libz3.so
     48331:	  trying file=tls/haswell/avx512_1/libz3.so
     48331:	  trying file=tls/haswell/x86_64/libz3.so
     48331:	  trying file=tls/haswell/libz3.so
     48331:	  trying file=tls/avx512_1/x86_64/libz3.so
     48331:	  trying file=tls/avx512_1/libz3.so
     48331:	  trying file=tls/x86_64/libz3.so
     48331:	  trying file=tls/libz3.so
     48331:	  trying file=haswell/avx512_1/x86_64/libz3.so
     48331:	  trying file=haswell/avx512_1/libz3.so
     48331:	  trying file=haswell/x86_64/libz3.so
     48331:	  trying file=haswell/libz3.so
     48331:	  trying file=avx512_1/x86_64/libz3.so
     48331:	  trying file=avx512_1/libz3.so
     48331:	  trying file=x86_64/libz3.so
     48331:	  trying file=libz3.so
     48331:	 search cache=/etc/ld.so.cache
     48331:	 search path=/lib64/tls:/lib64:/usr/lib64/tls:/usr/lib64		(system search path)
     48331:	  trying file=/lib64/tls/libz3.so
     48331:	  trying file=/lib64/libz3.so
     48331:	  trying file=/usr/lib64/tls/libz3.so
     48331:	  trying file=/usr/lib64/libz3.so
     48331:
     48331:	find library=liblibz3.so [0]; searching
     48331:	 search path=glibc-hwcaps/x86-64-v4:glibc-hwcaps/x86-64-v3:glibc-hwcaps/x86-64-v2:tls/haswell/avx512_1/x86_64:tls/haswell/avx512_1:tls/haswell/x86_64:tls/haswell:tls/avx512_1/x86_64:tls/avx512_1:tls/x86_64:tls:haswell/avx512_1/x86_64:haswell/avx512_1:haswell/x86_64:haswell:avx512_1/x86_64:avx512_1:x86_64:		(LD_LIBRARY_PATH)
     48331:	  trying file=glibc-hwcaps/x86-64-v4/liblibz3.so
     48331:	  trying file=glibc-hwcaps/x86-64-v3/liblibz3.so
     48331:	  trying file=glibc-hwcaps/x86-64-v2/liblibz3.so
     48331:	  trying file=tls/haswell/avx512_1/x86_64/liblibz3.so
     48331:	  trying file=tls/haswell/avx512_1/liblibz3.so
     48331:	  trying file=tls/haswell/x86_64/liblibz3.so
     48331:	  trying file=tls/haswell/liblibz3.so
     48331:	  trying file=tls/avx512_1/x86_64/liblibz3.so
     48331:	  trying file=tls/avx512_1/liblibz3.so
     48331:	  trying file=tls/x86_64/liblibz3.so
     48331:	  trying file=tls/liblibz3.so
     48331:	  trying file=haswell/avx512_1/x86_64/liblibz3.so
     48331:	  trying file=haswell/avx512_1/liblibz3.so
     48331:	  trying file=haswell/x86_64/liblibz3.so
     48331:	  trying file=haswell/liblibz3.so
     48331:	  trying file=avx512_1/x86_64/liblibz3.so
     48331:	  trying file=avx512_1/liblibz3.so
     48331:	  trying file=x86_64/liblibz3.so
     48331:	  trying file=liblibz3.so
     48331:	 search cache=/etc/ld.so.cache
     48331:	 search path=/lib64/tls:/lib64:/usr/lib64/tls:/usr/lib64		(system search path)
     48331:	  trying file=/lib64/tls/liblibz3.so
     48331:	  trying file=/lib64/liblibz3.so
     48331:	  trying file=/usr/lib64/tls/liblibz3.so
     48331:	  trying file=/usr/lib64/liblibz3.so
```

**Comment by ITaluone** [comment]
I have to chip in here.. having the same exception on linux (CI) with 4.12.2. But 4.11.2 does work.

**Comment by NikolajBjorner** [comment]
These appear to be downlevel issues. There is no support for down-level z3.
