### ISSUE TITLE
Consolidate issues on string formulas

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#4805]
Hi, for the following formula,
z3 40159a3a96b throws a leak
~~~~
(declare-fun i9 () Int)
(declare-fun str12 () String)
(assert (or (distinct i9 (abs (* 47 (* 84 80) i9 84 28))) (str.in_re str12 (str.to_re "pKiHwUQBmIWLhwkHomYlIkCXqhBsfFCWETyTTrxqLUXGpPBnUo"))))
(check-sat-using (then simplify nnf add-bounds normalize-bounds qfnia))
~~~~

~~~~
sat

=================================================================
==132782==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 360 byte(s) in 9 object(s) allocated from:
    #0 0x7ff36c797662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x27d5181 in memory::allocate(unsigned long) ../src/util/memory_manager.cpp:273
    #2 0x28057f7 in small_object_allocator::allocate(unsigned long) ../src/util/small_object_allocator.cpp:103
    #3 0x281d727 in mpz_manager<false>::allocate(unsigned int) ../src/util/mpz.cpp:201
    #4 0x281fe8f in mpz_manager<false>::big_set(mpz&, mpz const&) ../src/util/mpz.cpp:1503
    #5 0x577fa5 in mpz_manager<false>::set(mpz&, mpz const&) ../src/util/mpz.h:535
    #6 0xcfd7a6 in _scoped_numeral<mpz_manager<false> >::_scoped_numeral(_scoped_numeral<mpz_manager<false> > const&) ../src/util/scoped_numeral.h:31
    #7 0xcf7087 in value_trail<smt::context, _scoped_numeral<mpz_manager<false> > >::value_trail(value_trail<smt::context, _scoped_numeral<mpz_manager<false> > > const&) (/home/peisen/test/tofuzz/z3-debug/build/z3+0xcf7087)
    #8 0xcf7173 in void smt::context::push_trail<value_trail<smt::context, _scoped_numeral<mpz_manager<false> > > >(value_trail<smt::context, _scoped_numeral<mpz_manager<false> > > const&) (/home/peisen/test/tofuzz/z3-debug/build/z3+0xcf7173)
    #9 0xcddec0 in smt::theory_pb::assign_ineq(smt::theory_pb::ineq&, bool) ../src/smt/theory_pb.cpp:1109
    #10 0xcdd109 in smt::theory_pb::assign_eh(int, bool) ../src/smt/theory_pb.cpp:1009
    #11 0xf938eb in smt::context::propagate_atoms() ../src/smt/smt_context.cpp:1355
    #12 0xf976a4 in smt::context::propagate() ../src/smt/smt_context.cpp:1713
    #13 0xfadda2 in smt::context::bounded_search() ../src/smt/smt_context.cpp:3798
    #14 0xfac608 in smt::context::search() ../src/smt/smt_context.cpp:3688
    #15 0xfaabbf in smt::context::check(unsigned int, expr* const*, bool) ../src/smt/smt_context.cpp:3571
    #16 0xfa9eed in smt::context::setup_and_check(bool) ../src/smt/smt_context.cpp:3507
    #17 0xd0ffb4 in smt::kernel::imp::setup_and_check() ../src/smt/smt_kernel.cpp:108
    #18 0xd0ddbf in smt::kernel::setup_and_check() ../src/smt/smt_kernel.cpp:326
    #19 0xc3ed4b in smt_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/smt/tactic/smt_tactic.cpp:201
    #20 0x1bfa82b in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:122
    #21 0x1c01ea9 in try_for_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:961
    #22 0x1bfbc1b in or_else_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:298
    #23 0x1bfa82b in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:122
    #24 0x1bfa82b in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:122
    #25 0x1bfa82b in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:122
    #26 0x1bfa82b in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:122
    #27 0x1bfa82b in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:122
    #28 0x1bfa82b in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:122
    #29 0x1c004b3 in unary_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) ../src/tactic/tactical.cpp:788

SUMMARY: AddressSanitizer: 360 byte(s) leaked in 9 allocation(s).

~~~~

**Comment by rainoftime** [comment]
z3 40159a3
~~~~
(set-option :smt.arith.bounded_expansion true)
(declare-fun v1 () Bool)
(declare-fun v2 () Bool)
(declare-fun v3 () Bool)
(declare-fun v6 () Bool)
(declare-fun v8 () Bool)
(declare-fun v13 () Bool)
(declare-fun i2 () Int)
(declare-fun i15 () Int)
(declare-fun str1 () String)
(declare-fun str2 () String)
(declare-fun str4 () String)
(declare-fun str6 () String)
(declare-fun str8 () String)
(declare-fun str11 () String)
(declare-fun str13 () String)
(declare-fun str15 () String)
(declare-fun str16 () String)
(push 1)
(check-sat)
(pop 1)
(assert (= true true true true (str.in_re str15 (str.to_re "")) true))
(declare-fun v16 () Bool)
(assert (or v1 true (str.in_re (str.substr str16 64 (abs (abs i2))) (str.to_re str13)) (str.in_re str4 (str.to_re "BffzmoGsWHteAoPbmbhWcbgP"))))
(push 1)
(pop 1)
(assert (= str1 str4))
(push 1)
(check-sat)
(pop 1)
(declare-fun v20 () Bool)
(assert (or v16 v13))
(assert (xor v3 v20 v1 true (=> (distinct (str.substr (str.replace_re_all (str.substr str16 64 (abs (abs i2))) (str.to_re str16) str4) 166 (str.to_int (str.++ str4 str2))) (str.substr str11 i15 (str.to_int str2)) str13 "oMreFJECjBYQXtMD" "AiZLVHjOcCUVyooBnlCWhPNDrkvNQM") (= 59 (abs (abs i2)) 166)) v6))
(push 1)
(assert (xor (str.in_re (str.substr str16 64 (abs (abs i2))) (str.to_re str13)) true true false (str.prefixof str8 str6)))
(check-sat)
~~~~

~~~~
sat
sat
ASSERTION VIOLATION
File: ../src/smt/theory_seq.cpp
Line: 3077
n1->get_root() != n2->get_root()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~
