### ISSUE TITLE
(parallel.enable, rewriter.hoist_mul, rewriter.mul_to_power) Segmentation fault

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#5031]
```
[530] % z3release small.smt2
Segmentation fault
[531] % z3debug small.smt2
Segmentation fault
[532] %
[532] % cat small.smt2
(set-option :parallel.enable true)
(set-option :rewriter.hoist_mul true)
(set-option :rewriter.mul_to_power true)
(declare-sort a)
(declare-sort b)
(declare-sort d)
(declare-sort k)
(declare-sort e)
(declare-sort aa)
(declare-sort g)
(declare-sort h)
(declare-sort i)
(declare-sort j)
(declare-sort l)
(declare-sort m)
(declare-sort c)
(declare-fun ab () j)
(declare-fun n (i Int) j)
(declare-fun o (e Int) b)
(declare-fun r () e)
(declare-fun ac (c Int) Int)
(declare-fun p (k Int) c)
(declare-fun ad (l Int) i)
(declare-fun ae (d Int) l)
(declare-fun af (aa b) j)
(declare-fun t (m b) Int)
(declare-fun q () m)
(declare-fun f () d)
(declare-fun v () k)
(declare-fun u () l)
(declare-fun s (a b) aa)
(declare-fun y () a)
(declare-fun ag (h b) b)
(declare-fun ah (g b) h)
(declare-fun ai () g)
(assert
 (forall ((qaj Int))
 (= (forall ((qz Int) (qak Int) (qk Int))
   (let ((ql (ae f qaj)))
    (= (= (n (ad ql qz) qak) ab)
    (= (= (n (ad (ae f qz) qk) qak) ab) (= (n (ad ql qk) qak) ab)))))
  (forall ((qz b))
  (= (= (af (s y (o r qaj)) qz) ab)
   (forall ((aj Int))
   (= (forall ((qaj b)) (= (af (s y qaj) (ag (ah ai qaj) qz)) ab))
    (forall ((qaj Int))
    (= (forall ((qz Int))
      (= (= (n (ad u aj) qz) ab)
       (not (forall ((ak Int)) (not (= qz 0))))))
     (= (o r 0) (o r (ac (p v (t q (o r (- qaj 1)))) 0))))))))))))
(check-sat)
[533] %
```
Commit: 1da7522

**Comment by rainoftime** [comment]
~~~~
=================================================================
==12937==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x000000cee167 bp 0x7f7c5b5e0700 sp 0x7f7c5b5e06f0 T1)
    #0 0xcee166 in smt::enode::get_root() const ../src/smt/smt_enode.h:188
^[[O    #1 0xf83dee in smt::enode::init(ast_manager&, void*, ptr_vector<smt::enode> const&, app*, unsigned int, bool, bool, unsigned int, bool, bool) ../src/smt/smt_enode.cpp:58
    #2 0xf8415f in smt::enode::mk(ast_manager&, region&, ptr_vector<smt::enode> const&, app*, unsigned int, bool, bool, unsigned int, bool, bool) ../src/smt/smt_enode.cpp:71
    #3 0x100138c in smt::context::mk_enode(app*, bool, bool, bool) ../src/smt/smt_internalizer.cpp:971
    #4 0x11ba8ef in smt::theory_lra::imp::mk_enode(app*) ../src/smt/theory_lra.cpp:553
    #5 0x11b99e1 in smt::theory_lra::imp::linearize(smt::theory_lra::imp::scoped_internalize_state&) ../src/smt/theory_lra.cpp:482
    #6 0x11b83cc in smt::theory_lra::imp::linearize_term(expr*, smt::theory_lra::imp::scoped_internalize_state&) ../src/smt/theory_lra.cpp:337
    #7 0x11bc1fd in smt::theory_lra::imp::internalize_def(app*) (/home/peisen/test/tofuzz/z3-debug/build/z3+0x11bc1fd)
    #8 0x11bf69e in smt::theory_lra::imp::internalize_term(app*) (/home/peisen/test/tofuzz/z3-debug/build/z3+0x11bf69e)
    #9 0x11ae727 in smt::theory_lra::internalize_term(app*) ../src/smt/theory_lra.cpp:3786
    #10 0xfff98f in smt::context::internalize_theory_term(app*) ../src/smt/smt_internalizer.cpp:869
    #11 0xffeb65 in smt::context::internalize_term(app*) ../src/smt/smt_internalizer.cpp:808
    #12 0xffa751 in smt::context::internalize_rec(expr*, bool) ../src/smt/smt_internalizer.cpp:378
    #13 0xff9ff7 in smt::context::internalize(expr*, bool, unsigned int) ../src/smt/smt_internalizer.cpp:337
    #14 0x136d2a1 in smt::model_checker::assert_new_instances() ../src/smt/smt_model_checker.cpp:536
    #15 0x136cb2b in smt::model_checker::restart_eh() ../src/smt/smt_model_checker.cpp:503
    #16 0x10c1c6f in smt::default_qm_plugin::restart_eh() ../src/smt/smt_quantifier.cpp:733
    #17 0x10bf58d in smt::quantifier_manager::imp::restart_eh() ../src/smt/smt_quantifier.cpp:350
    #18 0x10bc391 in smt::quantifier_manager::restart_eh() ../src/smt/smt_quantifier.cpp:508
    #19 0xfb0933 in smt::context::restart(lbool&, unsigned int) ../src/smt/smt_context.cpp:3746
    #20 0xfafe30 in smt::context::search() ../src/smt/smt_context.cpp:3683
    #21 0xfae16f in smt::context::check(unsigned int, expr* const*, bool) ../src/smt/smt_context.cpp:3561
    #22 0xd13ad0 in smt::kernel::imp::check(unsigned int, expr* const*) (/home/peisen/test/tofuzz/z3-debug/build/z3+0xd13ad0)
    #23 0xd118e1 in smt::kernel::check(unsigned int, expr* const*) ../src/smt/smt_kernel.cpp:330
    #24 0x10d0e04 in check_sat_core2 ../src/smt/smt_solver.cpp:200
    #25 0x1bc14d1 in solver_na2as::check_sat_core(unsigned int, expr* const*) ../src/solver/solver_na2as.cpp:67
    #26 0x1bc576e in solver::check_sat(unsigned int, expr* const*) ../src/solver/solver.cpp:332
    #27 0x5fb8be in solver::check_sat(ref_vector<expr, ast_manager> const&) ../src/solver/solver.h:161
    #28 0x1bd50e1 in parallel_tactic::solver_state::simplify() ../src/solver/parallel_tactic.cpp:281
    #29 0x1bd800f in parallel_tactic::cube_and_conquer(parallel_tactic::solver_state&) ../src/solver/parallel_tactic.cpp:519
    #30 0x1bd9525 in parallel_tactic::run_solver() ../src/solver/parallel_tactic.cpp:672
    #31 0x1bd9c01 in parallel_tactic::solve(ref<model>&)::{lambda()#1}::operator()() const (/home/peisen/test/tofuzz/z3-debug/build/z3+0x1bd9c01)
    #32 0x1bdfea7 in void std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) /usr/include/c++/5/functional:1531
    #33 0x1bdfdbb in std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()>::operator()() /usr/include/c++/5/functional:1520
    #34 0x1bdfd4b in std::thread::_Impl<std::_Bind_simple<parallel_tactic::solve(ref<model>&)::{lambda()#1} ()> >::_M_run() /usr/include/c++/5/thread:115
    #35 0x7f7c5ef71e5d  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0e5d)
    #36 0x7f7c5f28b6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #37 0x7f7c5e6bd4dc in clone (/lib/x86_64-linux-gnu/libc.so.6+0x1074dc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/smt/smt_enode.h:188 smt::enode::get_root() const
Thread T1 created by T0 here:
    #0 0x7f7c5f4d71e3 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x361e3)
    #1 0x7f7c5ef71f63 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd0f63)

==12937==ABORTING
~~~~
