### ISSUE TITLE
"python scripts/mk_make.py" fails and "make" fails

### ISSUE THREAD

**Issue by mayankgrg** [Z3Prover/z3#5041]
Copied 'z3rcf.cpython-38.pyc'
Copied 'z3core.cpython-38.pyc'
Testing ar...
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/ubuntu/Downloads/z3-z3-4.8.10/scripts/mk_util.py", line 2646, in mk_makefile
    mk_config()
  File "/home/ubuntu/Downloads/z3-z3-4.8.10/scripts/mk_util.py", line 2459, in mk_config
    check_ar()
  File "/home/ubutnu/Downloads/z3-z3-4.8.10/scripts/mk_util.py", line 504, in check_ar
    raise MKException('%s (archive tool) was not found' % AR)
mk_exception.MKException: 'ar (archive tool) was not found'

**Comment by NikolajBjorner** [comment]
you don't have 'ar' on your path. You will need this if you want to run mk_make.py
Alternatively, try the cmake build system.
