### ISSUE TITLE
Consoliated issues for arithmetic formulas

### ISSUE THREAD

**Issue by rainoftime** [Z3Prover/z3#5320]
Hi, for the following formula,
z3 Bjorner
~~~~
(set-option :combined_solver.ignore_solver1 true)
(set-option :rewriter.eq2ineq true)
(assert (exists ((i Int)) (not (and (not (= i 0)) (ite (not (= i 0)) false true)))))
(check-sat)
(check-sat-using qffd)
~~~~

~~~~
z3 model_validate=true delta.smt2
sat
failed to verify: (exists ((i Int))
  (let ((a!1 (and (not (and (<= i 0) (>= i 0))) (<= i 0) (>= i 0))))
    (not a!1)))
evaluated to (exists ((i Int))
  (let ((a!1 (and (not (and (<= i 0) (>= i 0))) (<= i 0) (>= i 0))))
    (not a!1)))
(params keep_cardinality_constraints true pb.solver solver)

=================================================================
==85107==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x4d8892 in malloc /home/lvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145
    #1 0x412a752 in memory::allocate(unsigned long) /home/peisen/test/tofuzz/z3-debug/build/../src/util/memory_manager.cpp:273:16
    #2 0x4169aed in region::allocate(unsigned long) /home/peisen/test/tofuzz/z3-debug/build/../src/util/region.cpp:28:16
    #3 0x18e6edc in operator new[](unsigned long, region&) /home/test/tofuzz/z3-debug/build/../src/util/region.h:93:63
    #4 0x18e47ef in smt::ext_simple_justification::ext_simple_justification(region&, unsigned int, sat::literal const*, unsigned int, std::pair<smt::enode*, smt::enode*> const*) /home/test/tofuzz/z3-debug/build/../src/smt/smt_justification.cpp:305:17
    #5 0x1499197 in smt::ext_theory_simple_justification::ext_theory_simple_justification(int, region&, unsigned int, sat::literal const*, unsigned int, std::pair<smt::enode*, smt::enode*> const*, unsigned int, parameter*) /home/test/tofuzz/z3-debug/build/../src/smt/smt_justification.h:325:13
    #6 0x1592256 in smt::ext_theory_eq_propagation_justification::ext_theory_eq_propagation_justification(int, region&, unsigned int, sat::literal const*, unsigned int, std::pair<smt::enode*, smt::enode*> const*, smt::enode*, smt::enode*, unsigned int, parameter*) /home/test/tofuzz/z3-debug/build/../src/smt/smt_justification.h:374:13
    #7 0x1bbca37 in smt::theory_lra::imp::assign_eq(int, int) /home/test/tofuzz/z3-debug/build/../src/smt/theory_lra.cpp:3035:17
    #8 0x1c1783d in smt::theory_lra::imp::fixed_var_eh(int, lp::tv, unsigned int, unsigned int, rational const&) /home//test/tofuzz/z3-debug/build/../src/smt/theory_lra.cpp:3073:9
    #9 0x1c16d09 in smt::theory_lra::imp::propagate_eqs(lp::tv, unsigned int, lp::lconstraint_kind, lp_api::bound<sat::literal>&, rational const&) /home//test/tofuzz/z3-debug/build/../src/smt/theory_lra.cpp:2894:13
    #10 0x1c0fffd in smt::theory_lra::imp::assert_bound(unsigned int, bool, lp_api::bound<sat::literal>&) /home//test/tofuzz/z3-debug/build/../src/smt/theory_lra.cpp:2843:13
    #11 0x1b970c0 in smt::theory_lra::imp::propagate() /home/test/tofuzz/z3-debug/build/../src/smt/theory_lra.cpp:2084:17
    #12 0x1b8f242 in smt::theory_lra::propagate() /home/peisen/test/tofuzz/z3-debug/build/../src/smt/theory_lra.cpp:3826:12
    #13 0x180f5f0 in smt::context::propagate_theories() /home//test/tofuzz/z3-debug/build/../src/smt/smt_context.cpp:1611:16
    #14 0x1810a1b in smt::context::propagate() /home/test/tofuzz/z3-debug/build/../src/smt/smt_context.cpp:1709:22
    #15 0x1830ca4 in smt::context::bounded_search() /homest/tofuzz/z3-debug/build/../src/smt/smt_context.cpp:3788:21
    #16 0x182deab in smt::context::search() /home/peisen/test/tofuzz/z3-debug/build/../src/smt/smt_context.cpp:3678:22
    #17 0x182d0a4 in smt::context::check(unsigned int, expr* const*, bool) /home/est/tofuzz/z3-debug/build/../src/smt/smt_context.cpp:3561:17
    #18 0x13d52d7 in smt::kernel::imp::check(unsigned int, expr* const*) 
~~~~

**Comment by rainoftime** [comment]
(set-option :nlsat.randomize false)
(set-option :nlsat.reorder false)
(declare-fun b () Real)
(declare-fun a () Real)
(assert (and (= a (* b b)) (not (distinct (* a a) (* b b b b)))))
(check-sat-using (then add-bounds ctx-solver-simplify))

~~~~
ASSERTION VIOLATION
File: ../src/smt/tactic/ctx_solver_simplify_tactic.cpp
Line: 141
UNEXPECTED CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~

**Comment by rainoftime** [comment]
~~~~
(declare-const v Bool)
(assert (= v (= 0.0 (/ 1.0 0.0))))
(assert (not (= v (= 0.0 (/ 1.0 0.0)))))
(check-sat-using (then simplify aig purify-arith add-bounds recover-01 propagate-ineqs))
~~~~
~~~~
z3 delta.out.smt2
ASSERTION VIOLATION
File: ../src/util/mpq.cpp
Line: 306
d > 0.0
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
~~~~
