### ISSUE TITLE
python bindings are not installed

### ISSUE THREAD

**Issue by yaitskov** [Z3Prover/z3#5544]
Hi,

```
$ git log -1
* 47fdd6c06 - (HEAD -> master, origin/master, origin/HEAD) Added 16 bit string-encoding (#5540) (31 hours ago) (CEisenhofer)

$ mkdir build
$ cd build
$ cmake ..
$ make
...
[ 97%] Built target api
...
$ sudo make install
...
[ 97%] Built target api
...
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /var/empty/local/lib/cmake/z3/Z3Targets.cmake
-- Up-to-date: /var/empty/local/lib/cmake/z3/Z3Targets-relwithdebinfo.cmake
-- Up-to-date: /var/empty/local/lib/cmake/z3/Z3Config.cmake
-- Up-to-date: /var/empty/local/lib/cmake/z3/Z3ConfigVersion.cmake
-- Up-to-date: /var/empty/local/lib/pkgconfig/z3.pc
-- Up-to-date: /var/empty/local/lib/libz3.so.4.8.13.0
-- Up-to-date: /var/empty/local/lib/libz3.so.4.8
-- Up-to-date: /var/empty/local/lib/libz3.so
-- Up-to-date: /var/empty/local/include/z3_algebraic.h
-- Up-to-date: /var/empty/local/include/z3_api.h
-- Up-to-date: /var/empty/local/include/z3_ast_containers.h
-- Up-to-date: /var/empty/local/include/z3_fixedpoint.h
-- Up-to-date: /var/empty/local/include/z3_fpa.h
-- Up-to-date: /var/empty/local/include/z3.h
-- Up-to-date: /var/empty/local/include/z3++.h
-- Up-to-date: /var/empty/local/include/z3_macros.h
-- Up-to-date: /var/empty/local/include/z3_optimization.h
-- Up-to-date: /var/empty/local/include/z3_polynomial.h
-- Up-to-date: /var/empty/local/include/z3_rcf.h
-- Up-to-date: /var/empty/local/include/z3_v1.h
-- Up-to-date: /var/empty/local/include/z3_spacer.h
-- Up-to-date: /var/empty/local/include/z3_version.h
-- Up-to-date: /var/empty/local/bin/z3
```

inside src/api/python/README:
```
On Linux and macOS, you must install python bindings, before trying example.py.
To install python on Linux and macOS, you should execute the following
command in the Z3 root directory

        sudo make install-z3py
```

```
$ sudo make install-z3py # inside build directory
make: *** No rule to make target 'install-z3py'.  Stop.
$ cd .. # project root
make: *** No rule to make target 'install-z3py'.  Stop.
```

**Comment by yaitskov** [comment]
Manuall attempt
```
$ cd src/api/python
$ python setup.py build
$ sudo python setup.py install
...
Installed /usr/local/lib/python3.7/dist-packages/z3_solver-4.8.13.0-py3.7.egg
Processing dependencies for z3-solver==4.8.13.0
Finished processing dependencies for z3-solver==4.8.13.0

$ python -m z3
python3 -m z3
/bin/python3: Error while finding module specification for 'z3.__main__' (ImportError: cannot import name 'z3core' from 'z3' (/usr/local/lib/python3.7/dist-packages/z3_solver-4.8.13.0-py3.7.egg/z3/__init__.py))
```

**Comment by yaitskov** [comment]
```
$ cmake .. -DZ3_INSTALL_PYTHON_BINDINGS=ON  
$ make
$ find .. -name '*z3core*' | wc -l
0

```

**Comment by yaitskov** [comment]
cmake-gui turns python binding but python -m z3 cannot find libz3.so with default prefix (/var/empty) or /usr/local (after ldconfig)
setting Z3_LIBRARY_PATH has no effect

```
python -m z3
Could not find libz3.so; consider adding the directory containing it to
  - your system's PATH environment variable,
  - the Z3_LIBRARY_PATH environment variable, or 
  - to the custom Z3_LIB_DIRS Python-builtin before importing the z3 module, e.g. via
    import builtins
    builtins.Z3_LIB_DIRS = [ '/path/to/libz3.so' ] 
Traceback (most recent call last):
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/site-packages/z3/__init__.py", line 1, in <module>
    from .z3 import *
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/site-packages/z3/z3.py", line 48, in <module>
    from . import z3core
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/site-packages/z3/z3core.py", line 67, in <module>
    raise Z3Exception("libz3.%s not found." % _ext)
z3.z3types.Z3Exception: libz3.so not found.

```

**Comment by NikolajBjorner** [comment]
There are two build systems, the python based and the cmake build system. Instructions may refer to one or the other system. Use README-CMake.md for whatever relates to cmake.
I would have to read the scripts to help you, but so would you.
