### ISSUE TITLE
Segfault in z3 python 

### ISSUE THREAD

**Issue by pgoodman** [Z3Prover/z3#565]
To reproduce:
```python
import z3
a = z3.BitVec('aaaa', 32)
op = z3.Optimize()
op.add(a >= z3.BitVecVal(0, 32))
op.check()
m = op.minimize(a)
m.lower()
```

Stack trace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff401018d in opt::context::get_lower_as_num(unsigned int) () from /usr/lib/libz3.so
(gdb) bt
#0  0x00007ffff401018d in opt::context::get_lower_as_num(unsigned int) () from /usr/lib/libz3.so
#1  0x00007ffff4010729 in opt::context::get_lower(unsigned int) () from /usr/lib/libz3.so
#2  0x00007ffff3fc16b9 in Z3_optimize_get_lower () from /usr/lib/libz3.so
#3  0x00007ffff50ffadc in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#4  0x00007ffff50ff40c in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#5  0x00007ffff54f55fe in _ctypes_callproc () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#6  0x00007ffff54f6f9e in ?? () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#7  0x0000000000499be5 in PyEval_EvalFrameEx ()
#8  0x0000000000499ef2 in PyEval_EvalFrameEx ()
#9  0x0000000000499ef2 in PyEval_EvalFrameEx ()
#10 0x00000000004a1634 in ?? ()
#11 0x000000000044e87c in PyRun_InteractiveOneFlags ()
#12 0x000000000044e998 in PyRun_InteractiveLoopFlags ()
#13 0x000000000044ed70 in PyRun_AnyFileExFlags ()
#14 0x000000000044f904 in Py_Main ()
#15 0x00007ffff7818ec5 in __libc_start_main (main=0x44f9c2 <main>, argc=1, argv=0x7fffffffded8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdec8) at libc-start.c:287
#16 0x0000000000578c4e in _start ()
```

**Comment by NikolajBjorner** [comment]
Correct usage is to access lower/upper bounds after "check"

     import z3
     a = z3.BitVec('aaaa', 32)
     op = z3.Optimize()
     op.add(a >= z3.BitVecVal(0, 32))
     m = op.minimize(a)
     op.check()
     print m.lower()
