### ISSUE TITLE
Stack-overflow at bit_blaster_tpl<bit_blaster_cfg>::mk_const_case_multiplier

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#5779]
I'm not sure this case is valuable.
This case may contain a non-standard bit-width bit-vector, but it does generate from the seed in SMT-COMP benchmarks. 

```
$ cat delta.smt2
(assert (and (exists ((V (_ BitVec 28943))) (= (_ bv0 28943) (bvadd V V)))))
(check-sat)

$ z3 delta.smt2
AddressSanitizer:DEADLYSIGNAL
=================================================================
==598479==ERROR: AddressSanitizer: stack-overflow on address 0x7ffed4037fa0 (pc 0x5605bb532b02 bp 0x7ffed40381d0 sp 0x7ffed4037f10 T0)
    #0 0x5605bb532b01 in bit_blaster_tpl<bit_blaster_cfg>::mk_const_case_multiplier(bool, unsigned int, unsigned int, ptr_buffer<expr, 128u>&, ptr_buffer<expr, 128u>&, ref_vector<expr, ast_manager>&) (/z3/build/z3+0x3e78b01)
    #1 0x5605bb533552 in bit_blaster_tpl<bit_blaster_cfg>::mk_const_case_multiplier(bool, unsigned int, unsigned int, ptr_buffer<expr, 128u>&, ptr_buffer<expr, 128u>&, ref_vector<expr, ast_manager>&) (/z3/build/z3+0x3e79552)
    #2 0x5605bb533552 in bit_blaster_tpl<bit_blaster_cfg>::mk_const_case_multiplier(bool, unsigned int, unsigned int, ptr_buffer<expr, 128u>&, ptr_buffer<expr, 128u>&, ref_vector<expr, ast_manager>&) (/z3/build/z3+0x3e79552)
    #3 0x5605bb533552 in bit_blaster_tpl<bit_blaster_cfg>::mk_const_case_multiplier(bool, unsigned int, unsigned int, ptr_buffer<expr, 128u>&, ptr_buffer<expr, 128u>&, ref_vector<expr, ast_manager>&) (/z3/build/z3+0x3e79552)
    #4 0x5605bb533552 in bit_blaster_tpl<bit_blaster_cfg>::mk_const_case_multiplier(bool, unsigned int, unsigned int, ptr_buffer<expr, 128u>&, ptr_buffer<expr, 128u>&, ref_vector<expr, ast_manager>&) (/z3/build/z3+0x3e79552)
    #5 0x5605bb533552 in bit_blaster_tpl<bit_blaster_cfg>::mk_const_case_multiplier(bool, unsigned int, unsigned int, ptr_buffer<expr, 128u>&, ptr_buffer<expr, 128u>&, ref_vector<expr, ast_manager>&) (z3/build/z3+0x3e79552)
......
#248 0x5605bb533552 in bit_blaster_tpl<bit_blaster_cfg>::mk_const_case_multiplier(bool, unsigned int, unsigned int, ptr_buffer<expr, 128u>&, ptr_buffer<expr, 128u>&, ref_vector<expr, ast_manager>&) (/z3/build/z3+0x3e79552)

SUMMARY: AddressSanitizer: stack-overflow (/z3/build/z3+0x3e78b01) in bit_blaster_tpl<bit_blaster_cfg>::mk_const_case_multiplier(bool, unsigned int, unsigned int, ptr_buffer<expr, 128u>&, ptr_buffer<expr, 128u>&, ref_vector<expr, ast_manager>&)
==598479==ABORTING
```
****
```
$ cat seed.smt2
(set-info :smt-lib-version 2.6)
(set-logic QF_BV)
(set-info :source |
We verify that there exists no y != x with (x + y) = (x << 1).
Contributed by Andreas Froehlich, Gergely Kovasznai, Armin Biere
Institute for Formal Models and Verification, JKU, Linz, 2013
source: http://fmv.jku.at/smtbench and "Efficiently Solving Bit-Vector Problems Using Model Checkers" by Andreas Froehlich, Gergely Kovasznai, Armin Biere. In Proc. 11th Intl. Workshop on Satisfiability Modulo Theories (SMT'13), pages 6-15, aff. to SAT'13, Helsinki, Finland, 2013.
|)
(set-info :category "crafted")
(set-info :status unsat)
(declare-fun x () (_ BitVec 28943))
(declare-fun y () (_ BitVec 28943))
(declare-fun z () (_ BitVec 28943))
(assert (= z (bvadd x y)))
(assert (= z (bvshl x (_ bv1 28943))))
(assert (distinct x y))
(check-sat)
(exit)
```

Commit:https://github.com/Z3Prover/z3/commit/fcc9f379e7384194c6a8faac7b5522014987cd34

**Comment by NikolajBjorner** [comment]
It is out of scope of what bv theory implementation supports. 
The example is used to as part of illustrating NEXPTIME classification of the BV theory.
The implemented procedures are doubly exponential in the logarithm of the bit-width.
