### ISSUE TITLE
Parse Error on running mini_ic3.py

### ISSUE THREAD

**Issue by Rashmeet09** [Z3Prover/z3#5793]
Traceback (most recent call last):
  File "/home/local/ASUAD/rmnayyar/Desktop/ILP/mini_ic3.py", line 392, in <module>
    test("data/horn1.smt2")
  File "/home/local/ASUAD/rmnayyar/Desktop/ILP/mini_ic3.py", line 377, in test
    h2t.parse(file)
  File "/home/local/ASUAD/rmnayyar/Desktop/ILP/mini_ic3.py", line 26, in parse
    goals = fp.parse_file(file)
  File "/home/local/ASUAD/rmnayyar/.local/lib/python3.6/site-packages/z3/z3.py", line 7527, in parse_file
    return AstVector(Z3_fixedpoint_from_file(self.ctx.ref(), self.fixedpoint, f), self.ctx)
  File "/home/local/ASUAD/rmnayyar/.local/lib/python3.6/site-packages/z3/z3core.py", line 4513, in Z3_fixedpoint_from_file
    _elems.Check(a0)
  File "/home/local/ASUAD/rmnayyar/.local/lib/python3.6/site-packages/z3/z3core.py", line 1447, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'parser error'

**Comment by NikolajBjorner** [comment]
Looks like you copied the example to a new folder and the "data" folder doesn't exist.
I had to update the script a few places to make it run with latest python I have. Though, within the examples/python folder it does work.
