### ISSUE TITLE
Z3 fails to terminate despite set timeout

### ISSUE THREAD

**Issue by rindPHI** [Z3Prover/z3#5891]
I encountered a situation where the solver diverges even if I set a timeout (value of timeout seems not to matter). You can reproduce it with Z3 4.8.14.0 using the following Python code:

```python
import z3


def make_formula(number: int, should_terminate: bool) -> z3.BoolRef:
    formula = f"""
    (assert (forall 
      ((container String) (number String))
      (=> (and 
            (str.contains start container) 
            (str.contains container number) 
            {'(= (str.++ number (str.++ " * " "<number>")) container)' if not should_terminate else ''})
          (exists 
            ((elem String))
            (and 
              (str.contains number elem)
              (<= (if (= (str.at elem 0) "-") 
                    (* -1 (str.to.int (str.substr elem 1 (- (str.len elem) 1))))
                    (str.to.int elem))
                  {number}))))))"""

    start = z3.String("start")
    return z3.parse_smt2_string(formula, decls={"start": start})[0]


# Terminates
formula = z3.Not(z3.Implies(make_formula(-100, True), make_formula(-50, True)))

s = z3.Solver()
s.set("timeout", 100)
s.append(formula)
print(s.check())

# Diverges
formula = z3.Not(z3.Implies(make_formula(-100, False), make_formula(-50, False)))

s = z3.Solver()
s.set("timeout", 100)
s.append(formula)
print(s.check())
```

As you see, you can make the solver terminate / diverge by not adding / adding a specific premise to the formulas for which I check the implication. I would understand an "unknown" result, but nontermination despite the timeout is not the best possible outcome ;)

@nunoplopes guesses that the reason is ["the QI or the seq_rewriter that get stuck without checking for resource limits"](https://github.com/Z3Prover/z3/issues/5702#issuecomment-1062893272) and posted the following trace to demonstrate this:

```
#1  0x00007ffff6a7c57a in ast_manager::mk_app_core(func_decl*, unsigned int, expr* const*) [clone .constprop.0] ()
#2  0x00007ffff6a824fe in ast_manager::mk_app(int, int, expr*, expr*) ()
#3  0x00007ffff667e408 in seq_rewriter::mk_str_stoi(expr*, obj_ref<expr, ast_manager>&) ()
#4  0x00007ffff669483b in seq_rewriter::mk_app_core(func_decl*, unsigned int, expr* const*, obj_ref<expr, ast_manager>&)
#5  0x00007ffff6645b54 in (anonymous namespace)::th_rewriter_cfg::reduce_app(func_decl*, unsigned int, expr* const*, obj_ref<expr, ast_manager>&, obj_ref<app, ast_manager>&) ()
#6  0x00007ffff664965b in rewriter_tpl<(anonymous namespace)::th_rewriter_cfg>::operator()(expr*, obj_ref<expr, ast_manager>&, obj_ref<app, ast_manager>&) ()
#7  0x00007ffff5e5fdc2 in smt::qi_queue::instantiate(smt::qi_queue::entry&) ()
#8  0x00007ffff5e60932 in smt::qi_queue::instantiate() ()
#9  0x00007ffff5f4cac1 in smt::context::propagate() ()
#10 0x00007ffff5f52938 in smt::context::init_assumptions(ref_vector<expr, ast_manager> const&) ()
```
 
Thanks for the good work!

**Comment by NikolajBjorner** [comment]
contains and str.to.int are "evil". The solver isn't particularly good at handling all cases around these. It is generally open ended to deal with this so I can't take it as a bug.

**Comment by rindPHI** [comment]
Oh OK thanks anyway. Though it would be nice if it would at least terminate... Guess I'll have to put it in some process and kill it myself after a timeout then.

**Comment by NikolajBjorner** [comment]
it terminates for me with the timeout set.

**Comment by rindPHI** [comment]
Interesting! I just tried again in fresh virtual environments with Z3 4.8.14.0 and both Python 3.8 and 3.10, and it diverges, whether or not I set a timeout.
