### ISSUE TITLE
(tactic.default_tactic=smt, sat.euf=true) heap-buffer-overflow issue

### ISSUE THREAD

**Issue by merlinsun** [Z3Prover/z3#6058]
Hi,
For this instance, z3 https://github.com/Z3Prover/z3/commit/63b9c4bdf02c551384192f4426a9d3f6026e18fc
```
$ cat delta.smt2
(declare-const x Bool)
(declare-fun v () Int)
(assert (or true x (and false (= (_ bv0 14) ((_ int2bv 14) v)) (= (_ bv0 14) (bvurem (_ bv1 14) ((_ int2bv 14) 1))))))
(check-sat)
$ z3 delta.smt2
=================================================================
==33519==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62500025c908 at pc 0x5608d5e3ed77 bp 0x7ffe460b5220 sp 0x7ffe460b5210
WRITE of size 1 at 0x62500025c908 thread T0
    #0 0x5608d5e3ed76 in euf::th_explain::mk(euf::th_euf_solver&, unsigned int, sat::literal const*, unsigned int, std::pair<euf::enode*, euf::enode*> const*, sat::literal, euf::enode*, euf::enode*, sat::proof_hint const*) (/root/z3/build/z3+0x32b7d76)
    #1 0x5608d5e3f530 in euf::th_explain::propagate(euf::th_euf_solver&, svector<sat::literal, unsigned int> const&, svector<std::pair<euf::enode*, euf::enode*>, unsigned int> const&, euf::enode*, euf::enode*, sat::proof_hint const*) (/root/z3/build/z3+0x32b8530)
    #2 0x5608d5f86952 in arith::solver::add_eq(unsigned int, unsigned int, lp::explanation const&, bool) (/root/z3/build/z3+0x33ff952)
    #3 0x5608d5fe5ad3 in lp::lp_bound_propagator<arith::solver>::add_eq_on_columns(lp::explanation const&, unsigned int, unsigned int, bool) (/root/z3/build/z3+0x345ead3)
    #4 0x5608d5ff38b7 in lp::lp_bound_propagator<arith::solver>::try_add_equation_with_internal_fixed_tables(unsigned int) (/root/z3/build/z3+0x346c8b7)
    #5 0x5608d5ff59ff in lp::lp_bound_propagator<arith::solver>::try_add_equation_with_lp_fixed_tables(unsigned int, lp::lp_bound_propagator<arith::solver>::vertex const*) (/root/z3/build/z3+0x346e9ff)
    #6 0x5608d5fff59b in void lp::lar_solver::propagate_bounds_for_touched_rows<arith::solver>(lp::lp_bound_propagator<arith::solver>&) (/root/z3/build/z3+0x347859b)
    #7 0x5608d5fca0d1 in arith::solver::propagate_bounds_with_lp_solver() (/root/z3/build/z3+0x34430d1)
    #8 0x5608d5fcad4e in arith::solver::unit_propagate() (/root/z3/build/z3+0x3443d4e)
    #9 0x5608d5d4894f in euf::solver::unit_propagate() (/root/z3/build/z3+0x31c194f)
    #10 0x5608d83837d8 in sat::solver::propagate_core(bool) (/root/z3/build/z3+0x57fc7d8)
    #11 0x5608d83bb58b in sat::solver::basic_search() (/root/z3/build/z3+0x583458b)
    #12 0x5608d83bd5e4 in sat::solver::check(unsigned int, sat::literal const*) (/root/z3/build/z3+0x58365e4)
    #13 0x5608d5ce88c6 in sat_tactic::imp::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) (/root/z3/build/z3+0x31618c6)
    #14 0x5608d5cede14 in sat_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) (/root/z3/build/z3+0x3166e14)
    #15 0x5608d70c51c8 in cleanup_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) (/root/z3/build/z3+0x453e1c8)
    #16 0x5608d7160f89 in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&) (/root/z3/build/z3+0x45d9f89)
    #17 0x5608d71639d6 in check_sat(tactic&, ref<goal>&, ref<model>&, labels_vec&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (/root/z3/build/z3+0x45dc9d6)
    #18 0x5608d6f2acb1 in (anonymous namespace)::tactic2solver::check_sat_core2(unsigned int, expr* const*) (/root/z3/build/z3+0x43a3cb1)
    #19 0x5608d6f2430e in solver_na2as::check_sat_core(unsigned int, expr* const*) (/root/z3/build/z3+0x439d30e)
    #20 0x5608d6fa7164 in combined_solver::check_sat_core(unsigned int, expr* const*) (/root/z3/build/z3+0x4420164)
    #21 0x5608d6f75b17 in solver::check_sat(unsigned int, expr* const*) (/root/z3/build/z3+0x43eeb17)
    #22 0x5608d6e61da5 in cmd_context::check_sat(unsigned int, expr* const*) (/root/z3/build/z3+0x42dada5)
    #23 0x5608d6dc14b8 in smt2::parser::operator()() (/root/z3/build/z3+0x423a4b8)
    #24 0x5608d6d52d11 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&, char const*) (/root/z3/build/z3+0x41cbd11)
    #25 0x5608d330143a in read_smtlib2_commands(char const*) (/root/z3/build/z3+0x77a43a)
    #26 0x5608d32ba3da in main (/root/z3/build/z3+0x7333da)
    #27 0x7fcb8fc390b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #28 0x5608d32d360d in _start (/root/z3/build/z3+0x74c60d)
......
SUMMARY: AddressSanitizer: heap-buffer-overflow (/root/z3/build/z3+0x32b7d76) in euf::th_explain::mk(euf::th_euf_solver&, unsigned int, sat::literal const*, unsigned int, std::pair<euf::enode*, euf::enode*> const*, sat::literal, euf::enode*, euf::enode*, sat::proof_hint const*)
```

**Comment by NikolajBjorner** [comment]
fixed
