### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by saramohammadinejad** [Z3Prover/z3#6187]
Hi, I'm trying to install z3 on Mac using the command "pip install z3-solver" but it fails due to following error? any idea what should I do?

Building wheel for z3-solver (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for z3-solver (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      running bdist_wheel
      running build
      Configuring Z3
      Traceback (most recent call last):
        File "/Users/saramohamadi/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/saramohamadi/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/saramohamadi/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 330, in <module>
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "<string>", line 229, in run
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 338, in execute
          util.execute(func, args, msg, dry_run=self.dry_run)
        File "/private/var/folders/vl/x_fx4m791kj8wjpq4v0ggcqh0000gn/T/pip-build-env-gyg15zp9/overlay/lib/python3.8/site-packages/setuptools/_distutils/util.py", line 344, in execute
          func(*args)
        File "<string>", line 136, in _configure_z3
      AttributeError: 'str' object has no attribute 'starts_with'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for z3-solver
Failed to build z3-solver
ERROR: Could not build wheels for z3-solver, which is required to install pyproject.toml-based projects

**Comment by NikolajBjorner** [comment]
thanks this is a regression in 10.0 just pushed to pypi. It should be fixed in about 40 minutes with 4.10.1.

**Comment by NikolajBjorner** [comment]
Try now: pip install --upgrade z3-solver

**Comment by saramohammadinejad** [comment]
Thank you! Now I can install it, but for a simple z3 code I get segmentation fault : 11 error. 

from z3 import *
o = Optimize()

I get segmentation fault : 11 for the line o = Optimize(). Any idea what the problem is?

**Comment by NikolajBjorner** [comment]
was this resolved? Maybe side-by-side installations. I haven't heard other M1 issues so assume this is local to your setup.
