### ISSUE TITLE
`NoSuchFieldError` calling `Global.getParameter` in Java API

### ISSUE THREAD

**Issue by thpani** [Z3Prover/z3#6311]
Calling `Global.getParameter()` in the Java API throws a `java.lang.NoSuchFieldError` exception.

### Example

```java
import com.microsoft.z3.*;

class JavaExample {
  public static void main(String[] args) {
    System.out.println(Global.getParameter("smt.random_seed"));
  }
}
```

Results in the exception:

```
Exception in thread "main" java.lang.NoSuchFieldError: com.microsoft.z3.Native$StringPtr.value J
	at com.microsoft.z3.Native.INTERNALglobalParamGet(Native Method)
	at com.microsoft.z3.Native.globalParamGet(Native.java:767)
	at com.microsoft.z3.Global.getParameter(Global.java:60)
	at JavaExample.main(JavaExample.java:5)
```

This happens independent of the parameter name supplied.

### Versions

z3: current HEAD e4ef1717e3a7b30fc87a4959dd80195a519721a2
JDK: Temurin-17.0.2+8

**Comment by NikolajBjorner** [comment]
I doubt this ever worked.
update_api.py creates the stub:

```
DLL_VIS JNIEXPORT jboolean JNICALL Java_com_microsoft_z3_Native_INTERNALglobalParamGet(JNIEnv * jenv, jclass cls, jstring a0, jobject a1) {
  Z3_string _a0 = (Z3_string) jenv->GetStringUTFChars(a0, NULL);
  Z3_string _a1;
  bool result = Z3_global_param_get(_a0, &_a1);
  jenv->ReleaseStringUTFChars(a0, _a0);
  {
     jclass mc    = jenv->GetObjectClass(a1);
     jfieldID fid = jenv->GetFieldID(mc, "value", "J");
     jenv->SetLongField(a1, fid, (jlong) _a1);
  }
  return (jboolean) result;
}
```

The script update_api.py does not consider the case of _out(STRING) so appears to use an incorrect type.
If you know the correct approach, can you add a pull request for 
https://github.com/Z3Prover/z3/blob/master/scripts/update_api.py?

FYI - @wintersteiger
