### ISSUE TITLE
Can't load libz3.dll into Python

### ISSUE THREAD

**Issue by kenmcmil** [Z3Prover/z3#636]
Background:

Windows 8.1
Python 2.7.11, 32 bit
Z3 4.4.1, 32 bit

```
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import z3
>>> z3.init('c:/Users/kenmcmil/Downloads/z3-4.4.1-x86-win/bin/libz3.dll')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\DLLs\z3core.py", line 42, in init
    _lib = ctypes.CDLL(PATH)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 5] Access is denied
>>> 
```

**Comment by kenmcmil** [comment]
Problem was extracting the archive with Cygwin unzip leaves all the files with no execute permission.
