### ISSUE TITLE
4.12.1.0: Python3 Segmentation Fault With Incorrect z3.BoolRef argument

### ISSUE THREAD

**Issue by LMS57** [Z3Prover/z3#6560]
As the title suggests, in Python3 when sending an incorrect argument into z3.BoolRef python3 will Segfault.
Tested on:
   z3-solver 4.12.1.0
   Python3 10.6
Examples:
```
>>> import z3
>>> z3.z3.BoolRef(1)
Segmentation fault
```
```
>>> import z3
>>> z3.z3.BoolRef(0xdeadbeef)
Segmentation fault
```
Then when trying to print out, with 0 we get an invalid AST
```
>>> import z3
>>> a = z3.z3.BoolRef(0)
>>> a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/z3/z3.py", line 362, in __repr__
    return obj_to_string(self)
  File "/usr/local/lib/python3.10/dist-packages/z3/z3printer.py", line 1434, in obj_to_string
    _PP(out, _Formatter(a))
  File "/usr/local/lib/python3.10/dist-packages/z3/z3printer.py", line 1327, in __call__
    return self.main(a)
  File "/usr/local/lib/python3.10/dist-packages/z3/z3printer.py", line 1301, in main
    return self.pp_expr(a, 0, [])
  File "/usr/local/lib/python3.10/dist-packages/z3/z3printer.py", line 1197, in pp_expr
    if z3.is_app(a):
  File "/usr/local/lib/python3.10/dist-packages/z3/z3.py", line 1287, in is_app
    k = _ast_kind(a.ctx, a)
  File "/usr/local/lib/python3.10/dist-packages/z3/z3.py", line 494, in _ast_kind
    return Z3_get_ast_kind(ctx.ref(), a)
  File "/usr/local/lib/python3.10/dist-packages/z3/z3core.py", line 2998, in Z3_get_ast_kind
    _elems.Check(a0)
  File "/usr/local/lib/python3.10/dist-packages/z3/z3core.py", line 1482, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'not a valid ast'
```

**Comment by NikolajBjorner** [comment]
Then don't do it!
BoolRef is really internal. 
Use BoolVal or Bool to build expressions.
