### ISSUE TITLE
ERROR while compiling z3.4.8.5

### ISSUE THREAD

**Issue by zaki5m** [Z3Prover/z3#6767]
When installing the Z3 library with OPAM, I encounter the following error. Please tell me how to resolve it.
I have correctly set the environment variables.
Now, please provide the specific error message that you're encountering so that I can assist you better in resolving the issue.

```
#=== ERROR while compiling z3.4.8.5 ===========================================#
# context     2.1.4 | macos/arm64 | ocaml-base-compiler.4.12.0 | https://opam.ocaml.org#69a86674
# path        ~/.opam/4.12.0/.opam-switch/build/z3.4.8.5
# command     ~/.opam/opam-init/hooks/sandbox.sh build python2.7 scripts/mk_make.py --ml --staticlib
# exit-code   1
# env-file    ~/.opam/log/z3-75139-5072b9.env
# output-file ~/.opam/log/z3-75139-5072b9.out
### output ###
# [...]
# Copied 'z3printer.pyc'
# Copied 'z3.pyc'
# Testing ocamlc...
# Testing /Users/user/.opam/4.12.0/bin/ocamlopt...
# Traceback (most recent call last):
#   File "scripts/mk_make.py", line 18, in <module>
#     mk_bindings(API_files)
#   File "/Users/user/.opam/4.12.0/.opam-switch/build/z3.4.8.5/scripts/mk_util.py", line 3017, in mk_bindings
#     check_ml()
#   File "/Users/user/.opam/4.12.0/.opam-switch/build/z3.4.8.5/scripts/mk_util.py", line 462, in check_ml
#     raise MKException('Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.')
# mk_exception.MKException: 'Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.'
```

**Comment by NikolajBjorner** [comment]
It prints a path where you have specified OCAMLOPT so the environment variable is definitely set.

You could try to test the self-contained script, and set stdout and stderr to non-null pipes to see output.

``
def check_ml():
    t = TempFile('hello.ml')
    t.add('print_string "Hello world!\n";;')
    t.commit()
    print ('Testing %s...' % OCAMLOPT)
    r = exec_cmd([OCAMLOPT, '-o', 'a.out', 'hello.ml'])
    if r != 0:
        raise MKException('Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.')

def exec_cmd(cmd):
    if isinstance(cmd, str):
        cmd = cmd.split(' ')
    new_cmd = []
    first = True
    for e in cmd:
        if first:
            first = False
            new_cmd.append(e)
        else:
            if e != "":
                se = e.split(' ')
                if len(se) > 1:
                    for e2 in se:
                        if e2 != "":
                            new_cmd.append(e2)
                else:
                    new_cmd.append(e)
    cmd = new_cmd
    null = open(os.devnull, 'wb')
    try:
        return subprocess.call(cmd, stdout=null, stderr=null)
    except:
        # Failed to create process
        return 1
    finally:
        null.close()

```

**Comment by zaki5m** [comment]
The output showed the following error message. 
However, I can't solve this error.
Please let me know the solution.

```
ld: warning: ignoring file hello.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ld: warning: ignoring file /Users/user/.opam/4.12.0/lib/ocaml/std_exit.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file /Users/user/.opam/4.12.0/lib/ocaml/libasmrun.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Users/user/.opam/4.12.0/lib/ocaml/stdlib.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ignoring file /var/folders/dt/kch6vwlx56x3k9njbw2hydh40000gn/T/camlstartupfebea6.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking (exit code 1)

```

**Comment by jakezweifler** [comment]
I am getting the same error and have tried creating new switches on both ocaml 4.12.1 and 4.13.1. 

On the 4.12.1 switch (which I named z3_switch2), executing `which ocamlopt` prints `/Users/jzweifler/.opam/z3_switch2/bin/ocamlopt`. Here is my error code on the 4.12.1 switch: 

```#=== ERROR while compiling z3.4.12.2-1 ========================================#
# context     2.1.4 | macos/arm64 | ocaml-base-compiler.4.12.1 | https://opam.ocaml.org#78aa0376
# path        ~/.opam/z3_switch2/.opam-switch/build/z3.4.12.2-1
# command     ~/.opam/opam-init/hooks/sandbox.sh build python3 scripts/mk_make.py --ml
# exit-code   1
# env-file    ~/.opam/log/z3-37165-a391cc.env
# output-file ~/.opam/log/z3-37165-a391cc.out
### output ###
# [...]
# Copied 'z3types.cpython-38.pyc'
# Copied 'z3core.cpython-38.pyc'
# Testing ocamlc...
# Testing ocamlopt...
# Traceback (most recent call last):
#   File "scripts/mk_make.py", line 18, in <module>
#     mk_bindings(API_files)
#   File "/Users/jzweifler/.opam/z3_switch2/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 3066, in mk_bindings
#     check_ml()
#   File "/Users/jzweifler/.opam/z3_switch2/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 465, in check_ml
#     raise MKException('Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.')
# mk_exception.MKException: 'Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.' ```


> I get basically the same error message when I do this on my 4.13.1 switch: 

```#=== ERROR while compiling z3.4.12.2-1 ========================================#
# context     2.1.4 | macos/arm64 | ocaml-base-compiler.4.13.1 | https://opam.ocaml.org#78aa0376
# path        ~/.opam/4.13.1/.opam-switch/build/z3.4.12.2-1
# command     ~/.opam/opam-init/hooks/sandbox.sh build python3 scripts/mk_make.py --ml
# exit-code   1
# env-file    ~/.opam/log/z3-38031-58a0f3.env
# output-file ~/.opam/log/z3-38031-58a0f3.out
### output ###
# [...]
# Copied 'z3types.cpython-38.pyc'
# Copied 'z3core.cpython-38.pyc'
# Testing ocamlc...
# Testing ocamlopt...
# Traceback (most recent call last):
#   File "scripts/mk_make.py", line 18, in <module>
#     mk_bindings(API_files)
#   File "/Users/jzweifler/.opam/4.13.1/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 3066, in mk_bindings
#     check_ml()
#   File "/Users/jzweifler/.opam/4.13.1/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 465, in check_ml
#     raise MKException('Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.')
# mk_exception.MKException: 'Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.'```

**Comment by jakezweifler** [comment]
I am getting the same error and have tried creating new switches on both ocaml 4.12.1 and 4.13.1. 

On the 4.12.1 switch (which I named z3_switch2), executing `which ocamlopt` prints `/Users/jzweifler/.opam/z3_switch2/bin/ocamlopt`. Here is my error code on the 4.12.1 switch: 

```#=== ERROR while compiling z3.4.12.2-1 ========================================#
# context     2.1.4 | macos/arm64 | ocaml-base-compiler.4.12.1 | https://opam.ocaml.org#78aa0376
# path        ~/.opam/z3_switch2/.opam-switch/build/z3.4.12.2-1
# command     ~/.opam/opam-init/hooks/sandbox.sh build python3 scripts/mk_make.py --ml
# exit-code   1
# env-file    ~/.opam/log/z3-37165-a391cc.env
# output-file ~/.opam/log/z3-37165-a391cc.out
### output ###
# [...]
# Copied 'z3types.cpython-38.pyc'
# Copied 'z3core.cpython-38.pyc'
# Testing ocamlc...
# Testing ocamlopt...
# Traceback (most recent call last):
#   File "scripts/mk_make.py", line 18, in <module>
#     mk_bindings(API_files)
#   File "/Users/jzweifler/.opam/z3_switch2/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 3066, in mk_bindings
#     check_ml()
#   File "/Users/jzweifler/.opam/z3_switch2/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 465, in check_ml
#     raise MKException('Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.')
# mk_exception.MKException: 'Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.' 
```


I get basically the same error message when I do this on my 4.13.1 switch: 

```#=== ERROR while compiling z3.4.12.2-1 ========================================#
# context     2.1.4 | macos/arm64 | ocaml-base-compiler.4.13.1 | https://opam.ocaml.org#78aa0376
# path        ~/.opam/4.13.1/.opam-switch/build/z3.4.12.2-1
# command     ~/.opam/opam-init/hooks/sandbox.sh build python3 scripts/mk_make.py --ml
# exit-code   1
# env-file    ~/.opam/log/z3-38031-58a0f3.env
# output-file ~/.opam/log/z3-38031-58a0f3.out
### output ###
# [...]
# Copied 'z3types.cpython-38.pyc'
# Copied 'z3core.cpython-38.pyc'
# Testing ocamlc...
# Testing ocamlopt...
# Traceback (most recent call last):
#   File "scripts/mk_make.py", line 18, in <module>
#     mk_bindings(API_files)
#   File "/Users/jzweifler/.opam/4.13.1/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 3066, in mk_bindings
#     check_ml()
#   File "/Users/jzweifler/.opam/4.13.1/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 465, in check_ml
#     raise MKException('Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.')
# mk_exception.MKException: 'Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.'
```


In the code above by zaki5m, `Testing ocamlopt...` is replaced with `Testing (actual path)...`. I have this as well in some of the instances where I have run `opam install z3`.  

I have also looked into flexlink, but can't seem to find much information, other than the flexdll for windows (I have a mac with M1 chip, by the way). 

Any help would be greatly appreciated!

**Comment by wintersteiger** [comment]
This:

`building for macOS-x86_64 but attempting to link with file built for unknown-arm64`

means that the platforms of various libraries don't match; you're building for macOS, but your version of OCaml is for arm64.
