### ISSUE TITLE
"Failed testing ocamlopt compiler" while running opam install z3

### ISSUE THREAD

**Issue by jakezweifler** [Z3Prover/z3#6781]
Basically a continuation of [issue #6767](https://github.com/Z3Prover/z3/issues/6767). I have tried many different methods of installing the opam to z3 api, and have been unfruitful in all of them. Sorry this is so long, but any help would be greatly appreciated!

From my comment on 6767: 

I am getting the same error and have tried creating new switches on both ocaml 4.12.1 and 4.13.1. 

On the 4.12.1 switch (which I named z3_switch2), executing `which ocamlopt` prints `/Users/jzweifler/.opam/z3_switch2/bin/ocamlopt`. Here is my error code on the 4.12.1 switch: 

```#=== ERROR while compiling z3.4.12.2-1 ========================================#
# context     2.1.4 | macos/arm64 | ocaml-base-compiler.4.12.1 | https://opam.ocaml.org#78aa0376
# path        ~/.opam/z3_switch2/.opam-switch/build/z3.4.12.2-1
# command     ~/.opam/opam-init/hooks/sandbox.sh build python3 scripts/mk_make.py --ml
# exit-code   1
# env-file    ~/.opam/log/z3-37165-a391cc.env
# output-file ~/.opam/log/z3-37165-a391cc.out
### output ###
# [...]
# Copied 'z3types.cpython-38.pyc'
# Copied 'z3core.cpython-38.pyc'
# Testing ocamlc...
# Testing ocamlopt...
# Traceback (most recent call last):
#   File "scripts/mk_make.py", line 18, in <module>
#     mk_bindings(API_files)
#   File "/Users/jzweifler/.opam/z3_switch2/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 3066, in mk_bindings
#     check_ml()
#   File "/Users/jzweifler/.opam/z3_switch2/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 465, in check_ml
#     raise MKException('Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.')
# mk_exception.MKException: 'Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.' 
```

I get basically the same error message when I do this on my 4.13.1 switch: 

```#=== ERROR while compiling z3.4.12.2-1 ========================================#
# context     2.1.4 | macos/arm64 | ocaml-base-compiler.4.13.1 | https://opam.ocaml.org#78aa0376
# path        ~/.opam/4.13.1/.opam-switch/build/z3.4.12.2-1
# command     ~/.opam/opam-init/hooks/sandbox.sh build python3 scripts/mk_make.py --ml
# exit-code   1
# env-file    ~/.opam/log/z3-38031-58a0f3.env
# output-file ~/.opam/log/z3-38031-58a0f3.out
### output ###
# [...]
# Copied 'z3types.cpython-38.pyc'
# Copied 'z3core.cpython-38.pyc'
# Testing ocamlc...
# Testing ocamlopt...
# Traceback (most recent call last):
#   File "scripts/mk_make.py", line 18, in <module>
#     mk_bindings(API_files)
#   File "/Users/jzweifler/.opam/4.13.1/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 3066, in mk_bindings
#     check_ml()
#   File "/Users/jzweifler/.opam/4.13.1/.opam-switch/build/z3.4.12.2-1/scripts/mk_util.py", line 465, in check_ml
#     raise MKException('Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.')
# mk_exception.MKException: 'Failed testing ocamlopt compiler. Set environment variable OCAMLOPT with the path to the Ocaml native compiler. Note that ocamlopt may require flexlink to be in your path.'
```

In the code above by zaki5m, `Testing ocamlopt...` is replaced with `Testing (actual path)...`. I have this as well in some of the instances where I have run `opam install z3`.  

I have also looked into flexlink, but can't seem to find much information, other than the flexdll for windows (I have a mac with M1 chip, by the way). 

I have also tried the route of installing z3 first, via the z3 github, and running
``` 
python scripts/mk_make.py --ml
cd build
make
make install
```
Things work find without the `--ml` flag, but when I add this flag, I get the exact same `mk_exception.MKException: 'Failed testing ocamlopt compiler ...` as above. How can I fix this? I just want to use the ocaml to z3 api. 

Any help would be greatly appreciated!

**Comment by NikolajBjorner** [comment]
I guess it boils down to that the ARM build path was so-far not tested for OCaml.

**Comment by NikolajBjorner** [comment]
The ocaml support team seems busy.

![20230623_175413](https://github.com/Z3Prover/z3/assets/3085284/1bfbf91c-d327-4294-a28d-0860522dfdaa)

**Comment by NikolajBjorner** [comment]
See #6767
