### ISSUE TITLE
run docker 61948fa with error "unexpected character"

### ISSUE THREAD

**Issue by MuseMamba** [Z3Prover/z3#6799]
Thank you for your excellent work,  I try to use the docker with run command, but an error comes with "(error "line 1 column 1: unexpected character", ... multiple same errors follows)", Any clue about this?

**Comment by MuseMamba** [comment]
I also tried the gcc method, but when I ran python mk_make.py, here is what I got:
----------------------------------------------------------------
Sorry: IndentationError: unexpected indent (z3.py, line 11354)
Traceback (most recent call last):
  File "scripts/mk_make.py", line 18, in <module>
    mk_bindings(API_files)
  File "/code/z3/scripts/mk_util.py", line 3064, in mk_bindings
    cp_z3py_to_build()
  File "/code/z3/scripts/mk_util.py", line 2997, in cp_z3py_to_build
    raise MKException("failed to compile Z3Py sources")
mk_exception.MKException: 'failed to compile Z3Py sources'
----------------------------------------------------------------
I have done the apt-get steps in docker file, with python 3.8; I also tried python 2.7 but I got the same errors.

**Comment by MuseMamba** [comment]
If this is not a z3 problem, close it. Thank you for your checking.
