### ISSUE TITLE
Segfault when using bcd2 and maxhs maxsat_engines

### ISSUE THREAD

**Issue by chriswailes** [Z3Prover/z3#692]
Z3 (commit 4f5b0667) will generate a segmentation fault when processing the following formula using either the `bcd2` or `maxhs` engines:

````
(set-option :opt.maxsat_engine bcd2)
;(set-option :opt.maxsat_engine maxhs)

(declare-datatypes () ((PartID (P1) (P0))))
(declare-fun n3_p () PartID)
(declare-fun n2_p () PartID)
(declare-fun n1_p () PartID)
(declare-fun n0_p () PartID)
(declare-fun imbalance () Int)
(assert (let ((a!1 (+ 0
              (ite (= n0_p P0) 1 0)
              (ite (= n1_p P0) 1 0)
              (ite (= n2_p P0) 1 0)
              (ite (= n3_p P0) 1 0)))
      (a!2 (+ 0
              (ite (= n0_p P1) 1 0)
              (ite (= n1_p P1) 1 0)
              (ite (= n2_p P1) 1 0)
              (ite (= n3_p P1) 1 0))))
(let ((a!3 (- (ite (and true (>= a!1 a!2)) a!1 a!2)
              (ite (and true (<= a!1 a!2)) a!1 a!2))))
  (= imbalance a!3))))
(assert (<= imbalance 1))
(minimize (+ 0
   (ite (= n0_p n1_p) 0 100)
   (ite (= n0_p n2_p) 0 1)
   (ite (= n1_p n3_p) 0 1)
   (ite (= n2_p n3_p) 0 100)))
(minimize imbalance)
(check-sat)
```

The other engines produce the expected results.

A quick pass through GDB points to `model_evaluator::model_evaluator(model_core&, params_ref const&)` as the source of the segfault for bcd2.  Stack trace bellow:

```
#0  0x00000000007ac0a3 in model_evaluator::model_evaluator(model_core&, params_ref const&) ()
#1  0x00000000007aa013 in model::eval(expr*, obj_ref<expr, ast_manager>&, bool) ()
#2  0x0000000001162c5b in opt::bcd2::process_sat() ()
#3  0x0000000001164ff0 in opt::bcd2::operator()() ()
#4  0x0000000001187975 in opt::maxsmt::operator()() ()
#5  0x0000000001197a0b in opt::context::execute_maxsat(symbol const&, bool, bool) ()
#6  0x0000000001198c18 in opt::context::execute_lex() ()
#7  0x000000000119ad0f in opt::context::optimize() ()
#8  0x0000000000a27769 in cmd_context::check_sat(unsigned int, expr* const*) ()
#9  0x0000000000a5828a in smt2::parser::parse_cmd() ()
#10 0x0000000000a584c0 in smt2::parser::operator()() ()
#11 0x0000000000a47ff8 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&) ()
#12 0x0000000001248e2e in read_smtlib2_commands(char const*) ()
#13 0x000000000042a5ee in main ()
```

Similarly, the issue appears to be in `opt::hitting_sets::imp::init_weights()` for `maxhs`:

```
#0  0x0000000001170fb6 in opt::hitting_sets::imp::init_weights() ()
#1  0x0000000001171678 in opt::hitting_sets::imp::add_exists(unsigned int, unsigned int const*, bool) ()
#2  0x000000000116d047 in opt::hitting_sets::add_exists_true(unsigned int, unsigned int const*) ()
#3  0x000000000117888a in opt::maxhs::operator()() ()
#4  0x0000000001187975 in opt::maxsmt::operator()() ()
#5  0x0000000001197a0b in opt::context::execute_maxsat(symbol const&, bool, bool) ()
#6  0x0000000001198c18 in opt::context::execute_lex() ()
#7  0x000000000119ad0f in opt::context::optimize() ()
#8  0x0000000000a27769 in cmd_context::check_sat(unsigned int, expr* const*) ()
#9  0x0000000000a5828a in smt2::parser::parse_cmd() ()
#10 0x0000000000a584c0 in smt2::parser::operator()() ()
#11 0x0000000000a47ff8 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&) ()
#12 0x0000000001248e2e in read_smtlib2_commands(char const*) ()
#13 0x000000000042a5ee in main ()
```

**Comment by NikolajBjorner** [comment]
Thanks for trying these options and reporting. As these solvers are not as well tuned as the defaults wmax and maxres, I opted to deprecate them. They have now been removed.
