### ISSUE TITLE
Python bindings: Missing `importlib_resources` dependency

### ISSUE THREAD

**Issue by tyilo** [Z3Prover/z3#7041]
The newest version of `z3-solver` on PyPI (v4.12.3.0) is requires the dependency `importlib_resources`, but it is not specified as a dependency.

Thus the z3 bindings for Python isn't working out of the box:
```
$ mkdir /tmp/z3-test
$ cd /tmp/z3-test
$ python -mvenv venv
$ venv/bin/pip install z3-solver
$ venv/bin/python -c 'import z3; print(z3)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/z3-test/venv/lib/python3.11/site-packages/z3/__init__.py", line 1, in <module>
    from .z3 import *
  File "/tmp/z3-test/venv/lib/python3.11/site-packages/z3/z3.py", line 46, in <module>
    from . import z3core
  File "/tmp/z3-test/venv/lib/python3.11/site-packages/z3/z3core.py", line 7, in <module>
    import importlib_resources
ModuleNotFoundError: No module named 'importlib_resources'
```

Installing the `importlib_resources` dependency manually fixes the problem:
```
$ venv/bin/pip install importlib_resources
$ venv/bin/python -c 'import z3; print(z3)'
<module 'z3' from '/tmp/z3-test/venv/lib/python3.11/site-packages/z3/__init__.py'>
```

**Comment by NikolajBjorner** [comment]
Python 3.9 and up now use the built-in version thanks to https://github.com/Z3Prover/z3/pull/7042

**Comment by NikolajBjorner** [comment]
what is the location to add install_requires?

**Comment by youchangkim** [comment]
If you use `setup.py` to build the wheels, you can add `install_requires` in the `setup` function.
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html

**Comment by NikolajBjorner** [comment]
so pyproject.toml

```
[build-system]
requires = ["setuptools>=46.4.0", "wheel", "cmake"]
build-backend = "setuptools.build_meta"
```

becomes
```
[build-system]
requires = ["setuptools>=46.4.0", "wheel", "cmake", "importlib_resources"]
build-backend = "setuptools.build_meta"
```

?

**Comment by youchangkim** [comment]
I'm not super familiar with pyproject.toml, but it should go under `[project]`.
```
[project]
dependencies = [
    "importlib_resources",
]
```

**Comment by whyitfor** [comment]
What release fixes this issue?
