### ISSUE TITLE
z3 crashes with duality engine

### ISSUE THREAD

**Issue by YuliaDemyanova** [Z3Prover/z3#765]
Hello. I'm using the master branch. I get a SEGFAULT when I run z3 on the following input:

```
(set-option :fixedpoint.engine duality)
(set-logic HORN)
(set-info :status unknown)
(declare-fun inv_main4 (Int Int) Bool)
(declare-fun inv_main5 (Int Int) Bool)
(assert (or (not (and true true ) ) (inv_main4 1 0 ) ) )
(assert (forall ((var0 Int)) (forall ((var1 Int)) (or (not (and (inv_main4 var0 var1 ) (not (<= 0 (+ (+ 1024 (* (- 1) var1 ) ) (- 1) ) ) ) ) ) (inv_main5 var0 var1 ) ) ) ) )
(assert (forall ((var0 Int)) (forall ((var1 Int)) (or (not (and (inv_main4 var0 var1 ) (<= 0 (+ (+ 1024 (* (- 1) var1 ) ) (- 1) ) ) ) ) (inv_main4 0 (+ var1 1 ) ) ) ) ) )
(assert (forall ((var0 Int)) (forall ((var1 Int)) (not (and (inv_main5 var0 var1 ) (and true (not (= var0 0 ) ) ) ) ) ) ) )
(check-sat)
```

Stack trace:

```
#0  0x0000000000775662 in Duality::RPFP::SuffixVariable(Duality::expr const&, int) ()
#1  0x00000000007797ae in Duality::RPFP::RedVars(Duality::RPFP::Node*, Duality::expr&, std::vector<Duality::expr, std::allocator<Duality::expr> >&) ()
#2  0x0000000000783c05 in Duality::RPFP::GetUpperBound(Duality::RPFP::Node*) ()
#3  0x0000000000783f65 in Duality::RPFP::AssertNode(Duality::RPFP::Node*) ()
#4  0x00000000007c31a6 in Duality::Duality::ExpandNode(Duality::RPFP::Node*) ()
#5  0x00000000007c4ee3 in Duality::Duality::TryExpandNode(Duality::RPFP::Node*) ()
#6  0x00000000007c77d4 in Duality::Duality::PreSolve() ()
#7  0x00000000007ca91b in Duality::Duality::Solve() ()
#8  0x0000000000555c32 in Duality::dl_interface::query(expr*) ()
#9  0x00000000005506f7 in horn_tactic::imp::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) ()
#10 0x0000000000ed464e in cleanup_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) ()
#11 0x0000000000edc544 in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) ()
#12 0x0000000000edc99a in check_sat(tactic&, ref<goal>&, ref<model>&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::string&) ()
#13 0x0000000000d385db in tactic2solver::check_sat_core(unsigned int, expr* const*) ()
#14 0x0000000000d347ff in solver_na2as::check_sat(unsigned int, expr* const*) ()
#15 0x0000000000d3b9d3 in combined_solver::check_sat(unsigned int, expr* const*) ()
#16 0x0000000000c5ec63 in cmd_context::check_sat(unsigned int, expr* const*) ()
#17 0x0000000000c49478 in smt2::parser::parse_check_sat() ()
#18 0x0000000000c51398 in smt2::parser::operator()() ()
#19 0x0000000000c40d88 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&) ()
#20 0x00000000004226b8 in read_smtlib2_commands(char const*) ()
#21 0x00000000004114d3 in main ()
```

Thank you.

**Comment by NikolajBjorner** [comment]
Closing as the code that was exercised in this issue is no longer part of the code base, #1646.
