### ISSUE TITLE
z3 crashes with segfault

### ISSUE THREAD

**Issue by YuliaDemyanova** [Z3Prover/z3#792]
Hello. I'm using the master branch. I get a SEGFAULT when I run z3 on the following input:
```
(set-logic HORN)
(set-info :status unknown)
(declare-fun inv_main4 (Int Int) Bool)
(declare-fun inv_main5 (Int Int) Bool)
(assert (forall ((var0 Int)) (inv_main4 0 var0 ) ) ) 
(assert (forall ((var0 Int)) (forall ((var1 Int)) (or (not (and (inv_main4 var1 var0 ) (not (<= 0 (+ (+ var0 (* (- 1) var1 ) ) (- 1) ) ) ) ) ) (inv_main5 var1 var0 ) ) ) ) ) 
(assert (forall ((var0 Int)) (forall ((var1 Int)) (or (not (and (inv_main4 var1 var0 ) (<= 0 (+ (+ var0 (* (- 1) var1 ) ) (- 1) ) ) ) ) (inv_main4 (+ var1 2 ) var0 ) ) ) ) ) 
(assert (forall ((var0 Int)) (forall ((var1 Int)) (not (and (inv_main5 var1 var0 ) (forall ((var2 Int)) (or (not (and (and (and (and (<= 0 (+ (+ 2 (* (- 1) var2 ) ) (- 1) ) ) (<= 0 (+ (+ 2 (* 1 var2 ) ) (- 1) ) ) ) (or (not (<= 0 (+ var2 (- 1) ) ) ) (<= 0 (+ var1 (- 1) ) ) ) ) (or (not (<= 0 (+ (* (- 1) var2 ) (- 1) ) ) ) (<= 0 (+ (* (- 1) var1 ) (- 1) ) ) ) ) (exists ((var3 Int)) (= var1 (+ (* 2 var3 ) var2 ) ) ) ) ) (= var2 0 ) ) ) ) ) ) ) )
(check-sat)
```

Stack trace:
```
#0  0x0000000000edef7c in model_implicant::process_formula(app*, ptr_vector<expr>&, ptr_vector<expr>&) ()
#1  0x0000000000ee5109 in model_implicant::collect(ptr_vector<expr> const&, ptr_vector<expr>&) ()
#2  0x0000000000ee5839 in model_implicant::minimize_literals(ptr_vector<expr> const&, ref<model>&) ()
#3  0x000000000059b092 in pdr::context::create_children(pdr::model_node&) ()
#4  0x000000000059bd5c in pdr::context::expand_node(pdr::model_node&) ()
#5  0x000000000059bff2 in pdr::context::check_reachability(unsigned int) ()
#6  0x000000000059c105 in pdr::context::solve_impl() ()
#7  0x000000000059e41e in pdr::context::solve() ()
#8  0x0000000000589abb in pdr::dl_interface::query(expr*) ()
#9  0x00000000005506f7 in horn_tactic::imp::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) ()
#10 0x0000000000ed464e in cleanup_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) ()
#11 0x0000000000edc544 in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) ()
#12 0x0000000000edc99a in check_sat(tactic&, ref<goal>&, ref<model>&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::string&) ()
#13 0x0000000000d385db in tactic2solver::check_sat_core(unsigned int, expr* const*) ()
#14 0x0000000000d347ff in solver_na2as::check_sat(unsigned int, expr* const*) ()
#15 0x0000000000d3b9d3 in combined_solver::check_sat(unsigned int, expr* const*) ()
#16 0x0000000000c5ec63 in cmd_context::check_sat(unsigned int, expr* const*) ()
#17 0x0000000000c49478 in smt2::parser::parse_check_sat() ()
#18 0x0000000000c51398 in smt2::parser::operator()() ()
#19 0x0000000000c40d88 in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&) ()
#20 0x00000000004226b8 in read_smtlib2_commands(char const*) ()
#21 0x00000000004114d3 in main ()
``` 

This is a different bug from issue #765 which I reported before.
Thank you.

**Comment by NikolajBjorner** [comment]
The formulas are not in the fragment handled by PDR. They contain a non-ground sub-formula with an existential quantifier. I now added an exception pass to detect this and just fail instead of crashing.

**Comment by YuliaDemyanova** [comment]
Thank you.
