### ISSUE TITLE
"python scripts/mk_make.py" fails and "make" fails

### ISSUE THREAD

**Issue by proteusGIT** [Z3Prover/z3#865]
Attempted to use
```
python scripts/mk_make.py
cd build
make
sudo make install
```

However, this fails.
```
Copied 'z3consts.cpython-34.pyc'
Testing ar...
Testing g++...
Testing gcc...
Testing floating point support...
Testing OpenMP...
Host platform:  Linux
C++ Compiler:   g++
C Compiler  :   gcc
Archive Tool:   ar
Arithmetic:     internal
OpenMP:         True
Prefix:         /usr
64-bit:         True
FP math:        SSE2-GCC
Python pkg dir: /usr/lib64/python3.4/site-packages
Python version: 3.4
Writing build/Makefile
Traceback (most recent call last):
  File "scripts/mk_make.py", line 21, in <module>
    mk_makefile()
  File "/home/XXX/Downloads/z3-master/scripts/mk_util.py", line 2601, in mk_makefile
    c.mk_makefile(out)
  File "/home/XXX/Downloads/z3-master/scripts/mk_util.py", line 1154, in mk_makefile
    Component.mk_makefile(self, out)
  File "/home/XXX/Downloads/z3-master/scripts/mk_util.py", line 1030, in mk_makefile
    self.add_cpp_rules(out, include_defs, cppfile)
  File "/home/XXX/Downloads/z3-master/scripts/mk_util.py", line 988, in add_cpp_rules
    self.add_rule_for_each_include(out, cppfile)
  File "/home/XXX/Downloads/z3-master/scripts/mk_util.py", line 967, in add_rule_for_each_include
    owner = self.find_file(include, fullname)
  File "/home/XXX/Downloads/z3-master/scripts/mk_util.py", line 951, in find_file
    raise MKException("Failed to find include file '%s' for '%s' when processing '%s'." % (fname, ownerfile, self.name))
mk_exception.MKException: "Failed to find include file 'polynomial_factorization.h' for 'src/test/polynomial_factorization.cpp' when processing 'test'."
```

```
src/smt/smt_context.cpp
../src/smt/smt_context.cpp: In member function ‘bool smt::context::propagate_atoms()’:
../src/smt/smt_context.cpp:1416:33: error: expected unqualified-id before ‘not_eq’ token
                         literal not_eq = literal(l.var(), true);
                                 ^
../src/smt/smt_context.cpp:1417:135: error: expected primary-expression before ‘not_eq’ token
                         set_conflict(b_justification(mk_justification(eq_propagation_justification(get_enode(lhs), get_enode(rhs)))), not_eq);                        
                                                                                                                                       ^
../src/smt/smt_context.cpp:1417:141: error: expected primary-expression before ‘)’ token
                         set_conflict(b_justification(mk_justification(eq_propagation_justification(get_enode(lhs), get_enode(rhs)))), not_eq);                        
                                                                                                                                             ^
Makefile:2416: recipe for target 'smt/smt_context.o' failed
make: *** [smt/smt_context.o] Error 1
```

**Comment by wintersteiger** [comment]
Knock-on effect of #852, fixed.
