### ISSUE TITLE
Z3 fails to find libz3java on windows

### ISSUE THREAD

**Issue by lednhatkhanh** [Z3Prover/z3#894]
Error message:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no libz3java in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at com.microsoft.z3.Native.<clinit>(Native.java:14)
	at com.microsoft.z3.Global.ToggleWarningMessages(Global.java:87)
	at main.JavaExample.main(JavaExample.java:2270)
```

**Comment by wintersteiger** [comment]
Your program needs to be able to access libz3.dll as well as libz3java.dll (or .so, .dylib). Both of them need to be in your PATH and/or Java wants to see libz3java.dll in it's `java.library.path`, i.e., on the command line like so: `java -Djava.library.path=C:\path\to\dll`.

Note that all DLL/so/dylib's have to have the same bit-ness as your Java installation. I.e., a 32-bit Java will not load a 64-bit DLL and it may not report any useful error messages if that is the case (it will just throw an UnsatisfiedLinkError without any other information pointing to the underlying issue).
