### ISSUE TITLE
Segfault in `sat::solver::get_reachable`

### ISSUE THREAD

**Issue by mossberg** [Z3Prover/z3#901]
Hi! I get a segfault if I run the below file in z3. I'm on Z3 4.5.0, Ubuntu 16.04.

```
(set-logic QF_AUFBV)
(set-option :global-decls false)
(declare-fun V_2 () (_ BitVec 32))
(declare-fun aux51 () (_ BitVec 8))(assert (= aux51 ((_ extract 31 24) #x00000000)))
(declare-fun aux52 () (_ BitVec 8))(assert (= aux52 ((_ extract 23 16) #x00000000)))
(declare-fun aux53 () (_ BitVec 8))(assert (= aux53 ((_ extract 15 8) #x00000000)))
(declare-fun aux54 () (_ BitVec 8))(assert (= aux54 ((_ extract 7 0) #x00000000)))
(declare-fun aux55 () (_ BitVec 8))(assert (= aux55 ((_ extract 31 24) #x00000000)))
(declare-fun aux56 () (_ BitVec 8))(assert (= aux56 ((_ extract 23 16) #x00000000)))
(declare-fun aux57 () (_ BitVec 8))(assert (= aux57 ((_ extract 15 8) #x00000000)))
(declare-fun aux58 () (_ BitVec 8))(assert (= aux58 ((_ extract 7 0) #x00000000)))
(declare-fun aux59 () (_ BitVec 32))(assert (= aux59 (concat aux55 aux56 aux57 aux58)))
(declare-fun aux60 () (_ BitVec 32))(assert (= aux60 (concat aux55 aux56 aux57 aux58)))
(assert (= V_2 aux60))
(declare-fun V_3 () (_ BitVec 32))
(push 1)
(assert (bvuge V_2 V_3))
(maximize V_3)
(check-sat)
```

```
0x00000000010e3253 in sat::solver::get_reachable(sat::literal, sat::literal_set const&, sat::literal_set&) ()
(gdb) bt
#0  0x00000000010e3253 in sat::solver::get_reachable(sat::literal, sat::literal_set const&, sat::literal_set&) ()
#1  0x00000000010e4adf in sat::solver::find_mutexes(svector<sat::literal, unsigned int> const&, vector<svector<sat::literal, unsigned int>, true, unsigned int>&) ()
#2  0x00000000005102be in inc_sat_solver::find_mutexes(ref_vector<expr, ast_manager> const&, vector<ref_vector<expr, ast_manager>, true, unsigned int>&) ()
#3  0x00000000004d56ce in maxres::process_mutex() ()
#4  0x00000000004d691b in maxres::operator()() ()
#5  0x00000000004c30f9 in opt::maxsmt::operator()() ()
#6  0x00000000004b1d52 in opt::context::execute_maxsat(symbol const&, bool, bool) ()
#7  0x00000000004b6bd3 in opt::context::optimize() ()
#8  0x0000000000c1d7af in cmd_context::check_sat(unsigned int, expr* const*) ()
#9  0x0000000000c0312b in smt2::parser::operator()() ()
#10 0x0000000000bf1cbb in parse_smt2_commands(cmd_context&, std::istream&, bool, params_ref const&) ()
#11 0x0000000000424e8e in read_smtlib2_commands(char const*) ()
#12 0x000000000040f823 in main ()
```

**Comment by NikolajBjorner** [comment]
Yes, this is a known bug in 4.5. It was fixed in the current master branch.

**Comment by NikolajBjorner** [comment]
can I close this?

**Comment by mossberg** [comment]
Yes, thank you!
