### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc'

### ISSUE THREAD

**Issue by farao** [Z3Prover/z3#902]
Hi,

I'm having trouble installing Z3. I'm using the package from the Arch User Repostitory and I initially commented on the problem there, but it doesn't seem to be Archlinux specific and we couldn't solve the issue so I'm creating this one here, hope it is the right step.

This is the error I'm getting:
 ...
Testing ar...
Testing g++...
Testing gcc...
Testing floating point support...
Testing OpenMP...
Traceback (most recent call last):
File "scripts/mk_make.py", line 21, in <module>
mk_makefile()
File "/home/xy/.cache/pacaur/z3/src/z3-z3-4.5.0/scripts/mk_util.py", line 2567, in mk_makefile
mk_config()
File "/home/xy/.cache/pacaur/z3/src/z3-z3-4.5.0/scripts/mk_util.py", line 2434, in mk_config
if is_CXX_clangpp():
File "/home/xy/.cache/pacaur/z3/src/z3-z3-4.5.0/scripts/mk_util.py", line 885, in is_CXX_clangpp
return is_clang_in_gpp_form(CXX)
File "/home/xy/.cache/pacaur/z3/src/z3-z3-4.5.0/scripts/mk_util.py", line 881, in is_clang_in_gpp_form
return str(version_string).find('clang') != -1
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 181: ordinal not in range(128)

clang is installed:
$ clang --version
clang version 3.9.1 (tags/RELEASE_391/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

For reference the comments at the AUR and what we tried so far: https://aur.archlinux.org/packages/z3/#news

**Comment by wintersteiger** [comment]
Yes, that's another one of those unicode decoding problems, we've fixed a bunch of them in our scripts already but some still remain. This particular one has been fixed recently (https://github.com/Z3Prover/z3/pull/829), so updating to the latest master sources should fix this issue for you.
