### ISSUE TITLE
crash on malformed bv expression through API

### ISSUE THREAD

**Issue by nunoplopes** [Z3Prover/z3#98]
The following script crashes on Cygwin 32 (but not 64):
```
from z3 import *
print ZeroExt(2, ZeroExt(2, BitVecVal(0, 3))) - BitVecVal(0, 5)
```

stack trace:

```
#0  0x6c1229de in format_ns::mk_compose(ast_manager&, app*, app*, app*, app*)
    () from libz3.dll
#1  0x6c0ef068 in app* format_ns::mk_seq1<app**, format_ns::f2f>(ast_manager&, app** const&, app** const&, format_ns::f2f, char const*, char const*, char const*) [clone .constprop.201] () from libz3.dll
#2  0x6c0ef28b in smt2_pp_environment::pp_sort(sort*) ()
   from libz3.dll
#3  0x6c0f11a9 in ast_smt2_pp(std::ostream&, sort*, smt2_pp_environment&, params_ref const&, unsigned int) () from libz3.dll
#4  0x6c0f3845 in operator<<(std::ostream&, mk_ismt2_pp const&) ()
   from libz3.dll
#5  0x6c0d83b8 in ast_manager::check_sort(func_decl const*, unsigned int, expr* const*) const () from libz3.dll
#6  0x6c0d86a6 in ast_manager::check_sorts_core(ast const*) const ()
   from libz3.dll
#7  0x6c0d8768 in ast_manager::check_sorts(ast const*) const ()
   from libz3.dll
#8  0x6bc75017 in api::context::check_sorts(ast*) ()
   from libz3.dll
#9  0x6bc60f68 in Z3_mk_bvsub () from libz3.dll
```

**Comment by nunoplopes** [comment]
Update: this happens only with -O3, but not with -O2.
GCC is assuming the stack is 16-byte aligned and issuing a 'movaps' instruction. Since memory is actually not aligned, we get a crash.  Investigating whether it's Z3's fault or a bug in GCC 4.9..

**Comment by nunoplopes** [comment]
Duplicate of issue #86.
